### ISSUE TITLE
function CBLDatabase documentWithID error when running with Xcode 8.2, work well on Xcode 7.3

### ISSUE THREAD

**Issue by nguoithichkhampha** [couchbase/couchbase-lite-ios#1542] opened 2017-01-09 04:23 UTC
I run same test iOS project on Xcode 7.3 and Xcode 8.2 .
Result failed with Xcode 8.2 and Successful with Xcode 7.3
This is my code:
-database file is existed docID "IDtest1"

```
- (void)test00_ReplaceDatabase {
    // This is an example of a functional test case.
    // Use XCTAssert and related functions to verify your tests produce the correct results.
    // set up storage type default is ForestDB
    [[CBLManager sharedInstance]setStorageType:kCBLForestDBStorage];
    NSLog(@"Root directory: %@",[[CBLManager sharedInstance]directory]);
    NSError *error;
    database = [[CBLManager sharedInstance] existingDatabaseNamed: @"emotiv_cortex"error: &error];
    if(database)
    {
        NSLog(@"Exits database");
        XCTAssertGreaterThan([database documentCount], 0);
    }
    else
    {
        NSString *dbPath = [[NSBundle bundleForClass:[self class]] pathForResource:@"database" ofType:@"cblite2"];
        XCTAssertNotNil(dbPath);
         BOOL result = [[CBLManager sharedInstance] replaceDatabaseNamed:@"emotiv_cortex" withDatabaseDir:dbPath error:&error];
        XCTAssertTrue(result);
        database = [[CBLManager sharedInstance] existingDatabaseNamed: @"emotiv_cortex"error: &error];
        XCTAssertGreaterThan([database documentCount], 0);
    }
}

-(void)test01_ReadDocument{
    CBLDocument* doc = [database documentWithID:@"IDtest1"];
    XCTAssertNotNil(doc);
}
```

--------
* Version:   1.3
* Client OS: iOS 10 
* Server:    NAME_AND_VERSION

**Comment by nguoithichkhampha** [comment] 2017-01-13 17:28
@pasin . Yes, I see [error](https://drive.google.com/file/d/0B8bxPvVNitWjYmRZbE45WWVFZDg/view?usp=sharing)

**Comment by pasin** [comment] 2017-01-13 21:37
The assertion error just means that there is no documents in the database. Did you add any documents?

**Comment by nguoithichkhampha** [comment] 2017-01-16 03:45
yes, as I said:

> database file is existed docID "IDtest1"

**Comment by pasin** [comment] 2017-01-16 16:52
This seems to be unit tests issue. A couple of thing to check:

1. Put a breakpoint in the first line of `test01_ReadDocument` and check if the `database` is nil or not. If the database is nil, I guessed that either `test01_ReadDocument` or `test02_DeleteDatabase` was run before `test00_ReplaceDatabase`.

2. Check unit test's -setup or -teardown that might empty the database?

**Comment by pasin** [comment] 2017-01-16 19:44
I can confirm that XCode8 doesn't run the unit tests in alphabetical order anymore. Please check the order that your unit tests run. I'm closing the issue now. If the issue is something else, we can reopen the issue. Thanks.

**Closed by pasin** 2017-01-16 19:44 UTC
Labels: needsmoreinfo

**Comment by nguoithichkhampha** [comment] 2017-01-17 02:22
Thank you for your support.
