### ISSUE TITLE
CouchbaseLite Code=10409 "rejected by server"

### ISSUE THREAD

**Issue by srinadh-k** [couchbase/couchbase-lite-ios#2245] opened 2018-12-03 15:44 UTC
--------
* Version:   Couchbase Mobile 2.1.2 iOS Swift
* Client OS: iOS 12.1
* Server:    Couchbase Server 6.0

Documents are rejected by the server, Because of this my application working very weird behavior. 
<img width="972" alt="screenshot 2018-12-03 at 9 14 51 pm" src="https://user-images.githubusercontent.com/28667119/49384211-89670d80-f740-11e8-9dc3-4d3508da617f.png">

**Comment by pasin** [comment] 2018-12-03 16:21
Do you have sync function that rejects the document?

**Comment by srinadh-k** [comment] 2018-12-03 17:06
No, I don't have sync function in my sync gateway config. you can see the attachment.

{
	"adminInterface": "127.0.0.1:4985",
	"interface": "0.0.0.0:4984",
    "log": ["*"],
    "databases": {
        "staging": {
            "server": "http://localhost:8091",
            "bucket": "staging",
            "username": "test",
            "password": "testpass",
            "enable_shared_bucket_access": true,
            "import_docs": "continuous",
            "num_index_replicas": 0,
            "users": { 
                       "user1": { "disabled": false, "password" : "testpass", "admin_channels": ["*"] }
                    }
        },
        "qabucket": {
            "server": "http://localhost:8091",
            "bucket": "qabucket",
            "username": "test",
            "password": "testpass",
            "enable_shared_bucket_access": true,
            "import_docs": "continuous",
            "num_index_replicas": 0,
            "users": { 
                       "user1": { "disabled": false, "password" : "test123", "admin_channels": ["*"] }
                    }
        }
    }
}

**Comment by pasin** [comment] 2018-12-04 18:49
Look like there is no sync-function. Then the only reason I can think of is that the document got rejected due to conflict. SG 2.x doesn't allow conflict anymore and the conflict needs to be resolved before it can be push again. The normal flow is that CouchbaseLite pull replicator will pull the update from SG and resolve the conflict based on rules which is most active branch win. 

@srinadh-k , I have a couple questions to ask.
1. Do you have pull replicator running as well? Pull replicator is required for resolving the conflict.

2. If you do have pull replicator running, what is the unexpected behavior that you have seen?

**Comment by pasin** [comment] 2018-12-04 19:05
The reject error is considered harmless and the document should be pulled, resolved, and pushed again automatically. 

Do I understand correctly that you don't see new update (resolved conflict) on either SG or client at all after rejection until restarting the replicator? Could you please double check? If so, this sound like a bug.

**Comment by srinadh-k** [comment] 2018-12-04 19:12
Yes, your correct I don't see resolved conflict on either SG or in client at all after rejection and until i restart the replicator. i really wonder why should we need to restart replicator.

But i will cross verify and will send you a big log with all verbose turn on... 
so you can track it easily.

**Comment by pasin** [comment] 2018-12-04 19:14
I don't think number of nodes is an issue. Thanks for all info.

**Comment by srinadh-k** [comment] 2018-12-06 12:02
@pasin 
Here is my test case. you can check it. 
I used N1QL rest API in iPhone app and i got few records in iPhone and based on records i updated my doc status by using N1QL update Rest API and send to server. On my other application running on iPad and it has native Couchbase Lite with a live query. 
 So in Ipad some operations will done automatically by using IOT devices and it will store it into couchbase. Here i am getting conflicts and those are not fixing automatically. So when i re-run the iPad app (kill the app and open it. replicator will start again.) conflicts are fixing automatically and my iPhone app has live query and if any data matches with my records. it will update the design in iPHone app. 

The main reason i am using N1QL on my iPhone is... sometimes i am getting 20 records and sometimes 18 records whereas actually records count is 20. So i used N1QL for Get records on inital page and used live query with couchbase lite sdk for update the status of the record on iPhone display. 

You can see conflicts.txt file first and then i kill the app and re-run it. i got conflict free. so you can check re-run.txt file. 


[Conflicts.txt](https://github.com/couchbase/couchbase-lite-ios/files/2652947/Conflicts.txt)
[Resolved On Re-run.txt](https://github.com/couchbase/couchbase-lite-ios/files/2652945/Resolved.On.Re-run.txt)

**Comment by snej** [comment] 2018-12-21 02:09
@srinadh-k As I already said elsewhere: since you are an enterprise customer, please contact Couchbase support if you need help urgently. Spamming our Github issues is not going to help.

**Comment by srinadh-k** [comment] 2018-12-21 02:11
> @srinadh-k As I already said elsewhere: since you are an enterprise customer, please contact Couchbase support if you need help urgently. Spamming our Github issues is not going to help.

I can understand, But I am just doubted, can I ask there or not? But I will ask there. Thanks for your promote reply.

**Comment by pasin** [comment] 2019-01-02 18:19
@srinadh-k I have looked at [Conflicts.txt](https://github.com/couchbase/couchbase-lite-ios/files/2652947/Conflicts.txt) and the followings are the documents that got rejected when pushing to the SG:

```
-MGsN5p1Y6tnapbEykhMFFA
-hYkAhMktu49fBfa6HKzIjD
-TxWqFGI02sIZtFiCqzO8dp
```

However from the same Conflicts.txt file, all of them got resolved later on by the pull replication. I might have missed something so could you provide me the document ID of the document that has the issue. As @snej said, it's better to communicate through the customer support as you are a customer and I believe you have done that. Please provide more detail about the document that has the issue so we could investigate the issue further.

**Comment by srinadh-k** [comment] 2019-01-02 18:51
Yes, after some time, it got resolved, But today I posted in the support team. it took 24 min to resolve conflicts automatically. is there any time duration, why it took a long time for the single document to resolve automatically?

Here you can find my query in customer support

https://support.couchbase.com/hc/en-us/requests/25823?page=2#comments

**Comment by pasin** [comment] 2019-01-02 19:12
There is no time limit. It depends on when the document gets pulled from SG. Does the app also pull a lot of changes from SG at the same time?

**Comment by srinadh-k** [comment] 2019-01-02 20:03
Sometimes I get lots of changes to pull from SG. But I need to check at what case I am getting conflicts. so if I prevent it. somehow application looks good.

**Comment by snej** [comment] 2019-01-03 18:46
@srinadh-k, please work this out with the customer support engineers, not here. Carrying on the same conversation both there and here is confusing and risks duplicating effort.

**Comment by srinadh-k** [comment] 2019-01-04 07:59
@snej Sure, I will follow up in Customer Support page.

**Comment by djpongh** [comment] 2019-01-18 22:37
Tracking this in the CBSE

**Closed by djpongh** 2019-01-18 22:37 UTC
Labels: P1: high, ffc, ready
