### ISSUE TITLE
_active_tasks returns a wrong task status

### ISSUE THREAD

**Issue by jfenderico** [couchbase/couchbase-lite-ios#565] opened 2015-01-15 19:32 UTC
The "_active_tasks" endpoint returns a wrong task status when switching between online and offline modes.

Test case:

- Run the app with Internet connection enabled and make a request to the path "_active_tasks". This will return the status "Processed 0 / 0 ..." or "Idle".
- Disable connection (airplane mode) and make the same request. This will return the last status previous before going offline, so it'll be "Processed 0/0..." or "Idle". However, it should be "Offline".
- Enable connection and make a new request. This will return the previous status before going online, so it'll be "Offline". However, it should be "Idle" or "Active.

**Comment by snej** [comment] 2015-01-15 20:13
How are you making the request? I.e. is this a PhoneGap app?
There's no caching in the `_active_tasks` handler, so I don't know why its results would be out of date.

**Comment by snej** [comment] 2015-01-15 20:23
Also, what version of Couchbase Lite?

**Comment by jfenderico** [comment] 2015-01-15 21:59
I'm sorry for the lack of details. Yes, it's a Phonegap app. I'm using coax to make the HTTP request, but I also tried making the requests from the Safari's console. I'm using The Couchbase Lite version 1.0.3.

**Comment by pasin** [comment] 2015-02-27 00:11
I just tested it with the phonegap plugin (v1.0.3-64bit) installed directly from the [Couchbase-Lite-PhoneGap-Plugin] (https://github.com/couchbaselabs/Couchbase-Lite-PhoneGap-Plugin) repo which includes couchbase-lite-ios v1.0.3.1. 

However I couldn't reproduce the issue. When the airplane mode is on, the status was 'offline' and when the airplane mode is off, the status was 'idle'. I looked at the source code both couchbase-lite-ios and the PhoneGap plugin, and I couldn't spot anything wrong that could return the out-of-date result. I'm not sure what went wrong. Would it be possible to share your app or test app that I can check the issue out?

@jchris do you have any ideas what could went wrong with the out-of-date status when calling _active_tasks from PhoneGap?

**Comment by jfenderico** [comment] 2015-02-27 11:26
I check out the status in my code every one or two seconds and, as I explained in the issue description, you get the wrong status only when you change the airplane mode.

The test case would be like the following:
- Run the app with airplane mode off. This will work well. You'll see "Processed ..." status on every function call until the status changes to "Idle.
- Now, change to airplane mode on. Open up the app and start up the sync process again. You won't see the status "Offline" at the end of the process.
- Change the airplane mode back to off. Open up the app again. You'll see "Offline" instead of "Processed ..." or "Idle" status.

Has there been any update in the couchbase-lite-ios plugin since the issue report? If so, I could run my tests again.

**Comment by pasin** [comment] 2015-02-28 01:03
First I don't see any update or bug fixes related to this issue. Anyway, I did try to reproduce this second time this afternoon by using your steps but still no luck. I did get your 2nd bullet once but it was my mistake that I had both airplane and wifi mode enabled at the same time. I tested with an iPhone 6 (8.1.2) and looked at the javascript console from the safari (8.03)'s web inspector on my mac (10.10.2).

Could you load my test project, run, and post the result back? When the open is opened, it will create a local database and start a continuous push and pull replicator. I print the _active_tasks result to the console every 3 seconds. I also used coax to access the rest APIs.

1. Clone the repo and checkout the test project:
```
$git clone https://github.com/pasin/couchbase.git
$git checkout test/phonegap-active-tasks
```
2. Open www/js/index.js and modify the following line:
```
var syncUrl = "http://<server>:<port>/<database>";
```
3. Run the iOS platform
```
$phonegap run ios
```
4. Check the result from the safari web inspector console. You may need to do COMMAND-R to reconnect the app with the inspector to see log messages on the console.

**Comment by pasin** [comment] 2015-03-06 19:03
I'm closing the issue as not reproducible now. Please feel free to reopen the issue again if you have more information to share.

**Comment by jfenderico** [comment] 2015-03-06 19:05
Ok. I'm sorry, I haven't had time to run your project. I'll reopen it when I have more info. Thanks,

**Closed** 2015-03-06 19:06 UTC
Labels: f: REST, in progress, needsmoreinfo, P3: low, S4: minor, size-medium
