### ISSUE TITLE
LiteServ logs disconnect warnings

### ISSUE THREAD

**Issue by ashvindersingh** [couchbase/couchbase-lite-ios#973] opened 2015-11-11 18:00 UTC
01:28:38.148‖ WARNING: CBLHTTPConnection: Client disconnected: Error Domain=GCDAsyncSocketErrorDomain Code=4 "Read operation timed out" UserInfo=0x7f8cc2b5b7b0 {NSLocalizedDescription=Read operation timed out}

Found in release:1.1.1

Steps: 
- Download and unpack the latest 1.1.1 build
- Setup local sync gateway
- Launch LiteServ pointing to local sync gateway and setup pull replication
- Add document on SG using SG rest api
- After certain amount of time. Liteserv throws above warning.

**Comment by snej** [comment] 2015-11-11 18:19
Can you reproduce this on the release/1.2 branch? At this point the 1.1.1 sourcebase is pretty old.

**Comment by snej** [comment] 2015-11-11 18:22
Wait, I don't think I understand the steps to reproduce. The warning is from CBLHTTPConnection, which is part of the listener — it handles an _incoming_ REST call to LiteServ. But the directions above refer to LiteServ pulling from SG, which isn't going to involve the listener at all.

**Comment by ashvindersingh** [comment] 2015-11-11 18:57
ah my bad, Please try the following steps. This should reproduce the issue: 
Build: http://latestbuilds.hq.couchbase.com/couchbase-lite-ios/0.0.0/ios/0.0.0-550/
1. Launch liteserv --port 49840
2. Create a database using REST API http://localhost:49840/local_db_01
3. Wait for about 2 min
4. Warning appears on stdout:
10:54:20.043‖ WARNING: CBLHTTPConnection: Client disconnected: Error Domain=GCDAsyncSocketErrorDomain Code=4 "Read operation timed out" UserInfo=0x7fc4c3d0e700 {NSLocalizedDescription=Read operation timed out}

**Comment by snej** [comment] 2015-11-12 23:04
Can't reproduce this — I've used both curl and httpie to send the PUT request, and waited 5 minutes afterwards, but got no warnings. Can you describe exactly what you did in step 2?

**Comment by ashvindersingh** [comment] 2015-11-13 00:13
Reruning the above scenario with CURL did not generate the warning. However the warnings appear when using liteserv with nodejs or using POSTMAN http client.

**Comment by snej** [comment] 2015-11-16 17:19
This happens if the client uses a keep-alive connection, so the socket stays open after the first request, but then doesn't send any subsequent request. After a few minutes CocoaHTTPServer times out the socket and closes it. This is a normal thing to do, so I should suppress the warning (in my code.)

**Comment by snej** [comment] 2015-11-16 17:20
Fixed on branch release/1.2.

**Closed by snej** 2015-11-16 17:20 UTC
Labels: bug, cannotreproduce, f: Replication, f: REST, needsmoreinfo, ready
