### ISSUE TITLE
After a while of running pull repliction starts to fail with JSON error parsing _changes feed

### ISSUE THREAD

**Issue by blairio** [couchbase/couchbase-lite-ios#1265] opened 2016-05-27 16:03 UTC
Logs:
```
2016-05-16 10:39:24.383 LatVenu Register[6850:625467] ChangeTracker: CBLSocketChangeTracker[0x68b9300 show_v352]: Started... <http://bdl.local:15984/show_v352/_changes?feed=longpoll&heartbeat=300000&style=all_docs&since=328>
2016-05-16 10:39:24.384 LatVenu Register[6850:625467] ChangeTracker: CBLSocketChangeTracker[0x68b9300 show_v352]: Event 1 on <__NSCFInputStream: 0x8b09350>
2016-05-16 10:39:24.512 LatVenu Register[6850:625467] WARNING: JSON error parsing _changes feed: parse error: client cancelled parse via callback return value
2016-05-16 10:39:24.513 LatVenu Register[6850:625467] CBLSocketChangeTracker[0x68b9300 show_v352]: Connection error #1, retrying in 2.0 sec: The operation couldn’t be completed. (CBLChangeTracker error 587.)
```
Response from: http://bdl.local:15984/show_v352/_changes?feed=longpoll&heartbeat=300000&style=all_docs&since=328

```
{"results":[
{"seq":396,"id":"0","changes":[{"rev":"4-afb8d07bbd8eb41fabaabdab305ca364"}]},
{"seq":406,"id":"timestamp","changes":[{"rev":"402-418ae778c6b856244d9a82cbcd3cc564"}]}
],
"last_seq":406}
```

If I restart the app it will pull again for a while.

--------
* Version:   release/1.2.2 SHA 97e6d5826ce56dc9fe2a316b118c86faa6adcf69
* Client OS: iPad mini (Model A1432) iOS 8.4.1 (12H321)
* Server:    Apache CouchDB 1.6.1

**Comment by snej** [comment] 2016-05-27 16:35
Weird. The warning implies that there was an item in the results that's missing an `id` or `seq` property, but that's not the case in the output you showed.

If you run a tool like HTTPScoop or Charles Proxy, you can capture the actual requests/responses and see the data that caused the parsing to fail. That will help a lot.

Alternatively, if you can build CBL yourself, you could uncomment the `Log()` call at line 99 of CBLChangeMatcher.m; this will log the parsed values from the feed.

**Comment by blairio** [comment] 2016-05-30 03:24
It appears to be triggered by a momentary blip in connectivity. This happens naturally with the WiFi in my office, but I can also trigger it by rapidly turning wifi off then on in Control Centre.

Eg. Normal operation:
```
2016-05-29 21:08:44.763 App[12884:1158328] ChangeTracker: CBLSocketChangeTracker[0x673ccf0 db352]: Started... <http://server.local:15984/db352/_changes?feed=longpoll&heartbeat=300000&style=all_docs&since=6401>
2016-05-29 21:08:44.764 App[12884:1158328] ChangeTracker: CBLSocketChangeTracker[0x673ccf0 show_v352]: Event 1 on <__NSCFInputStream: 0x6726de0>
2016-05-29 21:08:44.945 App[12884:1158328] CBL_Router: Sending longpoll response
2016-05-29 21:09:15.057 LatVenu Register[12884:1158328] Ended ChangeMatcher with seq=6402, id='timestamp', deleted=0, revs=(
    "6385-489a230af46d50f690cc3e5d1489af81"
)
2016-05-29 21:09:15.059 LatVenu Register[12884:1158328] ChangeTracker: CBLSocketChangeTracker[0x673ccf0 show_v352]: EndEncountered <__NSCFInputStream: 0x6726de0>
2016-05-29 21:09:15.063 LatVenu Register[12884:1158328] ChangeTracker: CBLSocketChangeTracker[0x673ccf0 show_v352]: Starting...
2016-05-29 21:09:15.065 LatVenu Register[12884:1158328] ChangeTracker: Changes feed using proxy settings {
    ExceptionsList =     (
        "*.local",
        "169.254/16"
    );
    FTPPassive = 1;
    "__SCOPED__" =     {
        en0 =         {
            ExceptionsList =             (
                "*.local",
                "169.254/16"
            );
            FTPPassive = 1;
        };
    };
}
2016-05-29 21:09:15.068 LatVenu Register[12884:1158328] ChangeTracker: CBLSocketChangeTracker[0x673ccf0 show_v352]: Started... <http://bdl.local:15984/show_v352/_changes?feed=longpoll&heartbeat=300000&style=all_docs&since=6402>
2016-05-29 21:09:15.069 LatVenu Register[12884:1158328] ChangeTracker: CBLSocketChangeTracker[0x673ccf0 show_v352]: Event 1 on <__NSCFInputStream: 0xdf8f00>
2016-05-29 21:09:15.180 LatVenu Register[12884:1158328] CBL_Router: Sending longpoll response
2016-05-29 21:09:15.769 [info][tid:com.facebook.react.JavaScript] action @ 21:09:15.191 atVenuRegister/connectivity/UPDATE_SHOW_TIMESTAMP 
2016-05-29 21:09:15.770 [info][tid:com.facebook.react.JavaScript] —— log end ——
2016-05-29 21:09:15.772 [info][tid:com.facebook.react.JavaScript] 'Listening for changes of', 'show_v352', ' with', { feed: 'longpoll', since: 2827 }
2016-05-29 21:09:34.453 [info][tid:com.facebook.react.JavaScript] action @ 21:09:33.870 atVenuRegister/connectivity/UPDATE_TRANSACTION_STATUS 
2016-05-29 21:09:34.454 [info][tid:com.facebook.react.JavaScript] —— log end ——
2016-05-29 21:09:35.055 [info][tid:com.facebook.react.JavaScript] action @ 21:09:34.481 atVenuRegister/connectivity/UPDATE_TRANSACTION_STATUS 
2016-05-29 21:09:35.057 [info][tid:com.facebook.react.JavaScript] —— log end ——
2016-05-29 21:09:44.961 LatVenu Register[12884:1158328] Ended ChangeMatcher with seq=6403, id='timestamp', deleted=0, revs=(
    "6386-b663844f1f7cf61b7e486121f91f0f19"
)
2016-05-29 21:09:44.962 LatVenu Register[12884:1158328] ChangeTracker: CBLSocketChangeTracker[0x673ccf0 show_v352]: EndEncountered <__NSCFInputStream: 0xdf8f00>



```

**Comment by blairio** [comment] 2016-06-01 19:13
@snej Let me know if you need even more info
Thanks!

**Comment by pasin** [comment] 2016-08-25 21:52
I'm wondering if the issue is the same issue as https://github.com/couchbase/couchbase-lite-ios/issues/1403.

**Comment by snej** [comment] 2016-09-14 22:16
Yes, pretty sure this is the same bug. @blairio, please update to 1.3 and the problem should be fixed. If it isn't, please comment here and we'll reopen the bug and investigate.

**Closed** 2016-09-14 22:17 UTC
Labels: backlog, bug, compatibility, f: Replication, needsmoreinfo
