### ISSUE TITLE
400 Bad Request after iOS app is backgrounded and then foregrounded

### ISSUE THREAD

**Issue by anne-couchbase** [couchbase/couchbase-lite-ios#2152] opened 2018-05-07 22:08 UTC
CBL iOS 1.4.1
Sync Gateway 1.4.1

"_changes?feed=websocket" request following the backgrounding and foregrounding of app results in:

2018-05-07 14:06:03.500633-0500 QoL[16947:3133346] ChangeTracker: CBLWebSocketChangeTracker[0x1c01c97e0 xxx]: Started... <https://xxx.xxx.com/xxxxxxApi/xxx/_changes?feed=websocket>
2018-05-07 14:06:03.865315-0500 xxx[16947:3133346] CBLWebSocketChangeTracker[0x1c01c97e0 xxx]: Can't connect, giving up: CBLHTTP[400, "HTTP/1.1 400 Bad Request", <https://xxx.xxx.com/xxxxxxApi/xxx/_changes?feed=websocket>]<--PSWebSocketError[2, "Handshake failed: 400 Bad Request"]

CBL makes the request "GET /xxx/_changes?feed=websocket"

tcpdump from the Sync Gateway node shows the request header lacks websocket-specific handshake request.  Sync Gateway then responds with:

HTTP/1.1 400 Bad Request
not websocket protocol

This behavior is intermittent, but also seen when the device/app is idle for some time.

**Comment by ryd0rz** [comment] 2018-05-22 20:54
I'm getting a similiar issue, but with longpolling.

**Comment by pasin** [comment] 2018-05-22 20:56
@ryd0rz Could you please provide the log with Sync, SyncVerbose, ChangeTracker, ChangeTrackerVerbose, RemoteRequest logging domain enabled?

**Comment by ryd0rz** [comment] 2018-05-22 21:00
I'm actually just using the built in REST API, and leveraging header Cookie: SyncGatewaySession=xxx

I'm using React Native with a modified version of react-native-couchbase-lite that works with latest version of sync gateway.

I don't expect you folks to support the react-native-couchbase-lite stuff, but thought the issue is related to the OP above... The only difference with mine is it's longpolling and i'm using the API.

How do I enable the Sync, SyncVerbose, ChangeTracker, ChangeTrackerVerbose, RemoteRequest logging domains... or should I just search around for how to enable those things?

**Comment by pasin** [comment] 2018-05-22 21:04
To enable logging:

```Swift
CBLManager.enableLogging("Sync")
CBLManager.enableLogging("SyncVerbose")
CBLManager.enableLogging("ChangeTracker")
CBLManager.enableLogging("ChangeTrackerVerbose")
CBLManager.enableLogging("RemoteRequest")
```

```Objective-C
[CBLManager enableLogging: @"Sync"];
[CBLManager enableLogging: @"SyncVerbose"];
[CBLManager enableLogging: @"ChangeTracker"];
[CBLManager enableLogging: @"ChangeTrackerVerbose"];
[CBLManager enableLogging: @"RemoteRequest"];
```

**Comment by pasin** [comment] 2018-05-22 21:06
If using longpoll, basically it will be a different issue. We need to look what request to SGW returned 400 error.

**Comment by ryd0rz** [comment] 2018-05-22 22:27
Hey pasin,

I've enabled logging. 

Basically it happens only after 15+ hours of inactivity.

Here's a rundown of the events that occur:

1. App logs in through server, creating a sync gateway session token.
2. Session token is used to start replication to app via REST api call on loopback to couchbase-lite-ios framework.
3. After left for 15 minutes, app automatically logs itself out.
4. Replication stops via REST api call on loopback to couchbase-lite-ios framework.
5. App goes to sleep.
6. Wait 15+ hours
7. Come back login, get a new sync gateway session token from backend.
8. Start replication again with new sync token via REST api call on loopback to couchbase-lite-ios framework.
9. _changes receives nothing. -- Nothing works until we hard kill and restart app... then it starts working again.

This also may happen randomly after logging out and logging in again, but seems to be very intermittent. However, waiting 15 hours always reproduces.

**Comment by pasin** [comment] 2018-05-23 15:04
@ryd0rz When you are able to reproduce, please share the log. I couldn't think why that was happening especially when starting a new replicator with a new session.

**Comment by pasin** [comment] 2018-08-24 05:16
@anne-couchbase I have tried to reproduce the issue but unfortunately I couldn't reproduce. The 400 Bad Request, Not WebSocket protocol is normally caused by some WebSocket required HTTP headers are missing when sending an Upgrade request. We have seen some customers reported this issue when they used a proxy/load balancer that doesn't configured to support WebSocket and causes some headers to be stripped out. 

If this issue is still a concern, could you please check your proxy/load balancer settings if using one? Otherwise, please try to capture the raw HTTP request and provide the log with Sync, SyncVerbose, ChangeTracker, ChangeTrackerVerbose, RemoteRequest logging domain enabled?

I'm closing this issue for now and once we have more info, we can reopen the issue. Thanks.

**Closed by pasin** 2018-08-24 05:16 UTC
Labels: icebox
