### ISSUE TITLE
iOS App Extension replication gets suspended "prematurely"

### ISSUE THREAD

**Issue by rajagp** [couchbase/couchbase-lite-ios#1779] opened 2017-06-09 03:07 UTC
--------
* Version:   1.4 (have not tried on 2.0 . Don't expect any difference)
* Client OS: iOS9 / swift 3 (xcode 8.3)
* Server:    Sync Gateway (either 1.4 or 1.5. Does not make difference)

Issue: Unable to perform continuous replication with App Extensions/

I have set push/pull replication in continuous mode on my iOS App Extension but it suspends presumably due to inactivity (iOS App Extension is in foreground). Since the replication suspends, changes made through the app extension are not synced up until I close the extension and reopen it (because when I reopen, replication runs again once) . 
It appears that the criteria used for suspending the replicator may have to be revisited for App Extensions because these are not like regular apps (they run in a separate process space and are hosted by a host app).

See attached traces

Reproducing Issue: 

- Sample App : https://github.com/couchbaselabs/couchbase-mobile-ios-app-extension 
- Switch to branch "syncsupport" (Note: I have verbose logging on )
-  Launch sync gateway with the sample sync config file

-  Run the CBLiteAppExtension target from Xcode
-  Add CB Task App Extension to the Today widget as shown in https://blog.couchbase.com/wp-content/uploads/2017/05/addtodaywidget.gif
-  Add couple of tasks , tap to check them as complete/ incomplete. https://blog.couchbase.com/wp-content/uploads/2017/05/addtask.gif

- Now, stop the debugger and relaunch the "CBLiteTaskExtension" target. 
- You will observe from console logs that replicator is suspended. Update the "completed" status of task by tapping on it and naturally the change is not replicated.

[cbextensionsynclog.txt](https://github.com/couchbase/couchbase-lite-ios/files/1062933/cbextensionsynclog.txt)

**Comment by rajagp** [comment] 2017-06-14 01:28
Duplicated to https://github.com/couchbaselabs/couchbase-lite-apiv2/issues/108

**Comment by pasin** [comment] 2017-09-21 22:53
I have tested the sample app above and I could see the replicator was suspended when the containing app (not extension itself) was brought to the background. However I don't think we should assume that the replicator on the containing app will always run because the app extension can work without the containing app running.

@rajagp Can the extension especially today extension itself start the replicator?

**Comment by pasin** [comment] 2017-09-21 22:55
Also even though we allows the replicator to be run in the background inside the containing app, there is still a limitation about how long the containing app can be run until it gets suspended from the OS (unless the app is  like VOIP, location based, and so on).

**Comment by rajagp** [comment] 2017-09-22 17:04
The extension does in fact initialize replication. It has to do that because it needs to run independent of the container app.  You can look at the `TopTaskTableViewController` file `initialize()` method in the sample. So the issue is that the replicator seems to get suspended . (You can look at the `addReplicationChangeObserver()` method in `DatabaseManager.swift` to track the status change.

**Comment by pasin** [comment] 2017-09-22 18:32
I could see TopTaskTableViewController initializing the replicator. Currently I'm not seeing the issue that the replicator got suspended (could be because the recent fix in [MYBackgroundMonitor](https://github.com/snej/MYUtilities/pull/16), or I didn't test it correctly. In general, the suspend process is not enabled for the App Extension.

**Comment by pasin** [comment] 2017-09-22 22:21
I believe the issue is fixed by https://github.com/snej/MYUtilities/pull/16. I don't see the issue when I tested the app extension that @rajagp wrote. I'm closing the issue now. @rajagp if you are still seeing the issue, we can reopen.

**Closed by pasin** 2017-09-22 22:21 UTC
Labels: P2: medium, ready

**Comment by rajagp** [comment] 2017-10-10 21:04
@pasin   Seems to be working with the 1.4.1 build . I look forward to official version so I can blog about it :-)
