### ISSUE TITLE
Continous replication sockets are being closed by Cloudant, in Couchbase 1.3.1 this stops replication

### ISSUE THREAD

**Issue by jordanpwood** [couchbase/couchbase-lite-ios#1513] opened 2016-11-17 20:33 UTC
We recently changed our Cloudant server to their CouchDB 2.0 compliant version.  Soon after we did that, we noticed that our Couchbase Lite (version 1.2.1) connections were being closed, producing errors like the following:

```11:53:04.147‖ Sync: CBLRestPuller[https://couchClient:*****@browzine.cloudant.com:443/user-78961360-a3dd-11e6-98fc-f1733aeecc7a] Progress: set active = 1
11:53:04.148‖ Sync: CBLRestPuller[https://couchClient:*****@browzine.cloudant.com:443/user-78961360-a3dd-11e6-98fc-f1733aeecc7a] Progress: 1540 / 1540
11:53:04.148‖ Sync: CBLRestPuller[https://couchClient:*****@browzine.cloudant.com:443/user-78961360-a3dd-11e6-98fc-f1733aeecc7a] Progress: set active = 0
11:53:04.148‖ Sync: CBLReplication[from https://couchClient:*****@browzine.cloudant.com:443/user-78961360-a3dd-11e6-98fc-f1733aeecc7a]: idle, progress = 1540 / 1540, err: (null)
11:53:04.148‖ WARNING: Truncated changes feed
11:53:04.148‖ WARNING: CBLSocketChangeTracker[0x79770500 user-78961360-a3dd-11e6-98fc-f1733aeecc7a]: Longpoll connection closed (by proxy?) after 0.2 sec
11:53:04.149‖ CBLSocketChangeTracker[0x79770500 user-78961360-a3dd-11e6-98fc-f1733aeecc7a]: Connection error #1, retrying in 2.0 sec: The operation couldn’t be completed. (NSURLErrorDomain error -1005.)
```

While this is disturbing and causing lots of extraneous sockets to be created, the replications were still eventually completing.  However, when I tried upgrading to Couchbase Lite 1.3.1, I got the following errors:

```
09:27:30.292‖ CBLSocketChangeTracker[0x7f983c851320 user-ba87dac0-93d9-11e5-8034-13ab30f4e1cb]: Connection error #1, retrying in 2.0 sec: CBLHTTP[500, "internal server error", <https://couchClient:*****@browzine.cloudant.com:443/user-ba87dac0-93d9-11e5-8034-13ab30f4e1cb/_changes?feed=normal&heartbeat=300000&style=all_docs&active_only=true&filter=replicationFilters/get_everything_but_deleted>]
09:27:30.333‖ CBLSocketChangeTracker[0x7f983cb96a90 user-ba87dac0-93d9-11e5-8034-13ab30f4e1cb]: Connection error #1, retrying in 2.0 sec: CBLHTTP[500, "internal server error", <https://couchClient:*****@browzine.cloudant.com:443/user-ba87dac0-93d9-11e5-8034-13ab30f4e1cb/_changes?feed=normal&heartbeat=300000&style=all_docs&active_only=true&filter=replicationFilters/get_bookshelf>]
```

With this version, replication stopped and the data did not get transferred.  I have a trouble ticket open with Cloudant, I'll post any relevant comments they have about this here.  The fact that the newer version of Couchbase is completely unable to get data from Cloudant is worrisome, especially since I had hoped to upgrade to it soon.  Let me know if there is any information I can pass on to Cloudant to get this resolved.  

Also let me know if you need a database that you have permission to replicate with, I can get one set up.

--------
* Version:   1.2.1 and 1.3.1
* Client OS:   iOS 9 and 10
* Server:    Cloudant (DBCore build 5638)

**Comment by pasin** [comment] 2016-11-17 22:15
This seems to be related to https://github.com/couchbase/couchbase-lite-java-core/issues/1516.

**Comment by jordanpwood** [comment] 2016-11-18 14:38
Cloudant Support asks me the following:

> Could you confirm if the http requests of changes feed you have problem like below?

>https://browzine.cloudant.com/user-db/_changes?timeout=25000&include_docs=true&feed=longpoll&heartbeat=10000&since=22707-g1AAAAOreJzLYWBg4MhgTmFQSUlKzi9KdUhJMtQrycgsSsksys8zMDDUS87JL01JzCvRy0styQGqZkpkSJL___9_VgZzEgMDl3QuUIzdMDnZ0tTAkEhjUO0zImBfkgKQTLKHW8nDALbS0sgo0dDciEiTSLTSAWRlPNxK7ulgK00NLSwMjdPIstKYkJUJICvrEQGrBbbSKDHZ2MDQhEiTSPNlHguQZGgAUkBb50Os5ZwD8alBimGquTFNAhdi7QKItfuhcZoEiVMLs7TENFpaewBi7X2otVPA1qaYJplamJAXr8RZ-wBiLSxuXcHWJqUaGFgYEmttFgDexij6&limit=25&_nonce=1479445403612

I can't find anywhere that couchbase spits out the full `_changes` URL, the only thing I could find is:

>08:29:52.637‖ SyncVerbose: CBLSocketChangeTracker[0x7f0b25e0 user-db]: POST //<username redacted>:<password redacted>@browzine.cloudant.com:443/user-db/_changes

Can you tell me some more specifics about what the `_changes` feed looks like, so I can pass that on to Cloudant?

Thanks!

Jordan

**Comment by pasin** [comment] 2016-11-18 16:57
It seems like Cloudant does support POST changes feed request. We did have the [code](https://github.com/couchbase/couchbase-lite-ios/blob/master/Source/ChangeTracker/CBLSocketChangeTracker.m#L294-L306) to handle cloundant POST changes feed error, but it seems like after Cloudant upgraded to use CouchDB 2.0, Cloudant doesn't send the same error codes anymore.

**Comment by pasin** [comment] 2016-11-18 17:00
To support this, we might need to have an option to disable POST changes feed request from the replicator's custom settings. @jordanpwood Can you try to modify https://github.com/couchbase/couchbase-lite-ios/blob/master/Source/ChangeTracker/CBLSocketChangeTracker.m to always disable `_usePOST` and see if that helps?

**Comment by jordanpwood** [comment] 2016-11-18 17:15
This [line](https://github.com/couchbase/couchbase-lite-ios/blob/master/Source/ChangeTracker/CBLSocketChangeTracker.m#L315) is definitely not true in my situation.

**Comment by pasin** [comment] 2016-11-18 17:38
I will talk to the team about adding a custom config to the replicator but that could take some time. Meanwhile, can you modify the code yourself to always disable POST?

**Comment by jordanpwood** [comment] 2016-11-18 17:54
That did the trick, I no longer have my changes feed being closed.

**Comment by jordanpwood** [comment] 2016-11-18 18:13
Such an option would be added to the Android version of Couchbase Lite as well, correct?  We use both platforms.

**Comment by jordanpwood** [comment] 2016-11-18 20:15
We just looked at our Android app, and from what we can tell couchbase on Android doesn't use POST, so I guess that's a moot question!

**Comment by snej** [comment] 2016-11-19 00:33
You can use a tool like HTTPScoop or Charles Proxy to view the HTTP traffic.

I'm assuming this is a Cloudant bug unless we hear otherwise.

We also need clear and definitive documentation on how CouchDB / Cloudant handle POST to `_changes`. The CouchDB docs don't describe it in enough detail for us to support it properly, and I have no idea how much Cloudant differs from CouchDB 2.0. (And if it does differ, we can't tell how to tell it apart, since the user agent strings seem to be the same.)

**Comment by jordanpwood** [comment] 2016-11-19 20:24
Cloudant's _changes documentation is here: https://docs.cloudant.com/database.html#get-changes

This documentation describes how to do a GET request with the following section at the end:

> Using POST to get changes
> 
> Instead of GET, you can also use POST to query the changes feed. The only difference to the GET method is that parameters are specified in a JSON object in the request body.
>
> Example of POSTing to the _changes endpoint
> POST /$DB/_changes HTTP/1.1
> Host: $USERNAME.cloudant.com
> Content-Type: application/json
> {
>   "limit": 10
> }

Is this documentation sufficient?

Jordan

**Comment by jordanpwood** [comment] 2016-11-20 02:54
Someone at Cloudant tells me:

>We have found that we had authorization problems with POST requests to _changes, and we already have a fix for this issue. Will you be able to wait for a new release which will be rolled by our engineers next week?

I'll let you know if this fixes the issue!

**Comment by jordanpwood** [comment] 2016-11-20 03:04
My only Couchbase-related question at this point is why was version 1.2.1 able to muddle though and actually get data, while version 1.3.1 returned a 500 and bailed?  Was there some regression in the error handling, or was I just very, very lucky?

**Comment by pasin** [comment] 2016-11-21 21:56
From your 1st post, with 1.3.1, Cloudant returns 500 error, while 1.2.1 returns something different.

I would guessed, it could be because of the following change to fix CouchDB compatibility:
https://github.com/couchbase/couchbase-lite-ios/blob/master/Source/ChangeTracker/CBLChangeTracker.m#L100-L103

As Cloudant is releasing a fix for POST _changes requests, I will close the ticket. Please let us know if you have any other updates.

**Comment by jordanpwood** [comment] 2016-11-30 23:10
@pasin, @snej, I've gotten a reply from Cloudant about this issue:

>Sorry for the delay - it appears that our documentation was misleading. The documentation used to state:
>
>"Instead of GET, you can also use POST to query the changes feed. The only difference to the GET method is that parameters are specified in a JSON object in the request body."
>
>However the behavior is inconsistent with that description. The difference if you are using POST instead of GET is that if you are using either of the 'docs_ids' or 'selector' filters, it is possible to include the "doc_ids" : [...] or "selector": {...} parts in the request body. All other parameters are expected to be in the query string, the same as using GET.
>
>https://docs.cloudant.com/database.html#post
>
>Apologies for the confusion caused here. We recommend providing the parameters in the query string instead of the request body.

Is this an option for Couchbase?  If not, would you consider adding a config parameter to the replicator to disable POSTs to `_changes`?

**Comment by jordanpwood** [comment] 2016-12-08 16:16
@pasin , @snej , any news on this issue?  Could you let me know whether you plan on fixing the POST request that's sent to Cloudant, or will you provide a config parameter to turn off POST replication?

Thanks!

Jordan

**Comment by pasin** [comment] 2016-12-12 17:23
@jordanpwood, from the quote you have mentioned above, CBL-iOS already worked that way to support CouchDB POST changes feeds,

https://github.com/couchbase/couchbase-lite-ios/blob/master/Source/ChangeTracker/CBLChangeTracker.m#L168-L177

I understand that the issue is that Cloudant updated the Server name from CouchDB/1.0.2 to something else. We have put a workaround to support Cloudant POST changes feed error in the past: https://github.com/couchbase/couchbase-lite-ios/blob/master/Source/ChangeTracker/CBLSocketChangeTracker.m#L312-L319 

Can you check with Cloudant support or use a proxy (e.g. HTTPScoop or Charles Proxy) to check the Server properties in the response header? I might be able to update the code to support a new Server value.

> Could you let me know whether you plan on fixing the POST request that's sent to Cloudant, or will you provide a config parameter to turn off POST replication?

From the recent meeting, we do not have a plan to add a parameter to turn off POST changes feed request.

**Comment by snej** [comment] 2016-12-12 17:47
@pasin Actually our implementation doesn't 100% agree with the latest word from Cloudant. CBL will send any filter parameters in the POST body, while Cloudant explicitly only expects filter params named `"doc_ids"` or `"selector"`. (I can't think of any good reason to hardcode these; I think someone was fixing a CouchDB bug where the list of doc IDs overflowed the URL, and just did the most literal-minded fix possible instead of thinking ahead to other potential filters.)

**Comment by jordanpwood** [comment] 2016-12-12 23:30
>Can you check with Cloudant support or use a proxy (e.g. HTTPScoop or Charles Proxy) to check the Server properties in the response header? I might be able to update the code to support a new Server value.

Here's what Charles tells me the headers are:

HTTP/1.1 200 OK
Cache-Control: must-revalidate
Content-Type: application/json
Date: Mon, 12 Dec 2016 23:23:17 GMT
ETag: "330732Q2F27E86MF5DCP1R408"
Server: CouchDB/2.0.0 (Erlang OTP/17)
X-Couch-Request-ID: fbae715695
X-CouchDB-Body-Time: 0
X-Content-Type-Options: nosniff
X-Cloudant-Backend: thirdiron001
Via: 1.1 lb1.thirdiron001 (Glum/1.31.3)
Strict-Transport-Security: max-age=31536000
Transfer-Encoding: chunked
Connection: Close

**Comment by pasin** [comment] 2016-12-13 22:16
I have tried to reproduce this with Cloudant today but I have seen a different behavior. What I have seen is that using filter with POST _changes request doesn't work at all - basically no documents synced as well as  no errors. However the filter works fine with GET _changes requests. So I guessed, Cloudant might have fixed something that leads to this behavior. You may need to verify this.

If that is the case, the only option now is to disable POST _changes feed request by changing this [line](https://github.com/couchbase/couchbase-lite-ios/blob/master/Source/ChangeTracker/CBLChangeTracker.m#L85) to NO. As we do not have plan to have an option to disable POST changes feed request in the near future, you will need to modify and build the code your self. If the plan is changed, I will post an update here.

**Comment by willholley** [comment] 2016-12-22 10:52
Cloudant now matches CouchDB (1.x and 2.x) behaviour - in previous versions we didn't support `POST` to `_changes` at all. The request body is used for `doc_ids` and `selector` parameters only - the rest need to be specified as query parameters in the URL.

**Comment by pasin** [comment] 2016-12-28 18:56
@willholley Thanks for the update. I just ran a replication with docIds test (on master d2fe5fd036b598eb25e2eb064bdef921dd354ad1) to pull 10K docs against CouchDB 2.0.0. The pull replication worked just fine with either longpoll or WebSocket mode. I'm closing the ticket now.

**Closed by pasin** 2016-12-28 18:56 UTC
Labels: icebox

**Comment by pasin** [comment] 2016-12-28 18:58
@jordanpwood please try again with CBL either 1.3.1 or current master against the latest update from Cloundant. Thanks!

**Comment by jordanpwood** [comment] 2017-08-27 14:08
This problem never did get fixed.  I am currently running a version of Couchbase 1.4.0 that I tweaked to set `usePOST` to `NO`.  It would be very helpful if this was a parameter I could set somewhere.
