### ISSUE TITLE
2.0 Runtime Error due to library not loading when in mac OS CLI App

### ISSUE THREAD

**Issue by skela** [couchbase/couchbase-lite-ios#2030] opened 2018-01-18 17:10 UTC
This might very well be a setup issue, but I've not been able to work around it, and I wasn't able to find an example of a project where you use the latest 2.0 SDK in a Mac OS project.

	dyld: Library not loaded: @rpath/libswiftCore.dylib
	  Referenced from: /Users/skela/Library/Developer/Xcode/DerivedData/cli-aqhfpyrkoxerqbgqvsjbqddkfnbk/Build/Products/Debug/CouchbaseLiteSwift.framework/Versions/A/CouchbaseLiteSwift
	  Reason: image not found
	Program ended with exit code: 9

I've followed steps found here: https://developer.couchbase.com/documentation/mobile/current/installation/ios/index.html without any luck.

* CouchbaseLiteSwift.framework added in Linked Frameworks and Libraries
* "@loader_path/../Frameworks/." added to Runpath Search Paths in Linking of Build Settings
* Added Copy Files Phase with a Destination of Frameworks, tried with and without Code sign On Copy enabled.

Not having any luck here, anything obviously wrong?

**Comment by snej** [comment] 2018-01-18 18:04
Weird; that sounds like a Swift runtime library. Are you sure the version of Swift you're building with matches the one CBL was built with? (Swift doesn't have ABI stability yet, so unfortunately all code has to be compiled with the same version of Swift.)

Also compare your project against one of our 2.0 iOS demo projects and see if any of the build settings don't match.

**Comment by skela** [comment] 2018-01-18 18:14
I've been looking at several iOS ones, not had any luck, that's why I wanted to ask. Are you able to get it working with a brand new mac os project ?

I've attached mine here:

[cb_macos.zip](https://github.com/couchbase/couchbase-lite-ios/files/1643971/cb_macos.zip)

**Comment by snej** [comment] 2018-01-18 18:18
@rajagp, any ideas? I think you've got the most experience of us with building actual CBL 2 apps :)

**Comment by rajagp** [comment] 2018-01-18 18:29
Interesting. Haven't seen that one with our framework. With other frameworks, I've had to set the "always Embed swift framework" build settings to true and that typically would fix it. Let me take a look at the sample project...

**Comment by pasin** [comment] 2018-01-18 18:39
This seems to be an issue with the command line app not the Mac UI App.

**Comment by pasin** [comment] 2018-01-18 19:32
Here is some info from one of the Carthage issue: https://github.com/Carthage/Carthage/issues/2107.

**Comment by rajagp** [comment] 2018-01-18 20:37
@skela  I was able to link the sample app with CBL that I built from source (not via carthage) and it works fine.

**Comment by skela** [comment] 2018-01-18 20:40
Ok, what's the approach to do that? Do I still get to import the usual way in my code, i.e. "import CouchbaseLiteSwift" etc ? I don't mind doing that stuff if I have to via for example a git submodule, just need to know how :+1:

**Comment by rajagp** [comment] 2018-01-18 20:41
You mean building from source or using prebuilt binary?

**Comment by skela** [comment] 2018-01-18 21:17
Oh sorry I misread that. So what yer saying is, you were able to build the framework manually, and then include that , and it works without issue?

**Comment by skela** [comment] 2018-01-18 21:20
Ok, I will try that, and I'll rename this issue to reflect that it is an issue with your support for mac OS command line apps via Carthage :)

**Comment by skela** [comment] 2018-01-18 21:26
Hmm, sorry, tried it with the binary downloaded from your website, still same error, was there anything else you did, or did you try with a binary built from more recent code than whats in build 21?

**Comment by rajagp** [comment] 2018-01-18 21:32
Argh...I think I spoke too soon. I thought it ran fine with built version but it isn't ...will probe further

**Comment by pasin** [comment] 2018-01-19 02:02
I believe this is a limitation of using Swift Framework in Mac Command Line app. 

@skela @rajagp Beside CBL Swift Framework, do the other Swift frameworks work with Mac Command Line app?

**Comment by rajagp** [comment] 2018-01-19 03:26
> I believe this is a limitation of using Swift Framework in Mac Command Line app.

That is correct. I can use the swift Framework within my regular Mac App which has an app bundle structure that would allow you to embed the swift runtime into the app bundle. Cant do that with CLI 

> Beside CBL Swift Framework, do the other Swift frameworks work with Mac Command Line app?
I don't think I have ever linked a swift framework with a CLI App..

My recommendation to @skela would be to use the ObjC version of CouchbaseLite library- it has feature parity w/  swift version anyways.  ... @pasin  - what do you think ?

**Comment by pasin** [comment] 2018-01-19 03:39
Both CBL Swift and Objective-C framework have the same feature. Beside that currently the CBL swift framework is wrapping on top of the Objective-C framework.

**Comment by pasin** [comment] 2018-01-19 03:41
As it turns out the issue is a limitation of using Swift frameworks in the CLI App, I'm closing the issue now.

**Closed by pasin** 2018-01-19 03:41 UTC

**Comment by skela** [comment] 2018-01-19 07:17
But if I did use the objective-c framework, since you use different names for them, i.e. CouchbaseLite.framework and CouchbaseLiteSwift.framework, I would have to have different imports in my command line interface compared to the iOS app. This is still an issue, but this might be helpful:
http://colemancda.github.io/2015/02/12/embedded-swift-frameworks-osx-command-line-tools

**Comment by pasin** [comment] 2018-01-19 07:24
Thanks for sharing the article.

**Comment by rajagp** [comment] 2018-01-19 14:06
> This is still an issue, but this might be helpful:

@skela  This is not an issue with the CBL framework. If you are looking to use the same model layer implementation across your CLI macOS app and  your iOS app, then one option is to use the ObjC version of CBL in both. 
If you want to use the swift version in both,  you could try to follow the steps in the article to create the ObjC command line tool and create a bundle that you can embed your swift RT. Would be curious if you tried this out.

**Comment by skela** [comment] 2018-01-19 14:27
Trying to avoid objc as much as possible though. Anyway, no worries, perhaps I can look at Swift Package manager and take that route instead for the mac os command line.

**Comment by rajagp** [comment] 2018-01-19 14:36
Cool!  If you get the chance, it may be worthwhile sharing your experience . Would be useful for anyone else considering that option.

**Comment by skela** [comment] 2018-01-19 14:47
I will :+1:

**Comment by mahurtado** [comment] 2018-05-30 17:52
Hello @skela . Not sure if this is still open issue for you. I face same error and solved by adding CouchbaseLiteSwift.framework to the Embedded Binary on the target:

![image](https://user-images.githubusercontent.com/14200354/40738128-fe25c058-6442-11e8-97b0-4edb8efe1d20.png)

**Comment by snej** [comment] 2018-06-08 20:40
@mahurtado How did you get an Embedded Binaries section of your target? I'm looking at the General settings tab of a Mac CLI target (in Xcode 9.4), and it doesn't have one — only Identity, Signing, Deployment Info, and Linked Frameworks And Libraries.

**Comment by mahurtado** [comment] 2018-06-10 20:14
@snej , In my case, with sample project "Todo".
In the  "Project Navigator" select your project root folder, then in the main view, select "Target" > "Todo",  then scroll down until "Embedded Binaries" section

**Comment by snej** [comment] 2018-06-10 21:56
@mahurtado But this issue is about command-line binary targets, not applications.

**Comment by Fenil15** [comment] 2018-07-25 08:42
@mahurtado Thanks got it working after adding it in Embedded Binaries

**Comment by skela** [comment] 2018-10-11 18:09
Got nowhere when trying to use Swift Package Manager for your library, I'm guessing you need to add support for that by adding a Manifest. Anyway, to answer @pasin 's previous question : 
"I believe this is a limitation of using Swift Framework in Mac Command Line app.@skela @rajagp Beside CBL Swift Framework, do the other Swift frameworks work with Mac Command Line app?"

Yes, for instance CryptoKit - https://github.com/chrisamanse/CryptoKit
I've also made a library for a work project I did that works fine in CLI. Very easy to do, especially if you use Swift Package manager. So the question could potentially change to, would you be so kind as to add support for Swift Package manager for your library? Its a lot easier to work with, and cleaner than both Carthage and Cocoapods.

**Comment by pasin** [comment] 2018-10-11 18:12
@skela Can you share what you have done to make it work with command line app? also, if you have made the project work with Swift Package Manager, please share too.

**Comment by pasin** [comment] 2018-10-11 18:15
I think the current project structure is not what the default structure for Swift Package Manager. Not sure if they allow to have custom structure or not.

**Comment by skela** [comment] 2018-10-11 18:17
@pasin sorry if i wasn't clear enough, my bad. I'm saying I have not been able to use couchbase lite in a pure mac os cli app yet, but was just bringing up cryptokit and the fact that ive also made a library/framework (thats private) that works with swift pm.

And yeah, thats true that yer structure is a bit different, but it might be possible still with some code-fu somehow.

Making it work with yer swift code is probably not that hard, but you do require couchbase core, which might make it a bit more complicated (as thats cpp isnt it).

Although as far as I understand it is probably possible still to do it.

**Comment by pasin** [comment] 2018-10-11 19:53
I have created https://github.com/couchbase/couchbase-lite-ios/issues/2214.
