### ISSUE TITLE
Replicator stays offline when switching from disabled LTE to wifi

### ISSUE THREAD

**Issue by sridevi-15** [couchbase/couchbase-lite-ios#2121] opened 2018-03-26 23:06 UTC
### Environment
* Version:   ios - 755
* Server:   sg- 823

### Steps to reproduce : 
1. Login to todo app on ios device
2. Create task list and docs.
3. update docs
4. Switch network from wifi to disabled LTE.
5. open todo app and update docs again
6. Switch network from disabled LTE to wifi. 

### Result : 
Replicator stays offline and does not sync with sg.

### cbl logs : 
https://gist.github.com/sridevi-15/b52e3084a87a76df2f6b6d7371d68883

**Comment by pasin** [comment] 2018-03-26 23:37
From the log, the issue happened as the following scenarios:

1. Switched from WiFi to Not Working (No data plan enabled) LTE.
2. The replicator got operation timeout error (transient error) 
     -> Reachability started and Reachability thinks it may be online.
     -> Retry logic triggered
3. While the replicator was in the retry loop, switched to WiFi again,
     -> No changes in Reachability status
4. Replicator got NSPOSIXError 64 (Host is down error) from the previous retry.
    -> Replicator is offline as network error (not transient error) and keep waiting for reachability change.

**Comment by pasin** [comment] 2018-03-27 21:57
A few things that I found from testing this issue:

1. When create and start a new Reachability, the change status call back to the Replicator will not be called.
2. I was confused with the replicator status which shows 'Reachable' when I don't have the SG running. I was wrong on this as the Reachability i setup with host level not socket level.
3. The issue is only reproduced with SG setup on a VM machine.

**Comment by pasin** [comment] 2018-03-27 23:24
After several rounds of testing with the right setup to reproduce the issue, here is the cause of the issue.
1. Reachability reported as reachable regardless of using the not-working-LTE (40003, WR -t-----) or valid WiFi (20002, -R ------d).
2. The issue happened when switching from not-working-LTE to WiFi and instead of being able to connect, the WebSocket got POSIXError, 64, "Host is down" error. This required a few rounds of testing to get into this state.
3. As POSIXError, 64 is a network error (not transient error), the current replicator code will do the retry after getting change status of the Reachability but that is not going to happen because Reachability already notified with as Reachable, 20002.

**Solution:**
Option 1. Always retry when getting transient errors or network errors. This is what we do in 1.x.
Option 2. When getting a network error, restart the reachability (Need to fix the reachability to also notify the first status as currently it doesn't)

**Comment by snej** [comment] 2018-03-28 00:05
A continuous replication should always keep retrying as long as the server might be reachable.

**Comment by pasin** [comment] 2018-03-28 04:27
This will be fixed in the RC2 build (TBD).

**Closed** 2018-03-28 15:51 UTC
Labels: P1: high, ready
