### ISSUE TITLE
Inconsistent managed objects contexts with CBLIS

### ISSUE THREAD

**Issue by mastohhh** [couchbase/couchbase-lite-ios#1075] opened 2016-01-28 15:16 UTC
When we reproduce #1061 we are in a state where on a device we have a `team.players` with 3 players and the other side `team.players` with 10 players.

We just pushed a new commit on #1060 that creates a player when we select a team's cell.

So when you create a player in the team where there is less players, the other device now duplicates the team. One team with a `permanentID` and the other always stays with a `temporaryID`, even if we `save` contexts.

This is a NSManagedObjectContext problem because when we relaunch apps, everything come back to normal.

If contexts are not representative of the `CBLDocument`s (in this example both sides are wrong), could this corrupt data ? Until the app restarts (or crash) contexts never gets back to normal, what about documents ?

**Comment by pasin** [comment] 2016-01-28 18:08
Regarding to the permatentID and temporaryID, with multiple context configuration, I would recommended to always get the permatentID when creating a new entity object so that the IDs of the objects in all contexts and CBL document are the same.

**Comment by zgramana** [comment] 2016-01-29 00:46
@mastohhh we'll add a note in our docs portal and we'll keep this open so that you can track when that becomes available.

**Comment by mastohhh** [comment] 2016-01-29 10:07
@pasin about permanentID and temporaryID, it's just the state of the objects after reproducing this bug. We didn't do anything about that. We just create objects with classic methods.

This issue tries to show that, when we get a inconsistent context (like reproducing #1061), the fact of using if (insert update delete) causes problems on every other devices that are currently in sync. And every contexts of every devices gets inconsistent too.

**Comment by pasin** [comment] 2016-03-04 03:01
@mastohhh This is the same issue I have found while working on #1061. I believe the issue will be fixed by always obtaining permanent IDs after creating new NSManagedObjects by calling NSManagedObjectContexts's `obtainPermanentIDsForObjects:error:` method. 

The issue is that `NSManagedObject `objects created on a main context will be assigned with temporary IDs. Later when those objects are saved on the root context, they will be assigned with new permanent IDs. The issue is that the `NSManagedObject` objects created on the main context will never get refreshed with the new permanent IDs and this is CoreData behavior.

CBLIS, on the other hand, knows the `NSManagedObject` objects by their permanent IDs. When new changes get replicated, CBLIS refreshes the changed NSManagedObject objects referenced by the permanent IDs on all contexts. As the main context doesn't know that the `NSManagedObject objects created` on it already have the new IDs (permanent IDs), it then thinks that those objects that are being refreshed are the new objects and shows them as duplicated.

**Comment by zgramana** [comment] 2016-03-05 00:14
We need to add this to the docs in the dev portal.

**Comment by pasin** [comment] 2019-03-15 19:55
Close as no activities.

**Closed by pasin** 2019-03-15 19:55 UTC
Labels: bug, f: Core-data, icebox
