### ISSUE TITLE
"Invalid revpos" warnings and attachment errors during pull replication

### ISSUE THREAD

**Issue by arjunblue** [couchbase/couchbase-lite-ios#986] opened 2015-11-25 13:04 UTC
Syncing stops in iOS after getting following error.I am using cblite 1.1.1 . with ENTERPRISE EDITION VERSION for syncgateway 1.1 and couchbase server 4.0.0
This error was not coming in previous version of cbl  i.e. 1.0.4.

Replication: CBL_Puller[https://9187911089792:*****@prod.rajdemo.com:9443/ph] took 28.566 sec; error=Error Domain=CBLHTTP Code=400 "400 Invalid attachment" UserInfo=0x18899e10 {NSLocalizedFailureReason=Invalid attachment, NSLocalizedDescription=400 Invalid attachment}

Sync: CBL_Puller[https://**********:*****@domian/db] Progress: set error = 400 Invalid attachment
​
Due to this error pull replication stops completely.

This is same issue as https://github.com/couchbase/couchbase-lite-ios/issues/961

- we cannot downgrade cbl as its not compatible with swift2.0
- the Fix on the release/1.2 branch  as stated in above thread is also giving error in swift files.

This is a big showstopper for us. Any help will be very appreciated as we have no alternative left.

**Comment by snej** [comment] 2015-11-26 21:01
This issue has been fixed, as you saw. If there's a problem with Swift compatibility that's preventing you from using the 2.0 branch, then we should address that. Please provide details on exactly what errors you're getting.

**Comment by arjunblue** [comment] 2015-11-27 09:17
Hi,

Thanks for quick response, we are getting "Ambiguous use of subscript" in several places

Thanks in advance

**Comment by snej** [comment] 2015-11-27 17:48
I'll need more detail than that. Please paste in the actual error messages from the build log, with a few lines of source for context. Thanks.

**Comment by arjunblue** [comment] 2015-11-30 14:23
I applied the patch and have fixed all swift errors, the syncing started but again i got same error while syncing after sometime.

this is document id    -qfwrlzartlDc9rWvssrQ5o

i see this in log  "2015-11-30 19:09:42.779 arjun[11868:2937114] WARNING: Attachment '-qfwrlzartlDc9rWvssrQ5o.jpg' in {-qfwrlzartlDc9rWvssrQ5o #2-f877d4d8cead27a75ffe191ba98cf25d} has invalid revpos=3" before i get "400 Invalid attachment"

if i look in document it has rev pos 4

- what is rev pos as even when i add new attachment (1st time) i am getting revpos 3 or 4 but never 1.

document :

(
    [Yes] => image
    [_attachments] => Array
        (
            [-qfwrlzartlDc9rWvssrQ5o.jpg] => Array
                (
                    [content_type] => image/jpeg
                    [digest] => sha1-KcVKoj5OC/u98SssyOIxNdeLskU=
                    [length] => 88602
                    [revpos] => 4
                    [stub] => 1
                )

        )

    [_sync] => ArrayArray
(
    [Yes] => image
    [_attachments] => Array
        (
            [-qfwrlzartlDc9rWvssrQ5o.jpg] => Array
                (
                    [content_type] => image/jpeg
                    [digest] => sha1-KcVKoj5OC/u98SssyOIxNdeLskU=
                    [length] => 88602
                    [revpos] => 4
                    [stub] => 1
                )

        )

    [_sync] => Array
        (
            [rev] => 5-817b3adc5520a5bd1126f24d3fd46597
            [flags] => 24
            [sequence] => 485507
            [recent_sequences] => Array
                (
                    [0] => 471266
                    [1] => 471276
                    [2] => 471277
                    [3] => 471278
                    [4] => 471280
                    [5] => 471284
                    [6] => 484908
                    [7] => 485461
                    [8] => 485507
                )

            [history] => Array
                (
                    [revs] => Array
                        (
                            [0] => 4-d31c06b12936ab3b841d241a83c20c9b
                            [1] => 2-f877d4d8cead27a75ffe191ba98cf25d
                            [2] => 5-817b3adc5520a5bd1126f24d3fd46597
                            [3] => 1-c9c077f105e4341aa78146a0b22a4da7
                            [4] => 2-1710d4966a42e099dfa72086a7933771
                            [5] => 3-2e1d8460157559354c898f4a65040116
                        )

                    [parents] => Array
                        (
                            [0] => 5
                            [1] => 3
                            [2] => 0
                            [3] => -1
                            [4] => 3
                            [5] => 4
                        )

                    [bodies] => Array
                        (
                            [0] => 
                            [1] => {"Yes":"image","_attachments":{"-qfwrlzartlDc9rWvssrQ5o.jpg":{"content_type":"image/jpeg","digest":"sha1-KcVKoj5OC/u98SssyOIxNdeLskU=","length":88602,"revpos":3,"stub":true}},"authmx":"917042150850","backgroundcolor":"227,38,54","displayname":"Arjun","dx":["ae133155-feb3-46a2-bd49-70d5edd827dd","57679539-5d1a-4785-96b0-dfe508997083","-uvWRENr8jleZgjRYbYu4UL","de8e1341-6c97-455f-ab1e-443cb194b3a1","261dcb57-e9c5-4265-bf68-1490dfed5e1e","eb54c201-289e-41f0-890d-b2defaa0ce03","-4a7yr8KofhR33NTbHEhRi3"],"epochtime":"1448017481","eptime":"1448017481","firstname":"Arjun","mx":["919999883850","919999883850","919999883850"],"org":{"org_name":"arjun"},"owner":"917042150850","phone":[{"Mobile":"+919999883850"},{"Home":"+919849278819"}],"type":"cx"}
                            [2] => 
                            [3] => 
                            [4] => 
                            [5] => 
                        )

                    [channels] => Array
                        (
                            [0] => Array
                                (
                                    [0] => ch--4a7yr8KofhR33NTbHEhRi3
                                    [1] => ch--uvWRENr8jleZgjRYbYu4UL
                                    [2] => ch-261dcb57-e9c5-4265-bf68-1490dfed5e1e
                                    [3] => ch-57679539-5d1a-4785-96b0-dfe508997083
                                    [4] => ch-917042150850
                                    [5] => ch-ae133155-feb3-46a2-bd49-70d5edd827dd
                                    [6] => ch-de8e1341-6c97-455f-ab1e-443cb194b3a1
                                    [7] => ch-eb54c201-289e-41f0-890d-b2defaa0ce03
                                )

                            [1] => Array
                                (
                                    [0] => ch--4a7yr8KofhR33NTbHEhRi3
                                    [1] => ch--uvWRENr8jleZgjRYbYu4UL
                                    [2] => ch-261dcb57-e9c5-4265-bf68-1490dfed5e1e
                                    [3] => ch-57679539-5d1a-4785-96b0-dfe508997083
                                    [4] => ch-917042150850
                                    [5] => ch-ae133155-feb3-46a2-bd49-70d5edd827dd
                                    [6] => ch-de8e1341-6c97-455f-ab1e-443cb194b3a1
                                    [7] => ch-eb54c201-289e-41f0-890d-b2defaa0ce03
                                )

                            [2] => Array
                                (
                                    [0] => ch--4a7yr8KofhR33NTbHEhRi3
                                    [1] => ch--uvWRENr8jleZgjRYbYu4UL
                                    [2] => ch-261dcb57-e9c5-4265-bf68-1490dfed5e1e
                                    [3] => ch-57679539-5d1a-4785-96b0-dfe508997083
                                    [4] => ch-917042150850
                                    [5] => ch-a37b553f-0e54-4089-b0a0-17d3d5ec683e
                                    [6] => ch-ae133155-feb3-46a2-bd49-70d5edd827dd
                                    [7] => ch-de8e1341-6c97-455f-ab1e-443cb194b3a1
                                    [8] => ch-eb54c201-289e-41f0-890d-b2defaa0ce03
                                )

                            [3] => Array
                                (
                                    [0] => ch--uvWRENr8jleZgjRYbYu4UL
                                    [1] => ch-261dcb57-e9c5-4265-bf68-1490dfed5e1e
                                    [2] => ch-57679539-5d1a-4785-96b0-dfe508997083
                                    [3] => ch-917042150850
                                    [4] => ch-ae133155-feb3-46a2-bd49-70d5edd827dd
                                    [5] => ch-de8e1341-6c97-455f-ab1e-443cb194b3a1
                                    [6] => ch-eb54c201-289e-41f0-890d-b2defaa0ce03
                                )

                            [4] => Array
                                (
                                    [0] => ch--uvWRENr8jleZgjRYbYu4UL
                                    [1] => ch-261dcb57-e9c5-4265-bf68-1490dfed5e1e
                                    [2] => ch-57679539-5d1a-4785-96b0-dfe508997083
                                    [3] => ch-917042150850
                                    [4] => ch-ae133155-feb3-46a2-bd49-70d5edd827dd
                                    [5] => ch-de8e1341-6c97-455f-ab1e-443cb194b3a1
                                    [6] => ch-eb54c201-289e-41f0-890d-b2defaa0ce03
                                )

                            [5] => Array
                                (
                                    [0] => ch--4a7yr8KofhR33NTbHEhRi3
                                    [1] => ch--uvWRENr8jleZgjRYbYu4UL
                                    [2] => ch-261dcb57-e9c5-4265-bf68-1490dfed5e1e
                                    [3] => ch-57679539-5d1a-4785-96b0-dfe508997083
                                    [4] => ch-917042150850
                                    [5] => ch-ae133155-feb3-46a2-bd49-70d5edd827dd
                                    [6] => ch-de8e1341-6c97-455f-ab1e-443cb194b3a1
                                    [7] => ch-eb54c201-289e-41f0-890d-b2defaa0ce03
                                )

                        )

                )

            [channels] => Array
                (
                    [ch--4a7yr8KofhR33NTbHEhRi3] => 
                    [ch--uvWRENr8jleZgjRYbYu4UL] => 
                    [ch-261dcb57-e9c5-4265-bf68-1490dfed5e1e] => 
                    [ch-57679539-5d1a-4785-96b0-dfe508997083] => 
                    [ch-917042150850] => 
                    [ch-a37b553f-0e54-4089-b0a0-17d3d5ec683e] => 
                    [ch-ae133155-feb3-46a2-bd49-70d5edd827dd] => 
                    [ch-de8e1341-6c97-455f-ab1e-443cb194b3a1] => 
                    [ch-eb54c201-289e-41f0-890d-b2defaa0ce03] => 
                )

            [upstream_cas] => 1448110139439054848
            [upstream_rev] => 5-817b3adc5520a5bd1126f24d3fd46597
            [time_saved] => 2015-11-21T18:19:03.550272864+05:30
        )

    [addressID] => 11
    [archivedx] => Array
        (
            [0] => a37b553f-0e54-4089-b0a0-17d3d5ec683e
            [1] => de8e1341-6c97-455f-ab1e-443cb194b3a1
        )

    [authmx] => 917042150850
    [backgroundcolor] => 227,38,54
    [displayname] => Arjun
    [dx] => Array
        (
            [0] => ae133155-feb3-46a2-bd49-70d5edd827dd
            [1] => 57679539-5d1a-4785-96b0-dfe508997083
            [2] => -uvWRENr8jleZgjRYbYu4UL
            [3] => 261dcb57-e9c5-4265-bf68-1490dfed5e1e
            [4] => eb54c201-289e-41f0-890d-b2defaa0ce03
            [5] => -4a7yr8KofhR33NTbHEhRi3
        )

    [epochtime] => 1448017481
    [eptime] => 1448109652
    [firstname] => Arjun
    [mx] => Array
        (
            [0] => 919999883850
            [1] => 919999883850
            [2] => 919999883850
        )

    [org] => Array
        (
            [org_name] => arjun
        )

    [owner] => 917042150850
    [phone] => Array
        (
            [0] => Array
                (
                    [Mobile] => +919999883850
                )

            [1] => Array
                (
                    [Home] => +919849278819
                )

        )

    [type] => cx
)


log from xcode:

2015-11-30 19:09:42.774 arjun[11868:2937114] SyncVerbose: CBLRestPuller[https://918791108792:*****@domian.com::port/db] inserting 1 revisions...
2015-11-30 19:09:42.776 arjun[11868:2937114] SyncVerbose: CBLRestPuller[https://918791108792:*****@domian.com::port/db] inserting -qfwrlzartlDc9rWvssrQ5o ["2-f877d4d8cead27a75ffe191ba98cf25d", "1-c9c077f105e4341aa78146a0b22a4da7"]
2015-11-30 19:09:42.779 arjun[11868:2937114] WARNING: Attachment '-qfwrlzartlDc9rWvssrQ5o.jpg' in {-qfwrlzartlDc9rWvssrQ5o #2-f877d4d8cead27a75ffe191ba98cf25d} has invalid revpos=3
2015-11-30 19:09:42.780 arjun[11868:2937114] WARNING: CBLRestPuller[https://918791108792:*****@domian.com::port/db] failed to write {-qfwrlzartlDc9rWvssrQ5o #2-f877d4d8cead27a75ffe191ba98cf25d}: status=491
2015-11-30 19:09:42.781 arjun[11868:2937114] Sync: CBLRestPuller[https://918791108792:*****@domian.com::port/db] Progress: set error = 400 Invalid attachment
2015-11-30 19:09:42.782 arjun[11868:2937114] Sync: CBLRestPuller[https://918791108792:*****@domian.com::port/db] STOPPING...
2015-11-30 19:09:42.786 arjun[11868:2937114] Sync: Stopping 6 remote requests
2015-11-30 19:09:42.788 arjun[11868:2937114] SyncVerbose: CBLRestPuller[https://918791108792:*****@domian.com::port/db]: postProgressChanged (1771/1830, active=1 (batch=0, net=7), online=1)
2015-11-30 19:09:42.790 arjun[11868:2937114] SyncVerbose: CBLRestPuller[https://918791108792:*****@domian.com::port/db]: postProgressChanged (1774/1830, active=1 (batch=0, net=4), online=1)
2015-11-30 19:09:42.791 arjun[11868:2937114] SyncVerbose: CBLRestPuller[https://918791108792:*****@domian.com::port/db]: postProgressChanged (1780/1830, active=1 (batch=0, net=3), online=1)
2015-11-30 19:09:42.792 arjun[11868:2937114] SyncVerbose: CBLRestPuller[https://918791108792:*****@domian.com::port/db] finished inserting 1 revisions
2015-11-30 19:09:42.793 arjun[11868:2937114] Sync: CBLRestPuller[https://918791108792:*****@domian.com::port/db] inserted 1 revs in 0.018 sec (55.8/sec)
2015-11-30 19:09:42.796 arjun[11868:2937114] Sync: CBLRestPuller[https://918791108792:*****@domian.com::port/db] Progress: set active = 0
2015-11-30 19:09:42.796 arjun[11868:2937114] SyncVerbose: CBLRestPuller[https://918791108792:*****@domian.com::port/db]: postProgressChanged (1780/1830, active=0 (batch=0, net=0), online=1)
2015-11-30 19:09:42.797 arjun[11868:2937114] Sync: CBLRestPuller[https://918791108792:*****@domian.com::port/db] STOPPED
2015-11-30 19:09:42.798 arjun[11868:2937114] Replication: CBLRestPuller[https://918791108792:*****@domian.com::port/db] took 14.220 sec; error=Error Domain=CBLHTTP Code=400 "400 Invalid attachment" UserInfo={NSLocalizedFailureReason=Invalid attachment, NSLocalizedDescription=400 Invalid attachment}
2015-11-30 19:09:42.801 arjun[11868:2937114] SyncVerbose: CBLRestPuller[https://918791108792:*****@domian.com::port/db]: postProgressChanged (1781/1830, active=0 (batch=0, net=0), online=1)

Sync: CBLRestPuller[https://918791108792:*****@domain.com:9443/db] Progress: set error = 400 Invalid attachment
Replication: CBLRestPuller[https://918791108792:*****@domian.com::port/db] took 32.533 sec; error=Error Domain=CBLHTTP Code=400 "400 Invalid attachment" UserInfo={NSLocalizedFailureReason=Invalid attachment, NSLocalizedDescription=400 Invalid attachment}


Thanks
Arjun

**Comment by snej** [comment] 2015-11-30 16:36
The `revpos` is the generation number [the decimal number before the “-“ in `_rev`] at which the attachment was last changed. It’s used during replication to avoid sending unchanged attachments along with updated documents.

The warning `Attachment '-qfwrlzartlDc9rWvssrQ5o.jpg' in {-qfwrlzartlDc9rWvssrQ5o #2-f877d4d8cead27a75ffe191ba98cf25d} has invalid revpos=3` happens because the revpos (3) is _larger_ than the generation number (2), which shouldn’t be possible.

(Please don't paste huge dumps into a bug report. It makes it difficult to read. Use Gist or Pastebin or whatever instead.)

The doc dump from SG shows there's a conflicting revision `2-f877d`... that indeed contains an attachment with a revpos of 3:

```json
{"-qfwrlzartlDc9rWvssrQ5o.jpg":{"content_type":"image/jpeg","digest":"sha1-KcVKoj5OC/u98SssyOIxNdeLskU=","length":88602,"revpos":3,"stub":true}
```
This shouldn't be possible. I'm guessing SG isn't as strict about validating revpos so it allowed this revision to be added; but I don't know how that revision got created in the first place.

**Question:** What clients are in use that push to this server? Are they all CBL/iOS, or are there Android or .NET clients too? What about CouchDB or PouchDB?

**Comment by arjunblue** [comment] 2015-12-01 09:29
Hi,

Thanks for taking time out to help me.

- Not sure how can i validate revpos in sync gateway I can only place integrity check in document to check if  new revision is valid,  please help me out here how to put such a check in syncconfig

- We are creating three revs 1st on doc creation 2nd on updation of doc and 3rd on adding of attachment.

Question: What clients are in use that push to this server? Are they all CBL/iOS, or are there Android or .NET clients too? What about CouchDB or PouchDB?

Ans : we are using android cbl and ios cbl sdk only . We are using bucket shadowing in couchbase server 4.0.  for PHP sdk.

Thanks
Arjun

**Comment by snej** [comment] 2015-12-03 23:26
> Not sure how can i validate revpos in sync gateway

I meant that SG itself should be doing this (but maybe isn't.)

Can you reproduce the steps that create this messed-up doc? It would be great to know the sequence of changes made in CBL.

**Comment by sellingsolutions** [comment] 2015-12-09 13:21
Still getting 400 Invalid attachment with CBL 1.2:
__Sync CBLReplication[from ......]: stopped, progress = 24140 / 24140, err: 400 Invalid attachment__

Do you want access to my change feed?

**Comment by snej** [comment] 2015-12-09 17:44
The changes feed won't help; the problem is that this revision got created in the first place and that it was added to SG without complaint. That's why I asked if you can reproduce the problem from scratch, i.e. the steps that created this revision.

>Also, is there any way that I can prevent the replicator from dying?

Not at the app level, but in CBL we should downgrade this type of error so the replicator can skip the revision and continue (after warning.)

**Comment by Sagaris** [comment] 2015-12-10 08:46
I'm having the some problem on iOS with CBL1.1.1. 
However the error does not occur with CBL for Android 1.1.0 
Retrieving the same document and attachment by means of the Sync REST API does not result in any error. 

This issue has become a real show stopper for us.

**Comment by sellingsolutions** [comment] 2015-12-10 09:21
@snej I think you're referring to @arjunblue but yeah the same goes for me. Except I have no idea how it happened in the first place. 

There are two things that would get my show back on the road:
1) A way to see __which document the offending attachment belongs to__ so that I can delete it
2) Configure the replicator to keep going no matter what happens

If any of those two would work I would be able to serve my customers

**Comment by snej** [comment] 2015-12-10 17:34
>1) A way to see which document the offending attachment belongs to so that I can delete it

By "see" do you mean literally see, by looking at log output, or do you mean an API call that your app can use? If the former, you can look at the warning that's logged and see the doc ID and rev ID. Implementing an API to return this info would actually be a lot harder than just making the replicator not stop.

**Comment by sellingsolutions** [comment] 2015-12-10 20:14
Hmmm, I thought I looked all over. I have sync verbose on and I couldn't see the id or rev using CBL 1.1.1

I'll try one more time though

**Comment by sellingsolutions** [comment] 2015-12-10 20:15
And I was only referring to the log, I have numerous routines that look for error messages and remove offending documents to kick start the replicator

**Comment by sellingsolutions** [comment] 2015-12-10 20:45
I really can't seem to get ahold of the offending documentID, any ideas?

http://pastebin.com/rn4G7EHe

**Comment by snej** [comment] 2015-12-10 23:40
Oops, I think the warning "Attachment ... has invalid revpos=" was only added recently, on the release/1.2 branch.

But you should at least be getting a warning "CBLPuller … failed to write {docid, revid}: status=400". (From -[CBLPuller insertDownloads:].)

**Comment by snej** [comment] 2015-12-11 23:13
@sellingsolutions what clients are you using that sync to your server? We'd really like to find out where the bad revision came from — @zgramana says there may be some CBL/Android issues that could have caused this; they've been fixed, but post-1.1.

**Comment by Sagaris** [comment] 2015-12-12 08:00
I applied a temporary workaround so the iOS App can be used again until a fix is available. I used the Android App with CBL 1.1.0 which does not complain about corrupt attachments and pulled all documents. Then iterate over each document and check for conflicting revisions. Retrieved the attachments from the current revision in case of a conflict and then create a new revision and added the attachments again. After a push from the Android App, the iOS App pull didn't stop and no attachment was lost.

**Comment by snej** [comment] 2016-01-08 23:26
There's not enough info for us to fix anything, and it sounds like you've gotten around the problem, so we'll close this. If a similar problem arises, please reopen or file a new bug. (FYI, in 1.2+ there will be explicit warnings logged giving the docID, so that will make it easier.)

**Closed** 2016-01-08 23:26 UTC
Labels: bug, f: Replication, ready, reproduce/investigate
