### ISSUE TITLE
Latest 551 build is throwing run time error

### ISSUE THREAD

**Issue by sridevi-15** [couchbase/couchbase-lite-ios#2033] opened 2018-01-18 23:03 UTC
Throwing at Database.setLogLevel

Build 551 for iOS

**Comment by sridevi-15** [comment] 2018-01-18 23:04
Give this error in xcode : Thread 1: EXC_BAD_ACCESS (code=1, address=0x8)

**Comment by pasin** [comment] 2018-01-18 23:05
I think I know what it is. Do you have the full stack trace so I can confirm?

**Comment by rajagp** [comment] 2018-01-18 23:07
Looks like a dup of https://github.com/couchbase/couchbase-lite-ios/issues/2032

**Comment by pasin** [comment] 2018-01-19 00:16
I committed the fixes to feature/2.0 branch. Once the CI build is ready, I will let both of you know.

**Comment by pasin** [comment] 2018-01-19 02:00
Fixed in https://github.com/couchbase/couchbase-lite-ios/commit/f38c1da74ab9b9dde843ce0fb93a98b2cbc644bf.

**Closed by pasin** 2018-01-19 02:00 UTC
