### ISSUE TITLE
Pull replication missing documents from SG channel

### ISSUE THREAD

**Issue by nl** [couchbase/couchbase-lite-ios#608] opened 2015-02-22 12:50 UTC
This scenario might be hard to diagnose, but it has been happening consistently to me for months and months, so I'll try to start a conversation around it and hopefully someone will have a brilliant idea of what's going wrong.

Sync Gateway is setup with shadowing and a sync function with many channels (hundreds). The sync function doesn't give access to channels to any users. The json config file declares one admin user, which has access to the wildcard channel ('*').

Clients start pulling channels using the admin user, and all goes well for a few days/weeks. After a while (meaning: SG restarts, a couple changes to the sync function and manual calls to /_resync, clients going offline/online, etc.), the clients are out of sync.

Documents are correctly assigned to channel X (after careful inspection using the Admin API), clients are correctly pulling channel X (after careful inspection of CBL's and SG's logs) using the admin user (which has access to all channels), but some of those documents are not being pulled (some are).

A workaround that works everytime is deleting the database file from Application Support. This resets the pull replications which start over from scratch but, this time, don't miss any documents. Until this happens again a couple of weeks later.

Any thoughts? I'm not sure what more info to provide to help further.

**Comment by snej** [comment] 2015-02-22 18:20
This might equally well be a Sync Gateway issue. Any ideas, @adamcfraser / @ajres / @tleyden ?

**Comment by adamcfraser** [comment] 2015-02-23 17:53
I'm wondering about the _resync step.  Jens - do you recall whether that has the potential to update the set of channels on a document without updating the sequence number for that document?  In that scenario you'd end up with documents added to channel X, but with sequences earlier than the client's 'since' value that wouldn't get synchronized.

**Comment by pasin** [comment] 2015-02-24 07:43
@nl You mentioned that the issue did happen again in a couple week after resetting the database. Between the time that you reset the database and the time that you see the issue happening again, have you also changed the sync function and/or called _resync?

**Comment by nl** [comment] 2015-02-24 07:45
I think so, cause I tend to tinker with the sync function every so often, but I'm not positive. I'll keep an eye out for this though and report back if I see the bug again without touching the sync function.

**Comment by nl** [comment] 2015-03-01 12:16
Even without resyncing, I can confirm CBL ultimately misses documents from the gateway.

**Comment by pasin** [comment] 2015-03-01 19:07
Thanks for reporting back. 

Can you describe a little bit more about your puller setup?
- How many pullers (on the same missing doc channels) are you running at the same time? and Are they continuous or one-time?
- Are you running all of your pullers on the same thread?
- Are these pullers the ones that you start/stop/recreate every few seconds?

**Comment by pasin** [comment] 2015-03-01 19:49
Also do you have any logs (CBL and SyncGateway) that you can share when you saw that the docs are missing from the pull replication?

**Comment by nl** [comment] 2015-03-02 06:35
- I'm running a few dozen pullers, but each one is pulling a different channel. So the answer to your question is one. 
- I don't use any custom threading for CBL, and the few dozen pullers I'm talking about are different processes on different machines, all pointing to the same gateway.
- Because continuous replications are doomed on OS X, I run one-time replications, wait for them to finish, wait a few seconds then recreate them.
- I am using SG 1.0.3 on Ubuntu from the Couchbase downloads website.

As far as logs go, I'm not sure what to send, but next time this happens (in a couple of days I'm sure), I'll take a look.

**Comment by pasin** [comment] 2015-03-06 17:55
@nl have the issue happened again? I have a couple more questions that I should ask from the beginning.

1. How did you detect that some documents were not pulled from the remote (e.g. manually query, see the result of the live query from the app UI, or using document viewer to check the database)?

2. Do the missing docs have anything in common? For example, they are results of conflict resolutions, they have big attachments, or anything.

**Comment by pasin** [comment] 2015-03-09 19:22
@zgramana told me that there was one issue (https://github.com/couchbase/sync_gateway/issues/525) recently fixed (https://github.com/couchbase/sync_gateway/pull/686) in the Sync Gateway which may represent the behavior reported in this ticket that a client (puller) could miss some documents. 

@nl could you try to use sync gateway from the master branch and see it the issue happens again? You can either build one your self or download a binary from [here](http://latestbuilds.hq.couchbase.com/couchbase-sync-gateway/0.0.0/0.0.0-374/couchbase-sync-gateway-enterprise_0.0.0-374_x86_64.deb).

**Comment by pasin** [comment] 2015-03-27 02:01
I'm closing the issue for now. Please feel free to reopen when there is more information.

**Closed by pasin** 2015-03-27 02:01 UTC
Labels: backlog, bug, needsmoreinfo, reproduce/investigate

**Comment by pradipvaghasiya** [comment] 2016-09-28 17:46
This is happening to me as well. Continuous replication is missing some doc to pull. Doc is properly added to channel. Some devices get the doc some devices dont. Setup in different devices is exactly same with same build.

Killing the app and restarting (i. e. Restarting continuous replication ) does not work either. Once it is missed it is never pulled.

I am using latest Couchbase lite and Sync Gateway 1.3.1 version. This is so indeterministic that I cant reproduce but this is happening now and then. Can someone please help?
