### ISSUE TITLE
2.0 : TIC Read Status 1:57 error spam

### ISSUE THREAD

**Issue by BrandonNott** [couchbase/couchbase-lite-ios#2140] opened 2018-04-12 13:27 UTC
When CouchbaseLite 2.0 cannot connect to sync gateway -
(i.e. incorrect network routing, sluggish VPN, sync gateway instance is down)

The console is spammed with this error which repeats indefinitely and never recovers.
The memory usage of the app continues to rise until the app crashes.

```
2018-04-12 09:16:24.374532-0400 MyApp[4179:55526] TIC Read Status [2:0x6080001660c0]: 1:57
2018-04-12 09:16:24.374706-0400 MyApp[4179:55526] TIC Read Status [2:0x6080001660c0]: 1:57
2018-04-12 09:16:24.374902-0400 MyApp[4179:55526] TIC Read Status [2:0x6080001660c0]: 1:57
2018-04-12 09:16:24.375077-0400 MyApp[4179:55526] TIC Read Status [2:0x6080001660c0]: 1:57
2018-04-12 09:16:24.490190-0400 MyApp[4179:55526] TIC Read Status [2:0x6080001660c0]: 1:57
2018-04-12 09:16:24.490464-0400 MyApp[4179:55526] TIC Read Status [2:0x6080001660c0]: 1:57
2018-04-12 09:16:24.490745-0400 MyApp[4179:55526] TIC Read Status [2:0x6080001660c0]: 1:57
2018-04-12 09:16:24.490953-0400 MyApp[4179:55526] TIC Read Status [2:0x6080001660c0]: 1:57
2018-04-12 09:16:24.491161-0400 MyApp[4179:55526] TIC Read Status [2:0x6080001660c0]: 1:57
2018-04-12 09:16:24.491366-0400 MyApp[4179:55526] TIC Read Status [2:0x6080001660c0]: 1:57
2018-04-12 09:16:24.491560-0400 MyApp[4179:55526] TIC Read Status [2:0x6080001660c0]: 1:57
2018-04-12 09:16:24.491789-0400 MyApp[4179:55526] TIC Read Status [2:0x6080001660c0]: 1:57
2018-04-12 09:16:24.492087-0400 MyApp[4179:55526] TIC Read Status [2:0x6080001660c0]: 1:57
2018-04-12 09:16:24.492318-0400 MyApp[4179:55526] TIC Read Status [2:0x6080001660c0]: 1:57
2018-04-12 09:16:24.492532-0400 MyApp[4179:55526] TIC Read Status [2:0x6080001660c0]: 1:57
2018-04-12 09:16:24.492775-0400 MyApp[4179:55526] TIC Read Status [2:0x6080001660c0]: 1:57
2018-04-12 09:16:24.493000-0400 MyApp[4179:55526] TIC Read Status [2:0x6080001660c0]: 1:57
2018-04-12 09:16:24.493236-0400 MyApp[4179:55526] TIC Read Status [2:0x6080001660c0]: 1:57
2018-04-12 09:16:24.493433-0400 MyApp[4179:55526] TIC Read Status [2:0x6080001660c0]: 1:57
2018-04-12 09:16:24.493648-0400 MyApp[4179:55526] TIC Read Status [2:0x6080001660c0]: 1:57
2018-04-12 09:16:24.493953-0400 MyApp[4179:55526] TIC Read Status [2:0x6080001660c0]: 1:57
2018-04-12 09:16:24.494686-0400 MyApp[4179:55526] TIC Read Status [2:0x6080001660c0]: 1:57
```
--------
* Version:   CouchbaseLiteSwift 2.0 DB 23
* Client OS: iOS 11.3
* Server:    Sync Gateway 2.0 beta 2

**Comment by snej** [comment] 2018-04-12 17:00
In other words, the logging is from the OS, not from our code, so we can't make it go away. It's weird that it's happening so often though — we may be trying to retry connections too rapidly.

**Comment by BrandonNott** [comment] 2018-04-12 18:18
I am able to reproduce this issue in a local environment using docker-compose with the right conditions.  I think what needs to happen is docker is listening on port 4984, but the sync gateway service has stopped.

**Comment by BrandonNott** [comment] 2018-04-12 18:26
Here's the same behavior, different app, with verbose logging enabled
```
Database.setLogLevel(.verbose, domain: .all)
```
```
2018-04-12 14:23:40.056002-0400 MyApp[17078:249756] TIC Read Status [2:0x6000001645c0]: 1:57
2018-04-12 14:23:40.056113-0400 MyApp[17078:249865] CouchbaseLite WS Verbose: Received 0 bytes of HTTP response
2018-04-12 14:23:40.056156-0400 MyApp[17078:249754] TIC Read Status [1:0x604000166000]: 1:57
2018-04-12 14:23:40.056226-0400 MyApp[17078:249757] CouchbaseLite WS Verbose: Received 0 bytes of HTTP response
2018-04-12 14:23:40.056277-0400 MyApp[17078:249756] TIC Read Status [3:0x600000164740]: 1:57
2018-04-12 14:23:40.056355-0400 MyApp[17078:249865] CouchbaseLite WS Verbose: Received 0 bytes of HTTP response
2018-04-12 14:23:40.056394-0400 MyApp[17078:249756] TIC Read Status [2:0x6000001645c0]: 1:57
2018-04-12 14:23:40.056457-0400 MyApp[17078:249757] CouchbaseLite WS Verbose: Received 0 bytes of HTTP response
2018-04-12 14:23:40.056513-0400 MyApp[17078:249754] TIC Read Status [1:0x604000166000]: 1:57
2018-04-12 14:23:40.056662-0400 MyApp[17078:249865] CouchbaseLite WS Verbose: Received 0 bytes of HTTP response
```

**Comment by pasin** [comment] 2018-04-12 18:55
This is weird behavior. The `CouchbaseLite WS Verbose: Received 0 bytes of HTTP response` is logged from the completion handler when reading the HTTP response during establishing WebSocket connection time. I would expect more logging messages such as "CBLWebSocket connecting to..." and "CBLWebSocket Sent HTTP request..." in the same loop.

**Comment by snej** [comment] 2018-04-12 20:05
It looks like the read completion handler (in `-readHTTPResponse`) is being called with an ENOTCONN error. But it calls `-checkError:`, which calls `[self ignoreError: error]`, which returns true for ENOTCONN ... so the completion handler just appends zero bytes to the response and continues.

Apparently CFNetwork is confused by the task not getting closed, so it just loops and calls the completion handler again, which forms an infinite loop.

The comment in `-ignoreError:` says "We sometimes get bogus(?) ENOTCONN errors after closing the socket". But they shouldn't be ignored in this context because the socket is open. So something needs to be refactored so `-ignoreError:` only gets called in situations where the socket has been closed. Maybe take the call out of `-checkError:` and refactor it into the call sites where it makes sense?

**Comment by pasin** [comment] 2018-04-16 18:45
After reviewing the code, I believe we could just remove the `ignoreError:` check, then it will work. The -didCloseWithError: has already called `-ignoreError:` to check the error. 

Note that I still couldn't reproduce this issue myself. Basically I couldn't manage to get ENOTCONN error. I have also tried to use docker but all I got is ECONNREFUSED. 

@BrandonNott by any chance, would it be possible to reproduce the issue with `.network` log enabled? I would like to make sure that I don't miss anything as it's a bit weird to me that `_requestedClose` flag was set to true.

**Comment by BrandonNott** [comment] 2018-04-16 19:17
```
2018-04-16 12:13:53.179063-0700 MyApp[17039:374761] CouchbaseLite BLIP Info: {Connection#1}==> litecore::blip::Connection ->wss:example.com/sync_gateway/test/_blipsync
2018-04-16 12:13:53.179246-0700 MyApp[17039:374761] CouchbaseLite BLIP Info: {Connection#1} Opening connection...
2018-04-16 12:13:53.183068-0700 MyApp[17039:375526] CouchbaseLite WS Info: CBLWebSocket connecting to example.com...
2018-04-16 12:13:53.226583-0700 MyApp[17039:375526] [] nw_connection_fillout_tcp_statistics 6 Connection is not ready
2018-04-16 12:13:53.226947-0700 MyApp[17039:375526] [] tcp_connection_get_statistics Failed to get statistics from connection
2018-04-16 12:13:53.290543-0700 MyApp[17039:375525] CouchbaseLite WS Info:     useCredential for trust: <NSURLCredential: 0x608000011b60>: (null)
2018-04-16 12:13:53.338841-0700 MyApp[17039:375526] CouchbaseLite WS Verbose: CBLWebSocket Sent HTTP request...
2018-04-16 12:14:05.374927-0700 MyApp[17039:375525] TIC Read Status [6:0x60c000171e80]: 1:57
2018-04-16 12:14:05.375369-0700 MyApp[17039:375526] CouchbaseLite WS Verbose: Received 0 bytes of HTTP response
2018-04-16 12:14:05.375471-0700 MyApp[17039:375525] TIC TCP Conn Missing Error [6:0x60c000171e80]: Generating 1:54
2018-04-16 12:14:05.375636-0700 MyApp[17039:375526] TIC Read Status [6:0x60c000171e80]: 1:57
2018-04-16 12:14:05.375821-0700 MyApp[17039:375524] CouchbaseLite WS Verbose: Received 0 bytes of HTTP response
2018-04-16 12:14:05.376043-0700 MyApp[17039:375526] TIC Read Status [6:0x60c000171e80]: 1:57
2018-04-16 12:14:05.376314-0700 MyApp[17039:375524] CouchbaseLite WS Verbose: Received 0 bytes of HTTP response
2018-04-16 12:14:05.376530-0700 MyApp[17039:375526] TIC Read Status [6:0x60c000171e80]: 1:57
2018-04-16 12:14:05.376742-0700 MyApp[17039:375525] CouchbaseLite WS Verbose: Received 0 bytes of HTTP response
2018-04-16 12:14:05.376967-0700 MyApp[17039:375526] TIC Read Status [6:0x60c000171e80]: 1:57
2018-04-16 12:14:05.377231-0700 MyApp[17039:375525] CouchbaseLite WS Verbose: Received 0 bytes of HTTP response
```

**Comment by BrandonNott** [comment] 2018-04-16 21:16
This commit did not seem to help: https://github.com/couchbase/couchbase-lite-ios/commit/fa0f92086d9a3a617ee5d4f52153772ae6cbafcc

@pasin I have emailed you additional logs as well as a docker-compose setup for recreating the issue locally.

**Comment by pasin** [comment] 2018-04-16 21:54
@BrandonNott I received some additional log but not the docker-compose setup. Can you send me the docker-compose setup to reproduce the issue?

**Comment by pasin** [comment] 2018-04-16 22:27
Again thanks @BrandonNott for the docker-compose and the steps to reproduce the issue. The assumption that CFNetwork returns ENOTCONN as indicated by the TIC log messages is wrong. It turns out the completionHandler of the `readDataOfMinLength:maxLength:timeout:completionHandler: ^(NSData* data, BOOL atEOF, NSError* error)` is called in loop without error.

**Comment by pasin** [comment] 2018-04-16 22:49
@BrandonNott I have re-fixed the issue. Could you please verify the fix from the master branch?

**Closed** 2018-04-16 22:48 UTC
Labels: crash!, f: Replication, ffc, reproduce/investigate

**Comment by BrandonNott** [comment] 2018-04-16 23:26
I can confirm that this fixed the issue!  Thank you @pasin 💯

**Comment by pasin** [comment] 2018-04-17 00:51
Thanks for the confirmation!
