### ISSUE TITLE
405 method_not_allowed returned from Cloudant when pulling with Couchbase Lite 1.2

### ISSUE THREAD

**Issue by jordanpwood** [couchbase/couchbase-lite-ios#1020] opened 2016-01-08 17:08 UTC
When starting a pull replication with Cloudant with Couchbase Lite 1.2, Cloudant is returning a 405 status.  Apparently, Cloudant doesn't support POST to _changes yet.  This isn't that surprising, since they are based on version 1.0.2 of CouchDB.

**Comment by snej** [comment] 2016-01-08 17:27
Cloudant's actually heavily forked from CouchDB; I don't think their version numbers bear any relation to each other. They do merge CouchDB changes over into their code sometimes, though.

**Comment by snej** [comment] 2016-01-08 22:05
Even more confusingly, if you try to POST to `_changes` when you only have read access to the Cloudant db, you instead get a 401 status, with body `{"error":"unauthorized","reason":"_writer access is required for this request"}`. This confused me for a few minutes...

**Comment by snej** [comment] 2016-01-08 22:14
I was going to detect the 405 status and retry without POST, but the 401 status is harder to disambiguate because it also occurs if you need a password. Instead I'm going to take the easy way out and just check whether the hostname ends with ".cloudant.com" before sending the request.

**Comment by snej** [comment] 2016-01-08 22:32
Fixed on release/1.2 branch.

**Comment by jordanpwood** [comment] 2016-01-08 22:34
:+1: Thanks Jens!

**Comment by jordanpwood** [comment] 2016-01-11 14:55
This solution does cause some headaches for us, since we actually use our own URL which resolves to Cloudant.  Is there any way this could be a parameter which is set when we start the replication?  Or at least only have "cloudant" somewhere in the URL instead of "cloudant.com" being required at the end?

**Comment by willholley** [comment] 2016-01-11 16:39
a couple of other ideas for detecting Cloudant:
1. the database endpoint always returns "instance_start_time":"0"
2. the response will contain a header "Server: CouchDB/1.0.2 (Erlang OTP/17)". You could look for CouchDB/1.0.2 as a pretty reliable indicator.

To confirm what was said above, Cloudant forked CouchDB at 1.0.2 hence we report that. However, our functionality is closer to CouchDB 2.0. We're shortly to release an update which brings us fully in line with CouchDB 2.0 and the Apache repos will be the basis for future releases rather than our fork.

**Comment by willholley** [comment] 2016-01-11 16:55
also bear in mind that Cloudant doesn't support the _doc_ids filter yet (again, it will be in the next release) - I'm not sure why else you'd POST to _changes...

**Comment by jordanpwood** [comment] 2016-01-11 17:17
@snej, is there any hope of getting a non-URL based solution in before 1.2 is released?

**Comment by snej** [comment] 2016-01-13 18:13
I'll put in a better fix — the previous one was a bit of a band-aid, trying to avoid risk of regressions.
The next fix will probably be to detect the 405 and retry without using POST. I'll try to get that in today.

**Comment by snej** [comment] 2016-01-13 21:50
OK, better fix is now in on release/1.2.

**Closed by snej** 2016-01-13 21:50 UTC
Labels: compatibility, f: Replication, in progress

**Comment by mike-lang** [comment] 2016-01-14 17:10
Thanks so much!
