### ISSUE TITLE
2.0: database.deleteDocument(document) returns "404 not found"

### ISSUE THREAD

**Issue by raghusarangapani** [couchbase/couchbase-lite-ios#2003] opened 2017-12-29 19:48 UTC
CBL 2.0 top of tree feature/cbl2.0 branch

test case
```
def test_delete_doc(self, dbName, docId):
        '''
        @summary: Testing delete method of Database API
        '''
        doc = self.doc_obj.create(doc_id=docId)
        db = self.db_obj.create(dbName)
        self.db_obj.saveDocument(db, doc)
        self.db_obj.delete(document=doc, database=db)
        doc_res = self.db_obj.getDocument(db, docId)
        assert doc_res is None
```
The test is expecting a nil response to getDocument call above.

Swift code for fetching a doc corresponding to the above `self.db_obj.getDocument(db, docId)`:
```
            let database: Database = (args.get(name:"database"))!
            let id: String? = args.get(name: "id")
            let doc = database.document(withID: id!)
            print("doc is \(doc)")
            return doc
```
The above code prints
```
doc is Optional(CouchbaseLiteSwift.Document)
```
and hence, the test fails
```
>       assert doc_res is None
E       assert <CBLClient.MemoryPointer.MemoryPointer instance at 0x10c8c37e8> is None
```

**Comment by pasin** [comment] 2017-12-29 20:46
I couldn't reproduce the issue. There is also a unit test covering this test case as [here](https://github.com/couchbase/couchbase-lite-ios/blob/feature/2.0/Swift/Tests/DocumentTest.swift#L1100-L1112). 

Could you please check if `self.db_obj.delete(document=doc, database=db)` is actually deleting the document?

**Comment by rajagp** [comment] 2018-01-02 15:29
FWIW, I tested this and was unable to reproduce this issue. Seems to be working as expected

**Comment by pasin** [comment] 2018-01-02 18:34
@raghusarangapani as we couldn't reproduce the issue. I'm closing the issue now. Feel free to reopen the issue.

**Comment by raghusarangapani** [comment] 2018-01-02 22:04
I showed the issue to @pasin and @pasin is able to reproduce the issue now with a unit test case. The issue seems to be that if I create a doc separately, a DB separately and then save the doc to the DB, database.deleteDocument(document) returns "404 not found"

**Comment by rajagp** [comment] 2018-01-02 22:07
@raghusarangapani  Can you please specify the steps to reproduce.

**Comment by raghusarangapani** [comment] 2018-01-02 22:13
1. Create a doc with an ID - lets say the return doc ref is @1
2. Create a DB with a name - lets say the return db ref is @2
3. Save @1 to @2  - lets say the return db ref is @3
4. Delete @1 from @2.
-> This returns a 404: Not Found error.

**Comment by snej** [comment] 2018-01-02 23:07
The test is incorrect. The document `@1` doesn't have a revision ID; instead, the save method returns a new Document instance representing the saved document. That's the one that should be deleted.

I think this API is going to really confuse people ... it seems unnatural that after saving a Document, the Document instance doesn't reflect the effect of the save.

**Comment by raghusarangapani** [comment] 2018-01-03 17:46
See also https://github.com/couchbase/couchbase-lite-android/issues/1449

**Comment by borrrden** [comment] 2018-01-03 23:47
As noted above, whatever save API is being used in the testing API should return a new handle to be used for deletion.  So in your example, "3" should be used, instead of "1"

**Comment by pasin** [comment] 2018-01-04 00:04
I have looked into this with @waynecarter and @adamcfraser to compare the behavior with SGW. We should inline the implementation with what SGW is doing now.

Basically, if using @1 to delete the document, it should be like trying to create a tombstone revision at root which will end up getting conflicts.

**Comment by pasin** [comment] 2018-01-04 00:07
I will send out the notes along with the other API bug fixes.

**Comment by borrrden** [comment] 2018-01-04 00:15
> create a tombstone revision at root

This can be interpreted in two ways.  The first is creating a new generation 1 tombstone, which is nonsense and should not be allowed (That is the reason for the 404 error, I think).  The second is creating a generation 2 tombstone on top of generation 1, which sounds sensical but how can the generation 1 revision ID be retrieved?  It's not guaranteed to exist.

**Comment by snej** [comment] 2018-01-04 00:44
> We should inline the implementation with what SGW is doing now

But you can't really compare a REST API with a native OO API; it's apples and oranges. The SG equivalent of a Document object is the URL of the document, which doesn't behave the same way at all.

Returning a new distinct Document instance from the save method is kind of like what's done in functional languages where everything's immutable and you can't alter a value, only return a new one. But our API isn't like that. The document being saved is mutable, and it seems natural to me that saving would update the instance to store the new revID, making it useable afterwards.

**Comment by pasin** [comment] 2018-01-04 01:24
> This can be interpreted in two ways. The first is creating a new generation 1 tombstone, which is nonsense and should not be allowed (That is the reason for the 404 error, I think).

Current SGW implementation allowed this.

> The second is creating a generation 2 tombstone on top of generation 1, which sounds sensical but how can the generation 1 revision ID be retrieved? It's not guaranteed to exist.

If this situation happens, this will be done via conflict handling.

**Comment by borrrden** [comment] 2018-01-04 02:15
Is it possible that you meant to say create a tombstone "at the leaf" instead of "at the root"?  This is the current behavior of Sync Gateway which, for better or for worse, lets you create tombstone after tombstone without complaint (I just created 6 of them on top of each other).

**Comment by pasin** [comment] 2018-01-04 02:18
That's right. I forgot that when the current revision is a tombstone, a new revision will be appended under. The tombstone revision gets treated specially. @snej / @adamcfraser told me this before.

**Comment by pasin** [comment] 2018-01-19 02:06
We could close this issue now. The current behaviors of the Database.delete(document) are followings:
* If the document doesn't exist in the database, the delete operation will be no-ops without error.
* If the document has already been deleted, the delete operation will go thru conflict resolution. With the default conflict resolution, the delete operation will turn into no-ops without error as well.

**Closed by pasin** 2018-01-19 02:06 UTC
Labels: P1: high, backlog
