### ISSUE TITLE
Enterprise edition builds missing database encryption 

### ISSUE THREAD

**Issue by sridevi-15** [couchbase/couchbase-lite-ios#2070] opened 2018-02-20 21:17 UTC
--------
* Version:   2.0.0-604
* Client OS: iOS
* CB Server:    5.0.0-3519 
* Sync Gateway : 2.0.0-733

I got latest ios builds of 604 and I see that database encryption feature missing in enterprise edition.

**Comment by pasin** [comment] 2018-02-20 21:31
I have fixed the issue for Swift in https://github.com/couchbase/couchbase-lite-ios/commit/5d1302ea7c86cff518fcdff61f47a100223ae99b. I'm working on Objective-C to make the headers visible in EE.

**Comment by pasin** [comment] 2018-02-21 16:48
The Objective-C should be fixed in https://github.com/couchbaselabs/couchbase-lite-ios-ee/commit/068dfb87cb0b45708c12ace6a267fc9ded93104c. When the new build is out (611), please check if the issue is fixed.

**Closed by pasin** 2018-02-21 16:48 UTC
Labels: P1: high, ready

**Comment by snej** [comment] 2018-02-21 18:54
(To be clear, in case anyone panics about the title of the bug: the encryption feature was present, it's just that the public API headers didn't include the methods to access it.)
