### ISSUE TITLE
CBLIS - Very poor performances from 5000 documents locally

### ISSUE THREAD

**Issue by mastohhh** [couchbase/couchbase-lite-ios#938] opened 2015-10-06 08:23 UTC
Despite the optimizations @pasin did here : https://github.com/couchbase/couchbase-lite-ios/issues/793, I still encounter performance issues.

I really don't know what's the best practice to use both `CBLManager` and `NSManagedObjectContext`. Here's what I tried : 

## 1 - Parent Context - Private context's queue : 

- A main context that has a parent context
- A private context parent of the main, and with a coordinator.
- `dispatchQueue` of `CBLManager` is the same as the private context's queue. 

This is the one I actually use.

The problem with this one is `dispatch_get_current_queue();` will be deprecated. And it's not really fast.

## 2 - Parent Context - Background Queue

- A main context that has a parent context
- A private context parent of the main, and with a coordinator.
- `dispatchQueue` of `CBLManager` is `dispatch_get_global_queue(DISPATCH_QUEUE_PRIORITY_BACKGROUND, 0)`.

It gives sometimes crashes like :  `The FMDatabase <CBL_FMDatabase: 0x7ae753c0> is currently in use.`
`*** Assertion failure in -[CBL_FMDatabase warnInUse], FMDatabase.m:360`

## 3 - Main Context - Main Thread : 

- Only one context in the main thread with the coordinator.
- `dispatchQueue` of `CBLManager` is by default, main thread.

This is very slow

## 4 - Main Context - Background Queue : 

- Only one context in the main thread with the coordinator.
- `dispatchQueue` of `CBLManager` is `dispatch_get_global_queue(DISPATCH_QUEUE_PRIORITY_BACKGROUND, 0)`.

Every calls to `performBlock:` fails.
Slow and crashes like :  `The FMDatabase <CBL_FMDatabase: 0x7ae753c0> is currently in use.`

## 5 - Confinment Context - Background Queue

- `dispatchQueue` of `CBLManager` is `dispatch_get_global_queue(DISPATCH_QUEUE_PRIORITY_BACKGROUND, 0)`.
- Only one context `NSConfinementConcurrencyType` (deprecated) in the `dispatchQueue` of `CBLManager`.

Error message `Can only use -performBlock: on an NSManagedObjectContext that was created with a queue.`

## Conclusion

Performance goes down as the global number of documents increase.

Our app needs to handle thousands of documents (our firsts users maybe 100 000). There was no problem with classic CoreData SQLite. Now we have to purge old documents, and still remains problems of performance. Both in the saves, as in the fetches.

As iOS9 is available on iPad 2, we can't have an app that blocks for many seconds during usage. iPad Air 1 has UI lags from 5000 documents. 

I think pure couchbase-lite-ios without CoreData can be fast with `CBLManager`'s `dispatchQueue`, but maybe it's not design for `NSManagedObjectContext`s ?

Do you have a CoreData stack that works fine ?

Do you think `CBLIncrementalStore` can be optimized again ? I saw that `CBLQueryEnumerator* rows = [query run: outError];` is called often and behind there's `int rc = sqlite3_step(statement.statement);` and I don't think we can optimize that.

Does ForestDB is 100x faster ?

Thanks

**Comment by pasin** [comment] 2015-10-09 22:09
@mastohhh I will look into this in the next sprint (next week). Thanks a lot for reporting this.

**Comment by pasin** [comment] 2015-10-09 22:17
By any chance, have you run any profiling to see where the CBIS spent most time on during the save or fetch operations that are lagged?

**Comment by mastohhh** [comment] 2015-10-12 09:16
Here are my profiling results.

- Save Operation

As you already told me the `updateIndex` method is slow.

<img width="1920" alt="save" src="https://cloud.githubusercontent.com/assets/1760064/10424522/fee9039c-70cf-11e5-8d88-fe797b16981e.png">

- Inform after save

`currentRevision` is slow.

<img width="1920" alt="inform" src="https://cloud.githubusercontent.com/assets/1760064/10424529/11736cf0-70d0-11e5-85a4-af7a355fd2df.png">

- Normal fetches during using the app

`[CBL_FMResultStep step]` is slow.

<img width="1920" alt="query" src="https://cloud.githubusercontent.com/assets/1760064/10424541/2f8c8fa0-70d0-11e5-9381-5c7e99c737c7.png">


It's just a feeling, but I think every tables get slow even if a table contains only 1 row. I opened the sqlite file and I saw that there was one table per Entity, so I don't understand why everything become slow.

Do you think you can create a Performance Test with CBLIncrementalStore ? I'd like to try some optimizations but I can't stay on a feeling.

Thanks

**Comment by pasin** [comment] 2015-10-12 16:49
I think this is a very good starting point. I will look closely to your profiling result soon.

> Do you think you can create a Performance Test with CBLIncrementalStore ? I'd like to try some optimizations but I can't stay on a feeling.

Yes, that is my plan for this week to do CBLIS performance test. I will let you know once I have that setup. Thank for your patience.

**Comment by pasin** [comment] 2015-10-14 20:15
When profiling above cases, how many CoreData objects did you save or updates at once?

**Comment by mastohhh** [comment] 2015-10-14 20:16
More or less a thousand.

**Comment by pasin** [comment] 2015-10-14 20:45
> More or less a thousand

I see. That explains why the method like `newValuesForObjectWithID` has high number of execution time. 

A few questions about 1-many relationship case:
1. How many sub entities per a parent entity?
2. How many parent entities?
3. How many do you insert/update parent and sub entities at once? (e.g. 1 parent and 500 sub at once?)

**Comment by mastohhh** [comment] 2015-10-14 21:03
It's a 4 depth model. 1 parent with 10 subEntities, each one have 10 subSubEntities, and 10 more subSubSubEntities.

**Comment by pasin** [comment] 2015-10-16 01:15
Here are some tasks that could help improving performance:
[ ] Not firing fault for the changes coming from local database. I understand that there is no needs for this.
[ ] Before firing fault, should check if the object is in fault state or not. If it's in the fault state, ignore firing fault.
[ ] Cache NSIncrementalStoreNode returned by newValuesForObjectWithID:withContext:error:.
[ ] From the profiling results by @mastohhh above, all of the captured methods seemed to be executed on the main thread which definitely affect to UI performance. Verify what should be an appropriate context setup.

**Comment by mastohhh** [comment] 2015-10-20 13:15
I will really enjoy if I can help on this.

We discussed about that in my team, we think that if we have to choose between improving save, fetch, or inform : we chose fetches.

- Saves happen just after the user action. So we feel slow saves only when user does several actions close together.

- Informs happen when other devices sends data.

- But fetches slow down the user action itself.

Most of user actions create objects. That's why I think caching requests is not very helpful in our case.

But I saw that caching relationships uses `view.database.lastSequenceNumber` to know if we have to fetch again. Why this number is on the whole database ? Does that mean if I add Subentries, the next fetch on Entries (unchanged) will not use cache because of `lastSequenceNumber` ?

If I'm right : can we imagine a `lastSequenceNumber` by entity ?

**Comment by snej** [comment] 2015-10-20 16:12
Yes, `lastSequenceNumber` is global to the entire database. Every document revision is assigned a new sequence number from an incrementing counter. This is a key part of how replication works.

>If I'm right : can we imagine a lastSequenceNumber by entity ?

You mean a counter that only changes when a document of that entity type is modified? The closest equivalent would be `CBLView.lastSequenceChangedAt` (currently private API) which tells you the latest sequence number that affected that view's index. For example, if you look at this property, then update the view index, then look at the property again and it hasn't changed, it tells you that the index is still the same as before. (CBLLiveQuery uses this to avoid triggering unnecessarily.)

**Comment by pasin** [comment] 2015-10-20 22:19
@mastohhh 
I have push my performance fix around save operation and firing fault / merging changes. Basically there is no firing fault anymore and I only use merge contexts with notification. Also there is no merging or notifying operation for local database changes. 

Could you please check out CBLIS from [feature/issue_938_perf](https://github.com/couchbase/couchbase-lite-ios/tree/feature/issue_938_perf) branch and see how it works for you. Please let me know.

Note: I have noticed that when running performance test the CBLIS code that handles database changes doesn't get called because the test finished before that get executed. I don't have a good way to measure that part now.

**Comment by mastohhh** [comment] 2015-10-20 22:33
@pasin Thank you.

Could you please tell me what's your core data stack (context and persistent store creation) ? Could you copy paste here your code from your test app ?

I'll be sure if I did it right.

**Comment by pasin** [comment] 2015-10-20 23:48
I copied your parent-child context setup from the email you sent me a few months ago. So I guessed you already did it right.

**Comment by mastohhh** [comment] 2015-10-20 23:52
We just finished testing your branch.

On performance side, it's really better.

But we saw that sometimes after receiving changes from other devices, contexts are not up to date. (After an app kill/relaunch everything's good)

**Comment by pasin** [comment] 2015-10-21 00:03
I just also push a change to use `CBLView.lastSequenceChangedAt` (Private API) to check whether the relationship cache is still valid or not. You can check if that does any help on your end.

**Comment by pasin** [comment] 2015-10-21 00:16
Probably only merging contexts with notification is not enough. Somehow it works fine on my setup (probably too simple). I may need to add firing fault back.

**Comment by pasin** [comment] 2015-10-21 00:24
@mastohhh , when you see contexts are not up to date, do you realize it from NSFetchResultController doesn't get notification? If you are using NSFetchResultController, would it be possible to disable cache to see if it helps.

**Comment by mastohhh** [comment] 2015-10-21 00:27
Yes I use lots of NSFetchedResultsController.

But I also see https://github.com/couchbase/couchbase-lite-ios/issues/903 back.

**Comment by pasin** [comment] 2015-10-21 01:00
Before I get the firing fault back, could you help making 1 line change to see if it helps?

https://github.com/couchbase/couchbase-lite-ios/blob/873d5960f503a910abdaf55c3af60ea24601c199/Source/API/Extras/CBLIncrementalStore.m#L2168-L2170

Can you change to use performBlockAndWait: instead?

**Comment by pasin** [comment] 2015-10-21 01:40
I found 2 issues related to cache. I will fix this tonight and let you know. Hope it's related to the issue you are seeing.

**Comment by pasin** [comment] 2015-10-21 06:43
I have reverted a fix that uses `CBLView.lastSequenceChangedAt` as it doesn't get implemented correctly. I fixed a cache issue when the changes are local change. @mastohhh, If you have time, please try with this new fix and see if you are still seeing context-not-updated issue.

**Comment by cflorion** [comment] 2015-10-21 11:48
(I'm @mastohhh's colleague)

We've tested your last commits and the problem is still here. The main context is not up-to-date. More over the performBlockAndWait: sometimes is blocking the device. The UI is stuck, as if mergeChangesFromContextDidSaveNotification: never ends.

**Comment by pasin** [comment] 2015-10-22 05:41
Updated:
1. I have reverted back to use performBlock: so the blocking issue should be fixed.
2. I did more experiments and found that using mergeChangesFromContextDidSaveNotification: alone did it job to merge changes to all specified contexts correctly. However this might not always work with NSFetchResultController that requires more fine grain notifications and etc to reflect the UI correctly from all changes. I have bought firing fault code back. I have made a few small optimization to the code.

@mastohhh  or @cflorion , could you please try it out and let me know? Thanks!

**Comment by pasin** [comment] 2015-10-22 18:34
Also I have created a new issue (#960) to improve the relationship cache.

**Comment by pasin** [comment] 2015-10-30 17:05
@mastohhh or @cflorion, any updates on this?

**Comment by cflorion** [comment] 2015-10-30 21:29
Sorry, I'll make the test. Which version of the CBLIS do I have to try ?
Thanks

**Comment by pasin** [comment] 2015-10-30 22:10
Please update your feature/issue_938_perf. Thanks!

**Closed** 2015-12-09 00:05 UTC
Labels: bug, core-data, in progress, performance, reproduce/investigate, size-large
