### ISSUE TITLE
Assertion failure in CBL_Revision

### ISSUE THREAD

**Issue by jordanpwood** [couchbase/couchbase-lite-ios#1478] opened 2016-10-06 22:47 UTC
I've just upgraded the version of couchbase that my app uses from 1.2.1 to 1.3.1, and now my tests which used to work don't.  I'm getting the following assertion failure out of CBL_Revision:
`2016-10-06 17:03:53.646 BrowZine[51843:2879247] *** ASSERTION FAILED: !revID || [revID isKindOfClass: [CBL_RevID class]]`
`2016-10-06 17:03:53.647 BrowZine[51843:2879247] *** Assertion failure in -[CBL_Revision initWithDocID:revID:deleted:](), /Users/jenkins/jenkins/workspace/couchbase-lite-ios-builds/couchbase-lite-ios-community/Source/CBL_Revision.m:45`

There's a gist of the output from this test with database logging enabled:  https://gist.github.com/jordanpwood/eee4c2f58e38c30f99c9dc9904ad9a72

So far it seems that this problem is only in my tests, not in my regularly functioning app.

---
- Version:   Couchbase Lite 1.3.1
- Client OS: iOS 10.0
- Server:    N/A

**Comment by snej** [comment] 2016-10-07 22:16
I _really_ need a backtrace of this, to track down where it comes from. Can you get that?

**Comment by jordanpwood** [comment] 2016-10-10 17:16
Is this what you want?  

https://gist.github.com/jordanpwood/98f9f1fec6875f82c48f1f2f0cce750f

This is from a different failing test than the first.

**Comment by jordanpwood** [comment] 2016-10-10 17:22
Actually, here's the output when that one test is run in isolation, the other output was it failing after several other test had had failing assertions:

https://gist.github.com/jordanpwood/eaf1ad45d2056247fa4478f1506abb19

**Comment by snej** [comment] 2016-10-10 17:42
Yup, that's what I wanted. Will take a look.

**Comment by jordanpwood** [comment] 2016-10-27 13:14
Any news on this issue, Jens?  I have to decide whether I can use versions 1.3's ability to expire documents, or whether I have to write my own expiration and cleanup code for a product which has a December release date.

**Comment by snej** [comment] 2016-11-03 04:18
`2016-10-10 12:19:38.425 BrowZine[42270:6443981] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: 'CBL_TreeRevID required, but got CBL_TreeRevID 0x61800001da80'`
That error is very, very strange; note that the required and actual class names are the same. That implies there are two classes with the same name, which should be impossible'

**Comment by snej** [comment] 2016-11-03 04:20
The first exception makes more sense, but I'll have to dig around in those methods to see where the problem stems from.
```
12:19:38.417‖ WARNING: Exception caught in CBLDatabase transaction:
	!revID || [revID isKindOfClass: [CBL_RevID class]]
	5   BrowZine                            0x0000000109294bd4 -[CBL_Revision initWithDocID:revID:deleted:body:] + 0
	6   BrowZine                            0x0000000109348896 __103-[CBL_SQLiteStorage addDocID:prevRevID:properties:deleting:allowConflict:validationBlock:status:error:]_block_invoke + 991
	7   BrowZine                            0x00000001093426eb -[CBL_SQLiteStorage inTransaction:] + 334
	8   BrowZine                            0x0000000109342817 -[CBL_SQLiteStorage inOuterTransaction:] + 141
	9   BrowZine                            0x00000001093482c5 -[CBL_SQLiteStorage addDocID:prevRevID:properties:deleting:allowConflict:validationBlock:status:error:] + 769
	10  BrowZine                            0x000000010930ad73 -[CBLDatabase(Insertion) putDocID:properties:prevRevisionID:allowConflict:source:status:error:] + 1299
	11  BrowZine                            0x00000001092cecf6 -[CBLDocument putProperties:prevRevID:allowConflict:error:] + 197
	12  BrowZine                            0x00000001092d33c9 -[CBLUnsavedRevision save:] + 113
	13  BrowZine                            0x00000001092cee66 -[CBLDocument update:error:] + 122
```

**Comment by snej** [comment] 2016-11-03 04:33
In that backtrace, the offending revID object comes all the way from `-[CBLUnsavedRevision save:]`, where it's generated by `_parentRevID.cbl_asRevID`, which always returns a `CBL_TreeRevID`. So I don't see how this could fail.

Can you reproduce this? If you can break at the point of the assertion-failure exception it would be really, really interesting to see what the offending `CBL_RevID` object looks like.

**Comment by snej** [comment] 2016-11-03 04:49
Do you have two copies of CBL in your app? This could happen if your app contains a shared library (like an extension) and you've linked the static CBL into both the app and your library. That could cause Really Bad Stuff to happen since you end up with two different sets of classes, globals, etc.

**Comment by zygoat** [comment] 2016-11-03 18:17
I discovered the same problem as @jordanpwood immediately upon upgrading from 1.2.1 to 1.3.1, so I was glad to have found this report.

Indeed, we have CBL duplicately-linked in our app right now (it's a known condition that you might recall me musing about on the mailing list a couple months ago). We have an action extension in the app, along with an embedded framework that's linked by both the extension and the app proper, and given that CBL is distributed by CocoaPods as a pre-built static library we've had to tolerate the duplication.

**Comment by jordanpwood** [comment] 2016-11-18 02:47
This problem is in a test, so the test bundle makes couchbase calls to setup a database, then it runs code in the app bundle which also makes couchbase calls.  Could that cause the issue you're thinking of?  These tests work with the 1.2.1 version of couchbase.

I'd be happy to test a dynamically linked version of the couchbase framework.

**Comment by pasin** [comment] 2016-12-19 01:35
@jordanpwood To build dynamic framework, you can run archive on `CBL iOS Framework - Carthage` scheme.

**Comment by pasin** [comment] 2016-12-28 21:55
I'm closing the issue as the issue seems to be caused by having multiple CBL in the application. We could reopen the issue if it's otherwise.

**Closed by pasin** 2016-12-28 21:55 UTC
Labels: backlog, needsmoreinfo, P3: low
