### ISSUE TITLE
Cannot build with Xcode 11.4

### ISSUE THREAD

**Issue by keithcml** [couchbase/couchbase-lite-ios#2628] opened 2020-04-14 12:57 UTC
**Describe the bug**
I try to build the framework locally but fails

**To Reproduce**
1. git clone repo and branch out to tag 2.7.0
2. follow build guidelines and run build_framework.sh
3. build fail

**Logs** 
RegisterExecutionPolicyException /Users/mingloanchan/Library/Developer/Xcode/DerivedData/CouchbaseLite-agruurmufuvuewgkezfugcmzzroj/Build/Products/Release-iphoneos/CouchbaseLiteSwift.framework (in target 'CBL Swift' from project 'CouchbaseLite')
    cd /Users/mingloanchan/Documents/github/GOGOVAN/couchbase-lite-ios
    builtin-RegisterExecutionPolicyException /Users/mingloanchan/Library/Developer/Xcode/DerivedData/CouchbaseLite-agruurmufuvuewgkezfugcmzzroj/Build/Products/Release-iphoneos/CouchbaseLiteSwift.framework
note: Execution policy exception registration failed and was skipped: Error Domain=NSPOSIXErrorDomain Code=1 "Operation not permitted" (in target 'CBL Swift' from project 'CouchbaseLite')

Touch /Users/mingloanchan/Library/Developer/Xcode/DerivedData/CouchbaseLite-agruurmufuvuewgkezfugcmzzroj/Build/Products/Release-iphoneos/CouchbaseLiteSwift.framework (in target 'CBL Swift' from project 'CouchbaseLite')
    cd /Users/mingloanchan/Documents/github/GOGOVAN/couchbase-lite-ios
    /usr/bin/touch -c /Users/mingloanchan/Library/Developer/Xcode/DerivedData/CouchbaseLite-agruurmufuvuewgkezfugcmzzroj/Build/Products/Release-iphoneos/CouchbaseLiteSwift.framework

** BUILD FAILED **

**Comment by jayahariv** [comment] 2020-04-14 21:42
Did you try whitelist your Terminal in the `Settings > Security & Privacy > Privacy`?

https://forums.developer.apple.com/thread/124529

**Comment by jayahariv** [comment] 2020-04-16 17:09
@keithcml are you able to try this?

**Comment by keithcml** [comment] 2020-04-17 11:37
still cannot with same error

**Comment by jayahariv** [comment] 2020-04-22 22:59
tracking ticket > https://issues.couchbase.com/browse/CBL-899

**Comment by jayahariv** [comment] 2020-07-22 18:54
This issue seems to be not able to reproduce now, probably fixed with other fixes may be? But i was able to see a build failure in 2.7.0, which was already taken care in 2.7.1 https://github.com/couchbase/couchbase-lite-core/commit/09cf84429fae16df7c7f25793ed157210fa1be78

Seems like the attached logs messages are also not helping with the exact reason, its only some warnings just before the build failed, probably the real reason might be printed far above these messages. Or may be you can see the failed command after the Build failed message. 

Closing for now, if you are still facing issue, please feel to reopen the issue with more logs pointing to exact failure

**Closed by jayahariv** 2020-07-22 18:54 UTC
Labels: triaged
