### ISSUE TITLE
TodoLite showing wrong list when deleting tasks

### ISSUE THREAD

**Issue by sethrosetter** [couchbase/couchbase-lite-ios#1370] opened 2016-07-18 23:59 UTC
Using ForestDB 1.3.0-49,

--------
* Version:   ForestDB 1.3.0-49
* Client OS: iOS
* Server:    sync_gateway + CBS

Steps to reproduce using TodoLite (f50a016a81db512f509487a1983d2160d88cfeb8):
- Create a list
- Create a task
- Delete a task

- Expected (the list should should be empty)
- Seeing items from another list

**Comment by snej** [comment] 2016-07-19 00:46
Here's some logging I added to ToDoLite that shows that the query row being returned is totally not in the key range:
```
2016-07-18 17:42:40.882180 ToDoLite[7082:2740180] Task list: -------- startKey=(
    "-QO-tmGXBv-jkIYT3xusTWT",
        {
    }
), endKey=(
    "-QO-tmGXBv-jkIYT3xusTWT"
)
2016-07-18 17:42:40.882461 ToDoLite[7082:2740180] 	CBLQueryRow[key=["-mn_nm1SyVvyusU37LSlUQa","2016-07-19T00:42:38.604Z"]; value={"list_id":"-mn_nm1SyVvyusU37LSlUQa","title":"item2","_id":"-It9u3_7an9o1bd471ruNM6","type":"task","_rev":"1-3558ca10fdd46bb16a370c9ea7f9c920","created_at":"2016-07-19T00:42:38.604Z"}; id=-It9u3_7an9o1bd471ruNM6]
```

**Comment by sethrosetter** [comment] 2016-07-19 00:47
Easiest way to repro
- Create 2 lists
- Create 1 task per list
- Delete a task from the second list

Expected: You should see no task
Actual: You will see (not always) the task from the first list.

**Comment by snej** [comment] 2016-07-19 04:02
I created a unit test that does the same thing programmatically and reproduces the problem. Then I added some temporary assertions in CBForest that check that the keys being returned by the ForestDB iterator are within the requested range — and this test fails those assertions. So this definitely looks like a ForestDB iterator bug.

**Comment by snej** [comment] 2016-07-19 04:36
Filed ForestDB issue as [MB-20196](https://issues.couchbase.com/browse/MB-20196)

**Comment by snej** [comment] 2016-07-19 21:31
I have a workaround that fixes the manifestations of this bug that we've seen (including the test case I wrote), but I'm unsure whether it will work in all situations since I don't know the full effects of the bug. The workaround will at least not cause any regressions since it only triggers when the fdb_iterator illegally returns an out-of-range key.

It's checked in on a local branch; I'm waiting for an update from the ForestDB team before I commit it, since if they can fix the bug soon that would be preferable.

**Closed** 2016-07-20 18:06 UTC
Labels: bug, f: Query, forestdb, release-prep, S1: showstopper
