### ISSUE TITLE
Problem replicating to Cloudant when several revisions of a document are created quickly

### ISSUE THREAD

**Issue by jordanpwood** [couchbase/couchbase-lite-ios#1116] opened 2016-02-12 14:42 UTC
I have a document which, for historical reasons, gets saved 4 times, creating 4 distinct revisions in just a few milliseconds.  While doing this, I have continuous push and pull replications to Cloudant running.  The first revision is pushed to Cloudant, but the other three fail to get pushed until the next attempt at replication, at which time they are all pushed successfully.  I have reproduced this problem with both Couchbase lite 1.1.1 and 1.2.  

Here are logs of the 2 attempts to push the changes, the "Saving bookcase ..." lines are just before each revision is created and put in the DB.  

Log of the first push/pull attempt:
```
2016-02-12 07:45:02:153 BrowZine[37475:711b] Saving bookcase 0 with 5 journals
07:45:02.156‖ Sync: CBLRestPusher[https://couchClient:*****@browzine.cloudant.com:443/user-3111fc40-d0d2-11e5-b36b-2776274391bb] Progress: set active = 1
2016-02-12 07:45:02:156 BrowZine[37475:711b] Saving bookcase 1 with 4 journals
2016-02-12 07:45:02:159 BrowZine[37475:711b] Saving bookcase 2 with 7 journals
2016-02-12 07:45:02:161 BrowZine[37475:711b] Saving bookcase 3 with 0 journals
07:45:02.164‖ Sync: CBLReplication[to https://couchClient:*****@browzine.cloudant.com:443/user-3111fc40-d0d2-11e5-b36b-2776274391bb]: active, progress = 0 / 0, err: (null)
2016-02-12 07:45:02:165 BrowZine[37475:607] Saved bookcase 0
2016-02-12 07:45:02:166 BrowZine[37475:607] Saved bookcase 1
2016-02-12 07:45:02:166 BrowZine[37475:607] Saved bookcase 2
2016-02-12 07:45:02:166 BrowZine[37475:607] Saved bookcase 3
07:45:02.421‖ Sync: CBLRestPusher[https://couchClient:*****@browzine.cloudant.com:443/user-3111fc40-d0d2-11e5-b36b-2776274391bb]: Sending 1 revisions
07:45:02.422‖ Sync: CBLReplication[to https://couchClient:*****@browzine.cloudant.com:443/user-3111fc40-d0d2-11e5-b36b-2776274391bb]: active, progress = 0 / 1, err: (null)
07:45:02.559‖ Sync: CBLRestPusher[https://couchClient:*****@browzine.cloudant.com:443/user-3111fc40-d0d2-11e5-b36b-2776274391bb] Progress: 1 / 1
07:45:02.559‖ Sync: CBLReplication[to https://couchClient:*****@browzine.cloudant.com:443/user-3111fc40-d0d2-11e5-b36b-2776274391bb]: active, progress = 1 / 1, err: (null)
07:45:02.561‖ Sync: CBLRestPuller[https://couchClient:*****@browzine.cloudant.com:443/user-3111fc40-d0d2-11e5-b36b-2776274391bb] Progress: set active = 1
07:45:02.561‖ Sync: CBLReplication[from https://couchClient:*****@browzine.cloudant.com:443/user-3111fc40-d0d2-11e5-b36b-2776274391bb]: active, progress = 0 / 2, err: (null)
2016-02-12 07:45:02:561 BrowZine[37475:711b] Couchbase pull replication changed status from 2 to 3
07:45:02.563‖ Sync: CBLRestPuller[https://couchClient:*****@browzine.cloudant.com:443/user-3111fc40-d0d2-11e5-b36b-2776274391bb] queued 1 remote revisions from seq=52-g1AAAAKCeJyd0UEOgjAQBdAGTPQWunCNpYW2ruQm2nZogCAkBNd6E72J3kRvghVMiDvL5k_STN5v2hIhtMh8QGtQum7SBBQN2ixvIG_qCuMw0GV9Alm1QZW2pd32JFLLruuKzJeboz2YR0IZTcWfhluZWtlUu77PNg99hNGQUEco-UD7L-T3kOIpCwEcocMHOv_cSHCQJjZuUDWziS52WOs6YgyLKCZ6CnYbsPuIEQGcMzkFewzYc8S4sR-toynYa8D6N_N6TG4Jwyos3jcnxrY (0 in bulk, 1 individually)
07:45:02.564‖ Sync: CBLReplication[from https://couchClient:*****@browzine.cloudant.com:443/user-3111fc40-d0d2-11e5-b36b-2776274391bb]: active, progress = 1 / 2, err: (null)
07:45:02.709‖ Sync: CBLRestPuller[https://couchClient:*****@browzine.cloudant.com:443/user-3111fc40-d0d2-11e5-b36b-2776274391bb] inserted 1 revs in 0.013 sec (79.0/sec)
07:45:02.709‖ Sync: CBLRestPuller[https://couchClient:*****@browzine.cloudant.com:443/user-3111fc40-d0d2-11e5-b36b-2776274391bb] Progress: set active = 0
07:45:02.709‖ Sync: CBLRestPuller[https://couchClient:*****@browzine.cloudant.com:443/user-3111fc40-d0d2-11e5-b36b-2776274391bb] Progress: 2 / 2
07:45:02.727‖ Sync: CBLReplication[from https://couchClient:*****@browzine.cloudant.com:443/user-3111fc40-d0d2-11e5-b36b-2776274391bb]: idle, progress = 2 / 2, err: (null)
2016-02-12 07:45:02:727 BrowZine[37475:b36f] Couchbase pull replication changed status from 3 to 2
2016-02-12 07:45:02:727 BrowZine[37475:b36f] Pull replication took 166.317940 ms
07:45:09.183‖ Sync: CBLRestPusher[https://couchClient:*****@browzine.cloudant.com:443/user-3111fc40-d0d2-11e5-b36b-2776274391bb] checkpointing sequence=121
07:45:13.983‖ Sync: CBLRestPuller[https://couchClient:*****@browzine.cloudant.com:443/user-3111fc40-d0d2-11e5-b36b-2776274391bb] checkpointing sequence=52-g1AAAAKCeJyd0UEOgjAQBdAGTPQWunCNpYW2ruQm2nZogCAkBNd6E72J3kRvghVMiDvL5k_STN5v2hIhtMh8QGtQum7SBBQN2ixvIG_qCuMw0GV9Alm1QZW2pd32JFLLruuKzJeboz2YR0IZTcWfhluZWtlUu77PNg99hNGQUEco-UD7L-T3kOIpCwEcocMHOv_cSHCQJjZuUDWziS52WOs6YgyLKCZ6CnYbsPuIEQGcMzkFewzYc8S4sR-toynYa8D6N_N6TG4Jwyos3jcnxrY
07:45:14.043‖ Sync: CBLRestPusher[https://couchClient:*****@browzine.cloudant.com:443/user-3111fc40-d0d2-11e5-b36b-2776274391bb]: Sending 3 revisions
07:45:14.044‖ Sync: CBLReplication[to https://couchClient:*****@browzine.cloudant.com:443/user-3111fc40-d0d2-11e5-b36b-2776274391bb]: active, progress = 1 / 4, err: (null)
07:45:14.105‖ Sync: CBLRestPusher[https://couchClient:*****@browzine.cloudant.com:443/user-3111fc40-d0d2-11e5-b36b-2776274391bb] saved remote checkpoint '121' (_rev=0-37)
07:45:14.161‖ Sync: CBLRestPusher[https://couchClient:*****@browzine.cloudant.com:443/user-3111fc40-d0d2-11e5-b36b-2776274391bb]: Sending 1 revisions
07:45:14.161‖ Sync: CBLReplication[to https://couchClient:*****@browzine.cloudant.com:443/user-3111fc40-d0d2-11e5-b36b-2776274391bb]: active, progress = 1 / 5, err: (null)
07:45:14.167‖ CBLRemoteJSONRequest[POST https://couchClient:*****@browzine.cloudant.com:443/user-3111fc40-d0d2-11e5-b36b-2776274391bb/_bulk_docs]: Got error Error Domain=CBLHTTP Code=500 "500 internal server error" UserInfo={NSURL=https://couchClient:[redacted]@browzine.cloudant.com:443/user-3111fc40-d0d2-11e5-b36b-2776274391bb/_bulk_docs, NSLocalizedFailureReason=internal server error, NSLocalizedDescription=500 internal server error}
07:45:14.204‖ Sync: CBLRestPuller[https://couchClient:*****@browzine.cloudant.com:443/user-3111fc40-d0d2-11e5-b36b-2776274391bb] saved remote checkpoint '52-g1AAAAKCeJyd0UEOgjAQBdAGTPQWunCNpYW2ruQm2nZogCAkBNd6E72J3kRvghVMiDvL5k_STN5v2hIhtMh8QGtQum7SBBQN2ixvIG_qCuMw0GV9Alm1QZW2pd32JFLLruuKzJeboz2YR0IZTcWfhluZWtlUu77PNg99hNGQUEco-UD7L-T3kOIpCwEcocMHOv_cSHCQJjZuUDWziS52WOs6YgyLKCZ6CnYbsPuIEQGcMzkFewzYc8S4sR-toynYa8D6N_N6TG4Jwyos3jcnxrY' (_rev=0-45)
07:45:14.222‖ Sync: CBLReplication[to https://couchClient:*****@browzine.cloudant.com:443/user-3111fc40-d0d2-11e5-b36b-2776274391bb]: active, progress = 2 / 5, err: (null)
07:45:14.227‖ Sync: CBLRestPuller[https://couchClient:*****@browzine.cloudant.com:443/user-3111fc40-d0d2-11e5-b36b-2776274391bb] Progress: set active = 1
07:45:14.227‖ Sync: CBLReplication[from https://couchClient:*****@browzine.cloudant.com:443/user-3111fc40-d0d2-11e5-b36b-2776274391bb]: active, progress = 2 / 4, err: (null)
2016-02-12 07:45:14:227 BrowZine[37475:711b] Couchbase pull replication changed status from 2 to 3
07:45:14.228‖ Sync: CBLRestPuller[https://couchClient:*****@browzine.cloudant.com:443/user-3111fc40-d0d2-11e5-b36b-2776274391bb] Progress: 4 / 4
07:45:14.228‖ Sync: CBLRestPuller[https://couchClient:*****@browzine.cloudant.com:443/user-3111fc40-d0d2-11e5-b36b-2776274391bb] Progress: set active = 0
07:45:14.229‖ Sync: CBLReplication[from https://couchClient:*****@browzine.cloudant.com:443/user-3111fc40-d0d2-11e5-b36b-2776274391bb]: idle, progress = 4 / 4, err: (null)
2016-02-12 07:45:14:229 BrowZine[37475:42f] Couchbase pull replication changed status from 3 to 2
2016-02-12 07:45:14:229 BrowZine[37475:42f] Pull replication took 2.116919 ms
2016-02-12 07:45:14.545 BrowZine[37475:7088565] calling allBookcasesWithResult with manager <BZCouchLiveQueryManager: 0x7fadec90df40>
07:45:18.290‖ CBLRemoteJSONRequest[POST https://couchClient:*****@browzine.cloudant.com:443/user-3111fc40-d0d2-11e5-b36b-2776274391bb/_bulk_docs]: Got error Error Domain=CBLHTTP Code=500 "500 internal server error" UserInfo={NSURL=https://couchClient:[redacted]@browzine.cloudant.com:443/user-3111fc40-d0d2-11e5-b36b-2776274391bb/_bulk_docs, NSLocalizedFailureReason=internal server error, NSLocalizedDescription=500 internal server error}
07:45:19.229‖ Sync: CBLRestPuller[https://couchClient:*****@browzine.cloudant.com:443/user-3111fc40-d0d2-11e5-b36b-2776274391bb] checkpointing sequence=53-g1AAAAKCeJyd0U0OgjAQBeAGTPQWunBN-gNtXclNtO1AgGBJCK71JnoTvYneBAuYEHfC5k3STL7XtCVCaJX5gLagTVUnMWgWNFleQ15XFmMSmLI6g7JNYJOmdNueQnrdtm2R-Qqf3MEylDo1TP5pTCvTG5d63_e55qGPckYomwjFHXT4Qn4PaZFwAjAROnbQ5edGUoBKo3QaZBcu0dUNZ91GjGMZRtTMwe4D9hgxKkEIruZgzwF7jZhI3UebcA72HrD-zbweUzvKsSbFBzlrxrc
07:45:19.289‖ Sync: CBLRestPuller[https://couchClient:*****@browzine.cloudant.com:443/user-3111fc40-d0d2-11e5-b36b-2776274391bb] saved remote checkpoint '53-g1AAAAKCeJyd0U0OgjAQBeAGTPQWunBN-gNtXclNtO1AgGBJCK71JnoTvYneBAuYEHfC5k3STL7XtCVCaJX5gLagTVUnMWgWNFleQ15XFmMSmLI6g7JNYJOmdNueQnrdtm2R-Qqf3MEylDo1TP5pTCvTG5d63_e55qGPckYomwjFHXT4Qn4PaZFwAjAROnbQ5edGUoBKo3QaZBcu0dUNZ91GjGMZRtTMwe4D9hgxKkEIruZgzwF7jZhI3UebcA72HrD-zbweUzvKsSbFBzlrxrc' (_rev=0-46)
07:45:26.412‖ CBLRemoteJSONRequest[POST https://couchClient:*****@browzine.cloudant.com:443/user-3111fc40-d0d2-11e5-b36b-2776274391bb/_bulk_docs]: Got error Error Domain=CBLHTTP Code=500 "500 internal server error" UserInfo={NSURL=https://couchClient:[redacted]@browzine.cloudant.com:443/user-3111fc40-d0d2-11e5-b36b-2776274391bb/_bulk_docs, NSLocalizedFailureReason=internal server error, NSLocalizedDescription=500 internal server error}
07:45:26.412‖ Sync: CBLRestPusher[https://couchClient:*****@browzine.cloudant.com:443/user-3111fc40-d0d2-11e5-b36b-2776274391bb] Progress: set error = 500 internal server error
07:45:26.412‖ Sync: CBLRestPusher[https://couchClient:*****@browzine.cloudant.com:443/user-3111fc40-d0d2-11e5-b36b-2776274391bb] Progress: 5 / 5
07:45:26.412‖ Sync: CBLRestPusher[https://couchClient:*****@browzine.cloudant.com:443/user-3111fc40-d0d2-11e5-b36b-2776274391bb] Progress: set active = 0
07:45:26.413‖ Sync: CBLRestPusher[https://couchClient:*****@browzine.cloudant.com:443/user-3111fc40-d0d2-11e5-b36b-2776274391bb]: Failed to xfer 1 revisions; will retry in 60 sec
07:45:26.413‖ Sync: CBLReplication[to https://couchClient:*****@browzine.cloudant.com:443/user-3111fc40-d0d2-11e5-b36b-2776274391bb]: idle, progress = 5 / 5, err: 500 internal server error
```

Here is the second, successful retry attempt:
```
07:46:26.416‖ Sync: CBLRestPusher[https://couchClient:*****@browzine.cloudant.com:443/user-3111fc40-d0d2-11e5-b36b-2776274391bb] RETRYING, to transfer missed revisions...
07:46:26.416‖ Sync: CBLRestPusher[https://couchClient:*****@browzine.cloudant.com:443/user-3111fc40-d0d2-11e5-b36b-2776274391bb] Progress: set error = (null)
07:46:26.416‖ Sync: CBLRestPusher[https://couchClient:*****@browzine.cloudant.com:443/user-3111fc40-d0d2-11e5-b36b-2776274391bb] Progress: set active = 1
07:46:26.417‖ Sync: CBLReplication[to https://couchClient:*****@browzine.cloudant.com:443/user-3111fc40-d0d2-11e5-b36b-2776274391bb]: active, progress = 5 / 5, err: (null)
07:46:26.694‖ Sync: CBLRestPusher[https://couchClient:*****@browzine.cloudant.com:443/user-3111fc40-d0d2-11e5-b36b-2776274391bb]: Replicating from lastSequence=121
07:46:26.804‖ Sync: CBLRestPusher[https://couchClient:*****@browzine.cloudant.com:443/user-3111fc40-d0d2-11e5-b36b-2776274391bb]: Sending 1 revisions
07:46:26.805‖ Sync: CBLReplication[to https://couchClient:*****@browzine.cloudant.com:443/user-3111fc40-d0d2-11e5-b36b-2776274391bb]: active, progress = 5 / 6, err: (null)
07:46:26.951‖ Sync: CBLRestPusher[https://couchClient:*****@browzine.cloudant.com:443/user-3111fc40-d0d2-11e5-b36b-2776274391bb] Progress: 6 / 6
07:46:26.951‖ Sync: CBLRestPusher[https://couchClient:*****@browzine.cloudant.com:443/user-3111fc40-d0d2-11e5-b36b-2776274391bb] Progress: set active = 0
07:46:26.951‖ Sync: CBLReplication[to https://couchClient:*****@browzine.cloudant.com:443/user-3111fc40-d0d2-11e5-b36b-2776274391bb]: idle, progress = 6 / 6, err: (null)
07:46:26.952‖ Sync: CBLRestPuller[https://couchClient:*****@browzine.cloudant.com:443/user-3111fc40-d0d2-11e5-b36b-2776274391bb] Progress: set active = 1
07:46:26.952‖ Sync: CBLReplication[from https://couchClient:*****@browzine.cloudant.com:443/user-3111fc40-d0d2-11e5-b36b-2776274391bb]: active, progress = 4 / 6, err: (null)
2016-02-12 07:46:26:952 BrowZine[37475:5a3f] Couchbase pull replication changed status from 2 to 3
07:46:26.954‖ Sync: CBLRestPuller[https://couchClient:*****@browzine.cloudant.com:443/user-3111fc40-d0d2-11e5-b36b-2776274391bb] Progress: 6 / 6
07:46:26.954‖ Sync: CBLRestPuller[https://couchClient:*****@browzine.cloudant.com:443/user-3111fc40-d0d2-11e5-b36b-2776274391bb] Progress: set active = 0
07:46:26.955‖ Sync: CBLReplication[from https://couchClient:*****@browzine.cloudant.com:443/user-3111fc40-d0d2-11e5-b36b-2776274391bb]: idle, progress = 6 / 6, err: (null)
2016-02-12 07:46:26:955 BrowZine[37475:b477] Couchbase pull replication changed status from 3 to 2
2016-02-12 07:46:26:955 BrowZine[37475:b477] Pull replication took 2.821922 ms
07:46:31.954‖ Sync: CBLRestPusher[https://couchClient:*****@browzine.cloudant.com:443/user-3111fc40-d0d2-11e5-b36b-2776274391bb] checkpointing sequence=126
07:46:31.955‖ Sync: CBLRestPuller[https://couchClient:*****@browzine.cloudant.com:443/user-3111fc40-d0d2-11e5-b36b-2776274391bb] checkpointing sequence=54-g1AAAAKCeJyd0UEOgjAQBdAGTPQWunBN2gJtXclNtO1AgCAkBNd6E72J3kRvgqU1Ie6EzZ-kmbzftBVCaJX7gLagdNOmCagw6PKihaJtaoxJoKvmDLLugjrtKrPtSaTWfd-XuS_JyRwsI6EyHYo_jWllamNS7W2faXZ9lIWEhhOhZIAOX8i3kOIpIwAToeMAXX5uJDjILM6mQfXCJLqaYazbiDEsopjqOdjdYY8RowI4Z3IO9nTYa8R4Zj5aR3Owt8Psm3kWkzvKsCLlBzuvxrg
07:46:32.016‖ Sync: CBLRestPusher[https://couchClient:*****@browzine.cloudant.com:443/user-3111fc40-d0d2-11e5-b36b-2776274391bb] saved remote checkpoint '126' (_rev=0-38)
07:46:32.184‖ Sync: CBLRestPuller[https://couchClient:*****@browzine.cloudant.com:443/user-3111fc40-d0d2-11e5-b36b-2776274391bb] saved remote checkpoint '54-g1AAAAKCeJyd0UEOgjAQBdAGTPQWunBN2gJtXclNtO1AgCAkBNd6E72J3kRvgqU1Ie6EzZ-kmbzftBVCaJX7gLagdNOmCagw6PKihaJtaoxJoKvmDLLugjrtKrPtSaTWfd-XuS_JyRwsI6EyHYo_jWllamNS7W2faXZ9lIWEhhOhZIAOX8i3kOIpIwAToeMAXX5uJDjILM6mQfXCJLqaYazbiDEsopjqOdjdYY8RowI4Z3IO9nTYa8R4Zj5aR3Owt8Psm3kWkzvKsCLlBzuvxrg' (_rev=0-47)
```

**Comment by jordanpwood** [comment] 2016-02-12 15:09
When I try 
```
curl -v https://couchClient:[redacted]@browzine.cloudant.com:443/user-3111fc40-d0d2-11e5-b36b-2776274391bb/_bulk_docs
```
I don't get a 500 response, like the log above seems to indicate, instead I get a 405:
```
*   Trying 169.54.45.158...
* Connected to browzine.cloudant.com (169.54.45.158) port 443 (#0)
* TLS 1.2 connection using TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256
* Server certificate: *.cloudant.com
* Server certificate: DigiCert SHA2 Secure Server CA
* Server certificate: DigiCert Global Root CA
* Server auth using Basic with user 'couchClient'
> GET /user-3111fc40-d0d2-11e5-b36b-2776274391bb/_bulk_docs HTTP/1.1
> Host: browzine.cloudant.com
> Authorization: Basic Y291Y2hDbGllbnQ6dENaeW5DNDVEa0h2T2tIMHhzcEM=
> User-Agent: curl/7.43.0
> Accept: */*
> 
< HTTP/1.1 405 Method Not Allowed
< X-Couch-Request-ID: 47b2e919e3
< Server: CouchDB/1.0.2 (Erlang OTP/17)
< Date: Fri, 12 Feb 2016 13:25:32 GMT
< Content-Type: text/plain;charset=utf-8
< Content-Length: 60
< Cache-Control: must-revalidate
< Allow: POST
< Strict-Transport-Security: max-age=31536000
< X-Content-Type-Options: nosniff;
< 
{"error":"method_not_allowed","reason":"Only POST allowed"}
* Connection #0 to host browzine.cloudant.com left intact
```

**Comment by snej** [comment] 2016-02-17 02:11
As you saw, this seems to be a Cloudant error; their server's returning a 500:
```
07:45:18.290‖ CBLRemoteJSONRequest[POST https://couchClient:*****@browzine.cloudant.com:443/user-3111fc40-d0d2-11e5-b36b-2776274391bb/_bulk_docs]: Got error Error Domain=CBLHTTP Code=500 "500 internal server error" UserInfo={NSURL=https://couchClient:[redacted]@browzine.cloudant.com:443/user-3111fc40-d0d2-11e5-b36b-2776274391bb/_bulk_docs, NSLocalizedFailureReason=internal server error, NSLocalizedDescription=500 internal server error}
```

Your curl command didn't work because `_bulk_docs` is a POST not a GET. And it's got a JSON request body containing the document data, so you can't really reproduce that request without having a trace of the full HTTP traffic during the replication.

If this is a Mac app, you can use the HTTPScoop app to capture the traffic. On iOS (or if you have to use HTTPS connections) you can use Charles Proxy.

**Comment by snej** [comment] 2016-02-26 00:27
Any update on this, Jordan? I'm assuming it's a Cloudant bug, but if it's still persisting I'd like to see what the actual HTTP response is, in case it has some interesting diagnostic info.

**Comment by jordanpwood** [comment] 2016-02-26 03:53
I'm sorry Jens, I haven't had a chance to circle back around to this
issue.  We are (hopefully!) days away from launching our couchDB-based
system, with 5 different codebases making a change over to this system.  I
changed my app to first build the document, then save it, so I'm not
hitting this case any more.  However, my colleague who is developing the
Android version of our app has reported the same type of problem using the
Android version of Couchbase Lite.  His problem seems to clear up fairly
quickly, and isn't causing problems which impact the user.

I plan on making a Node-based test which repeatedly saves the same article
over and over to Cloudant, to see if we still see this issue. I'll let you
know the results when I do!

Jordan

**Comment by snej** [comment] 2016-02-26 05:47
OK, thanks for the update! I'll close the issue. If you run into it again later, I suggest trying Cloudant tech support first, but if they point a finger at us, add a comment here and I'll re-open it.

**Closed by snej** 2016-02-26 05:47 UTC
