### ISSUE TITLE
2.0 - CocoaPods install fails

### ISSUE THREAD

**Issue by sethrosetter** [couchbase/couchbase-lite-ios#1696] opened 2017-04-05 00:23 UTC
--------
* Version:   2.0DB004
* Client OS: iOS
* Server:    N/A

Using the following PodFile
```
target 'TestPOC.Swift' do
  use_frameworks!
  pod 'CouchbaseLiteSwift', :git => 'https://github.com/couchbase/couchbase-lite-ios.git', :tag => '2.0DB004', :submodules => true
end
```

```
TestingPOC/TestPOC.Swift » pod install
Analyzing dependencies
Pre-downloading: `CouchbaseLiteSwift` from `https://github.com/couchbase/couchbase-lite-ios.git`, tag `2.0DB004`, submodules `true`
[!] /bin/bash -c
set -e
sh Scripts/prepare_cocoapods.sh "CBL ObjC"

Preparing CouchbaseLite framework ...
** BUILD FAILED **


The following build commands failed:
	CompileC /Users/sethrosetter/Library/Developer/Xcode/DerivedData/CouchbaseLite-cklyakruplevwndkguazqsybwmme/Build/Intermediates/blip_cpp.build/Release-iphoneos/blip_cpp.build/Objects-normal/armv7/Message.o src/blip/Message.cc normal armv7 c++ com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)
** BUILD FAILED **


The following build commands failed:
	CompileC /Users/sethrosetter/Library/Developer/Xcode/DerivedData/CouchbaseLite-cklyakruplevwndkguazqsybwmme/Build/Intermediates/blip_cpp.build/Release-appletvos/blip_cpp.build/Objects-normal/arm64/Message.o src/blip/Message.cc normal arm64 c++ com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)
** BUILD FAILED **


The following build commands failed:
	CompileC /Users/sethrosetter/Library/Developer/Xcode/DerivedData/CouchbaseLite-cklyakruplevwndkguazqsybwmme/Build/Intermediates/blip_cpp.build/Release/blip_cpp.build/Objects-normal/x86_64/Message.o src/blip/Message.cc normal x86_64 c++ com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)

TestingPOC/TestPOC.Swift »
```

**Comment by pasin** [comment] 2017-04-05 01:27
`sh Scripts/prepare_cocoapods.sh "CBL ObjC"` is weird. Seem like it is building ObjC for Swift.

**Comment by pasin** [comment] 2017-04-05 01:41
@sethrosetter I couldn't reproduce the issue. What is the pod version you are using?

**Comment by pasin** [comment] 2017-04-05 01:47
I believe the pod file that I use is the same as yours:

```
Pasins-MBP:swift pasin$ more Podfile
target 'Todo' do
  use_frameworks!
  pod 'CouchbaseLiteSwift', :git => 'https://github.com/couchbase/couchbase-lite-ios.git', :tag => '2.0DB004', :submodules => true
end
```

Result:
```
Pasins-MBP:swift pasin$ pod update
Update all pods
Updating local specs repositories

CocoaPods 1.2.1.beta.1 is available.
To update use: `sudo gem install cocoapods --pre`
[!] This is a test version we'd love you to try.

For more information, see https://blog.cocoapods.org and the CHANGELOG for this version at https://github.com/CocoaPods/CocoaPods/releases/tag/1.2.1.beta.1

Analyzing dependencies
Pre-downloading: `CouchbaseLiteSwift` from `https://github.com/couchbase/couchbase-lite-ios.git`, tag `2.0DB004`, submodules `true`


Downloading dependencies
Installing CouchbaseLiteSwift 2.0DB004 (was 2.0DB2)
Generating Pods project
Integrating client project
Sending stats
Pod installation complete! There is 1 dependency from the Podfile and 1 total pod installed.
```

**Comment by pasin** [comment] 2017-04-05 01:48
`pod install` also works.

**Comment by djpongh** [comment] 2017-04-14 21:44
Couldn't repro. Closing.

**Closed** 2017-04-14 21:45 UTC
