### ISSUE TITLE
Forest DB Linker error

### ISSUE THREAD

**Issue by msanilkumar2020** [couchbase/couchbase-lite-ios#1466] opened 2016-09-29 13:01 UTC
Hi,

We are getting below linker error if we add forest db library to our application.

If i integrate with sample app it is working fine, i tried even removing -load-all flag.

Please help me in resolving this linker error.

I am using CBL V - 1.3.1(From branch), even i tried with 1.3 version also we have same issue.

This issue is similar to below issue.
http://mobile-couchbase.narkive.com/Vpjh9cY5/forestdb-linker-errors-after-adding-libcblforestdbstorage-a

duplicate symbol _register_unicodesn_tokenizer in:
    /Users/iOS_Dev/Library/Developer/Xcode/DerivedData/InstaPoC-fadwenmppikdsrdqojnplirobqds/Build/Products/Debug-iphoneos/libCBLForestDBStorage.a(sqlite3_unicodesn_tokenizer.o)
    /Users/iOS_Dev/Library/Developer/Xcode/DerivedData/InstaPoC-fadwenmppikdsrdqojnplirobqds/Build/Products/Debug-iphoneos/libCouchbaseLite.a(sqlite3_unicodesn_tokenizer.o)
duplicate symbol _dutch_UTF_8_create_env in:
    /Users/iOS_Dev/Library/Developer/Xcode/DerivedData/InstaPoC-fadwenmppikdsrdqojnplirobqds/Build/Products/Debug-iphoneos/libCBLForestDBStorage.a(stem_UTF_8_dutch.o)
    /Users/iOS_Dev/Library/Developer/Xcode/DerivedData/InstaPoC-fadwenmppikdsrdqojnplirobqds/Build/Products/Debug-iphoneos/libCouchbaseLite.a(stem_UTF_8_dutch.o)
duplicate symbol _dutch_UTF_8_close_env in:
    /Users/iOS_Dev/Library/Developer/Xcode/DerivedData/InstaPoC-fadwenmppikdsrdqojnplirobqds/Build/Products/Debug-iphoneos/libCBLForestDBStorage.a(stem_UTF_8_dutch.o)
    /Users/iOS_Dev/Library/Developer/Xcode/DerivedData/InstaPoC-fadwenmppikdsrdqojnplirobqds/Build/Products/Debug-iphoneos/libCouchbaseLite.a(stem_UTF_8_dutch.o)
duplicate symbol _dutch_UTF_8_stem in:
    /Users/iOS_Dev/Library/Developer/Xcode/DerivedData/InstaPoC-fadwenmppikdsrdqojnplirobqds/Build/Products/Debug-iphoneos/libCBLForestDBStorage.a(stem_UTF_8_dutch.o)
    /Users/iOS_Dev/Library/Developer/Xcode/DerivedData/InstaPoC-fadwenmppikdsrdqojnplirobqds/Build/Products/Debug-iphoneos/libCouchbaseLite.a(stem_UTF_8_dutch.o)
duplicate symbol _hungarian_ISO_8859_1_create_env in:
    /Users/iOS_Dev/Library/Developer/Xcode/DerivedData/InstaPoC-fadwenmppikdsrdqojnplirobqds/Build/Products/Debug-iphoneos/libCBLForestDBStorage.a(stem_ISO_8859_1_hungarian.o)
    /Users/iOS_Dev/Library/Developer/Xcode/DerivedData/InstaPoC-fadwenmppikdsrdqojnplirobqds/Build/Products/Debug-iphoneos/libCouchbaseLite.a(stem_ISO_8859_1_hungarian.o)
duplicate symbol _hungarian_ISO_8859_1_close_env in:
    /Users/iOS_Dev/Library/Developer/Xcode/DerivedData/InstaPoC-fadwenmppikdsrdqojnplirobqds/Build/Products/Debug-iphoneos/libCBLForestDBStorage.a(stem_ISO_8859_1_hungarian.o)
    /Users/iOS_Dev/Library/Developer/Xcode/DerivedData/InstaPoC-fadwenmppikdsrdqojnplirobqds/Build/Products/Debug-iphoneos/libCouchbaseLite.a(stem_ISO_8859_1_hungarian.o)
duplicate symbol _hungarian_ISO_8859_1_stem in:
    /Users/iOS_Dev/Library/Developer/Xcode/DerivedData/InstaPoC-fadwenmppikdsrdqojnplirobqds/Build/Products/Debug-iphoneos/libCBLForestDBStorage.a(stem_ISO_8859_1_hungarian.o)
    /Users/iOS_Dev/Library/Developer/Xcode/DerivedData/InstaPoC-fadwenmppikdsrdqojnplirobqds/Build/Products/Debug-iphoneos/libCouchbaseLite.a(stem_ISO_8859_1_hungarian.o)
duplicate symbol _swedish_UTF_8_create_env in:
    /Users/iOS_Dev/Library/Developer/Xcode/DerivedData/InstaPoC-fadwenmppikdsrdqojnplirobqds/Build/Products/Debug-iphoneos/libCBLForestDBStorage.a(stem_UTF_8_swedish.o)
    /Users/iOS_Dev/Library/Developer/Xcode/DerivedData/InstaPoC-fadwenmppikdsrdqojnplirobqds/Build/Products/Debug-iphoneos/libCouchbaseLite.a(stem_UTF_8_swedish.o)
duplicate symbol _swedish_UTF_8_close_env in:
    /Users/iOS_Dev/Library/Developer/Xcode/DerivedData/InstaPoC-fadwenmppikdsrdqojnplirobqds/Build/Products/Debug-iphoneos/libCBLForestDBStorage.a(stem_UTF_8_swedish.o)
    /Users/iOS_Dev/Library/Developer/Xcode/DerivedData/InstaPoC-fadwenmppikdsrdqojnplirobqds/Build/Products/Debug-iphoneos/libCouchbaseLite.a(stem_UTF_8_swedish.o)
duplicate symbol _swedish_UTF_8_stem in:
    /Users/iOS_Dev/Library/Developer/Xcode/DerivedData/InstaPoC-fadwenmppikdsrdqojnplirobqds/Build/Products/Debug-iphoneos/libCBLForestDBStorage.a(stem_UTF_8_swedish.o)
    /Users/iOS_Dev/Library/Developer/Xcode/DerivedData/InstaPoC-fadwenmppikdsrdqojnplirobqds/Build/Products/Debug-iphoneos/libCouchbaseLite.a(stem_UTF_8_swedish.o)
duplicate symbol _dutch_ISO_8859_1_create_env in:
    /Users/iOS_Dev/Library/Developer/Xcode/DerivedData/InstaPoC-fadwenmppikdsrdqojnplirobqds/Build/Products/Debug-iphoneos/libCBLForestDBStorage.a(stem_ISO_8859_1_dutch.o)
    /Users/iOS_Dev/Library/Developer/Xcode/DerivedData/InstaPoC-fadwenmppikdsrdqojnplirobqds/Build/Products/Debug-iphoneos/libCouchbaseLite.a(stem_ISO_8859_1_dutch.o)
duplicate symbol _dutch_ISO_8859_1_close_env in:
    /Users/iOS_Dev/Library/Developer/Xcode/DerivedData/InstaPoC-fadwenmppikdsrdqojnplirobqds/Build/Products/Debug-iphoneos/libCBLForestDBStorage.a(stem_ISO_8859_1_dutch.o)
    /Users/iOS_Dev/Library/Developer/Xcode/DerivedData/InstaPoC-fadwenmppikdsrdqojnplirobqds/Build/Products/Debug-iphoneos/libCouchbaseLite.a(stem_ISO_8859_1_dutch.o)
duplicate symbol _dutch_ISO_8859_1_stem in:
    /Users/iOS_Dev/Library/Developer/Xcode/DerivedData/InstaPoC-fadwenmppikdsrdqojnplirobqds/Build/Products/Debug-iphoneos/libCBLForestDBStorage.a(stem_ISO_8859_1_dutch.o)
    /Users/iOS_Dev/Library/Developer/Xcode/DerivedData/InstaPoC-fadwenmppikdsrdqojnplirobqds/Build/Products/Debug-iphoneos/libCouchbaseLite.a(stem_ISO_8859_1_dutch.o)
duplicate symbol _sqlite3Fts3UnicodeSnTokenizer in:
    /Users/iOS_Dev/Library/Developer/Xcode/DerivedData/InstaPoC-fadwenmppikdsrdqojnplirobqds/Build/Products/Debug-iphoneos/libCBLForestDBStorage.a(fts3_unicodesn.o)
    /Users/iOS_Dev/Library/Developer/Xcode/DerivedData/InstaPoC-fadwenmppikdsrdqojnplirobqds/Build/Products/Debug-iphoneos/libCouchbaseLite.a(fts3_unicodesn.o)
duplicate symbol _english_UTF_8_create_env in:
    /Users/iOS_Dev/Library/Developer/Xcode/DerivedData/InstaPoC-fadwenmppikdsrdqojnplirobqds/Build/Products/Debug-iphoneos/libCBLForestDBStorage.a(stem_UTF_8_english.o)
    /Users/iOS_Dev/Library/Developer/Xcode/DerivedData/InstaPoC-fadwenmppikdsrdqojnplirobqds/Build/Products/Debug-iphoneos/libCouchbaseLite.a(stem_UTF_8_english.o)
duplicate symbol _english_UTF_8_close_env in:
    /Users/iOS_Dev/Library/Developer/Xcode/DerivedData/InstaPoC-fadwenmppikdsrdqojnplirobqds/Build/Products/Debug-iphoneos/libCBLForestDBStorage.a(stem_UTF_8_english.o)
    /Users/iOS_Dev/Library/Developer/Xcode/DerivedData/InstaPoC-fadwenmppikdsrdqojnplirobqds/Build/Products/Debug-iphoneos/libCouchbaseLite.a(stem_UTF_8_english.o)
duplicate symbol _english_UTF_8_stem in:
    /Users/iOS_Dev/Library/Developer/Xcode/DerivedData/InstaPoC-fadwenmppikdsrdqojnplirobqds/Build/Products/Debug-iphoneos/libCBLForestDBStorage.a(stem_UTF_8_english.o)
    /Users/iOS_Dev/Library/Developer/Xcode/DerivedData/InstaPoC-fadwenmppikdsrdqojnplirobqds/Build/Products/Debug-iphoneos/libCouchbaseLite.a(stem_UTF_8_english.o)
duplicate symbol _german_ISO_8859_1_create_env in:
    /Users/iOS_Dev/Library/Developer/Xcode/DerivedData/InstaPoC-fadwenmppikdsrdqojnplirobqds/Build/Products/Debug-iphoneos/libCBLForestDBStorage.a(stem_ISO_8859_1_german.o)
    /Users/iOS_Dev/Library/Developer/Xcode/DerivedData/InstaPoC-fadwenmppikdsrdqojnplirobqds/Build/Products/Debug-iphoneos/libCouchbaseLite.a(stem_ISO_8859_1_german.o)
duplicate symbol _german_ISO_8859_1_close_env in:

**Comment by snej** [comment] 2016-09-29 16:39
>If i integrate with sample app it is working fine, i tried even removing -load-all flag.

Can you describe that in more detail? It sounds like the problem is triggered by using the `-all_load` linker flag. Did you turn that off in your app or just in the sample app?

**Comment by msanilkumar2020** [comment] 2016-09-30 04:19
Snej,

I have turned off -all_load in both sample app and also in our application, in sample app it is working not in our application.

Below are the linker flags i have enabled
-weak_framework
CoreFoundation
-weak_framework
UIKit
-weak_framework
AVFoundation
-weak_framework
CoreMedia
-weak-lSystem
-Obj-C
$(inherited)

**Comment by msanilkumar2020** [comment] 2016-10-04 13:03
Any update on this?

**Comment by pasin** [comment] 2016-10-04 17:47
@msanilkumar2020 do you build the binary yourself of download from couchbase.com website?

**Comment by msanilkumar2020** [comment] 2016-10-05 04:50
Initially i took it from release 1.3.1 library i had issue in compiling then i compiled myself CBL ForestDB Storage target by removing tokeniser.a library then it worked for me. It is better to have released libraries compared to taking library from branch.

**Comment by snej** [comment] 2016-10-06 04:45
Well, you seem to be the only person who's run into this issue, so since we don't understand it and can't reproduce it, and our initial guess (about `-all_load`) didn't work, I think you'll need to troubleshoot it yourself...

**Comment by jscubida** [comment] 2016-10-06 19:43
I was having this issue, too. I had to cherry-pick a commit because of [this issue](https://github.com/couchbase/couchbase-lite-ios/issues/1458) and compile CBL myself. Removing `-all_load` worked for me.

**Comment by pasin** [comment] 2016-12-17 00:53
@msanilkumar2020 are you still having the issue? 

Just in case, you are using cocoapods, you can use forestdb by doing the followings. 
```
pod 'couchbase-lite-ios', '1.3.1'
pod 'couchbase-lite-ios/ForestDB', '1.3.1'
```

As I couldn't reproduce the issue by either using cocoapods or installing downloaded binary, I'm not sure what the issue is. It seems to be related to the project configuration. You may create a simple project that reproduces the issue and post it here so I can take a look. I'm closing the issue now.

**Closed by pasin** 2016-12-17 00:53 UTC
Labels: Build, icebox, needsmoreinfo
