### ISSUE TITLE
SQLITE database is unreadable (err 5)

### ISSUE THREAD

**Issue by sivamani1818** [couchbase/couchbase-lite-ios#1979] opened 2017-12-12 11:19 UTC
We are not doing encryption, still i am getting error while trying to access the database.Please guide us.

[11/17 09:46:57:355][ 0x17006b840]Type-Database , Message-Created CBLManager[0x170110500 /var/mobile/Containers/Data/Application/161984A5-FED4-4906-931E-01F26EDC8794/Documents/PTXDataBase]
[11/17 09:46:57:355][ 0x174470480]Type-Database , Message-Opening <CBL_SQLiteStorage: 0x17427b400>
[11/17 09:46:57:359][ 0x174470480]Type-Database , Message-Open /var/mobile/Containers/Data/Application/161984A5-FED4-4906-931E-01F26EDC8794/Documents/PTXDataBase/ptxdata.cblite2/db.sqlite3 with SQLite (flags=6(null))
[11/17 09:46:57:361][ 0x17006b840]Type-Server , Message-CBL_RunLoopServer[0x170432d20] Starting server thread ...
[11/17 09:46:57:362][ 0x17006b840]Type-Database , Message-CBLManager[0x17410cb10 /var/mobile/Containers/Data/Application/161984A5-FED4-4906-931E-01F26EDC8794/Documents/PTXDataBase] created CBL_RunLoopServer[0x170432d20] (with CBLManager[0x170110500 /var/mobile/Containers/Data/Application/161984A5-FED4-4906-931E-01F26EDC8794/Documents/PTXDataBase])
[11/17 09:46:57:362][ 0x170476b40]Type-Server , Message-CBL_RunLoopServer[0x170432d20]: Server thread starting...
[11/17 09:46:57:431][ 0x17446c5c0]Type-Router , Message-  Runninf the router request on server thread

[11/17 09:46:57:432][ 0x170476b40]Type-Router , Message-GET http://lite.couchbase./ptxdata
	User-Agent: Mozilla/5.0 (iPhone; CPU iPhone OS 10_3_3 like Mac OS X) AppleWebKit/603.3.8 (KHTML, like Gecko) Mobile/14G60
	Accept: application/json
	Content-Type: application/json
[11/17 09:46:57:443][ 0x170476b40]Type-Database , Message-Opening CBLDatabase[<0x174159f40>ptxdata]
[11/17 09:46:57:443][ 0x170476b40]Type-Database , Message-Using CBL_SQLiteStorage for db at /var/mobile/Containers/Data/Application/161984A5-FED4-4906-931E-01F26EDC8794/Documents/PTXDataBase/ptxdata.cblite2; upgrade=0
[11/17 09:46:57:443][ 0x170476b40]Type-Database , Message-Opening <CBL_SQLiteStorage: 0x17446c4c0>
[11/17 09:46:57:443][ 0x170476b40]Type-Database , Message-Open /var/mobile/Containers/Data/Application/161984A5-FED4-4906-931E-01F26EDC8794/Documents/PTXDataBase/ptxdata.cblite2/db.sqlite3 with SQLite (flags=6(null))

[11/17 09:46:57:518][ 0x170476b40]Type-WARNING , Message-CBL_SQLiteStorage: database is unreadable (err 5) {at -[CBL_SQLiteStorage decryptWithKey:error:]:308}
[11/17 09:46:57:553][ 0x170476b40]Type-Router , Message-Response -- status=500, body=40 bytes
	Server: CouchbaseLite 08_003_00_01P-Debug unofficial: commit 
	Content-Type: application/json
[11/17 09:46:58:609][ 0x17446c5c0]Type-Router , Message-  Runninf the router request on server thread

--------
* Version:   1.4.1
* Client OS: iOS 10.3.3

**Comment by pasin** [comment] 2017-12-12 18:49
The error message (`database is unreadable`) could either mean that the database encryption key is not correct or the database is not readable at that time. For this case, the error code is 5 which is SQLITE_BUSY, which is weird because it happens when opening the database.

Can you provide more information about how the app got into this state or how to reproduce the issue?

**Comment by sivamani1818** [comment] 2017-12-13 05:07
App got crashed and then  launched the app.Tried to open the database and for that response received as 500

**Comment by sivamani1818** [comment] 2017-12-19 12:01
Attached the log file for reference.


[couch_logs_old.txt.zip](https://github.com/couchbase/couchbase-lite-ios/files/1571567/couch_logs_old.txt.zip)

**Comment by pasin** [comment] 2017-12-19 16:59
@sivamani1818, honestly I have never seen this issue before. If database is corrupted, the error code should be 11 (database disk image is malformed) instead of 5 (busy). 

A couple of things for debugging:

1. If you run the code with XCode, can you dump the thread when the issue happens? I'm wondering if the database file is locked by another process.

2. Try to get the database file and open it with any SQLite viewer to see if it's openable or not. This will ensure that the database file is not corrupted.

3. Does this happen all the time with a fresh installed app? If yes, you can try with CBL 1.4.0 to confirm if the issue happens only on 1.4.0.

4. Try to create a sample app that can reproduce the issue and share it here.

**Comment by sivamani1818** [comment] 2017-12-28 05:26
1.If you run the code with XCode, can you dump the thread when the issue happens? I'm wondering if the database file is locked by another process

--> It is reproduced in production not in debug mode.

2.Try to get the database file and open it with any SQLite viewer to see if it's openable or not. This will ensure that the database file is not corrupted.

--> sqlite is not corrupted and able to view the database.

3.Does this happen all the time with a fresh installed app? If yes, you can try with CBL 1.4.0 to confirm if the issue happens only on 1.4.0.

--> happened only twice.After crash try to login this issue happened.

Try to create a sample app that can reproduce the issue and share it here.
--> we are using Rest based Api to interact with database.

**Comment by pasin** [comment] 2018-01-03 01:54
With the database busy error, we really need to see how the database is being use on the other thread. The workaround I could think of is to do the retry after failure.

**Comment by snej** [comment] 2018-01-03 17:20
Very strange that `sqlite3_open` would fail with `SQLITE_BUSY`, especially when opening the _second_ connection to the db. I'll ask on the SQLite mailing list.

**Comment by snej** [comment] 2018-01-03 17:29
@sivamani1818: Are you including the full log output? All of the logs you've shown us seem to come from your app's log handler. What about messages produced by NSLog?

I'm asking because we register a SQLite database-busy handler that should log `*** SQLITE database busy` to NSLog, and I don't see that message in the logs you've sent. Please check.

**Comment by sivamani1818** [comment] 2018-01-04 05:14
**@snej** : Are you including the full log output? All of the logs you've shown us seem to come from your app's log handler. What about messages produced by NSLog?
 
 --> We have included the full logs.Yeah it is printed from app's log handler.We didn't capture Nslog because it is observed in production.

**Comment by snej** [comment] 2018-01-04 17:43
You should be able to capture NSLog output too; it's important not just for this, but for diagnosing issues involving system frameworks. An analytics library like Crashlytics should be able to take care of that.

**Comment by pasin** [comment] 2018-01-04 18:20
@snej I think the database busy error is not from `sqlite3_open`. The error happens when checking if the database is readable or not after opening the database. Here is the [code](https://github.com/couchbase/couchbase-lite-ios/blob/master/Source/CBL_SQLiteStorage.m#L297-L309) that prints out the error message.

@sivamani1818 is there another thread that is already using database that the same time?

**Comment by sivamani1818** [comment] 2018-01-05 04:50
No other thread is using the database at that time.

**Comment by pasin** [comment] 2018-01-16 18:18
I have found the followings from the SQLite [documentation](https://www.sqlite.org/wal.html) regarding the BUSY status in WAL mode. The last bullet point is likely what is happening here.

Cases where a query against a WAL-mode database can return SQLITE_BUSY include the following:

* If another database connection has the database mode open in exclusive locking mode then all queries against the database will return SQLITE_BUSY. Both Chrome and Firefox open their database files in exclusive locking mode, so attempts to read Chrome or Firefox databases while the applications are running will run into this problem, for example.

* When the last connection to a particular database is closing, that connection will acquire an exclusive lock for a short time while it cleans up the WAL and shared-memory files. If a second database tries to open and query the database while the first connection is still in the middle of its cleanup process, the second connection might get an SQLITE_BUSY error.

* If the last connection to a database crashed, then the first new connection to open the database will start a recovery process. An exclusive lock is held during recovery. So if a third database connection tries to jump in and query while the second connection is running recovery, the third connection will get an SQLITE_BUSY error.

**Comment by snej** [comment] 2018-01-16 23:42
That sounds likely. But we use a busy-handler callback, so the situation should be invisible; the callback will keep telling SQLite to retry. 

The callback seems to give up pretty quickly, though: after 10 attempts spaced over about 50ms. I think the `usleep` call in there (FMDatabase.m:262) should be changed to try for several seconds, with exponential backoff between attempts; something like `usleep(2000 * (1 << numberOfTries))`.

**Comment by pasin** [comment] 2018-01-17 18:30
@sivamani1818 I have updated the fmdb to increase the total wait time with the exponential backoff per @snej's suggestion. The total wait time of the max of 10 retries will increase from 55ms to 4092ms. The fix has been committed to the master branch. Please check that out. Thanks!

**Closed by pasin** 2018-01-17 18:30 UTC
Labels: ffc, needsmoreinfo
