### ISSUE TITLE
(CBL 1.3) Can't get destroy db to work

### ISSUE THREAD

**Issue by npomfret** [couchbase/couchbase-lite-ios#1414] opened 2016-08-22 14:01 UTC
Calling DELETE database from the rest api seems to hang forever.  My log file is full of warnings:

`WARNING: <CBL_Shared: 0x7fe6a2a81430>: Still waiting to -forgetDatabaseNamed: "pc_macmini_0_c5149e0b-d6a6-4d7c-9498-ed311552c663" {at -[CBL_Shared forgetDatabaseNamed:]:139}`

It worked until recently.  Not sure if my app is doing something to prevent it from working or not.  Any idea?

Here's the full log.

https://gist.github.com/npomfret/62d42a1a67801e4a560514a2f1afb103

**Comment by npomfret** [comment] 2016-08-22 14:17
The issue is something to do with replication.  My app creates a one-shot (non continuous) replication when it starts.  It looks like this is preventing delete database from completing.  Is there something I need to do to a replication to allow this to work?

I followed instructions [here](http://developer.couchbase.com/documentation/mobile/current/develop/guides/couchbase-lite/native-api/replication/index.html) but can't see anything specific.

**Comment by pasin** [comment] 2016-08-26 16:19
Possibly the same root cause : https://github.com/couchbase/couchbase-lite-ios/issues/1366.

**Comment by pasin** [comment] 2016-08-31 15:48
Simple single shot push and pull replicator doesn't seem to reproduce the issue. Probably something else was causing the issue.

>  I don't believe the replication has any work to do at all, but I don't see a notification when its in a state of kCBLReplicationStopped.

Does this always happen? Was it single-shot pull or push replicator?

**Comment by npomfret** [comment] 2016-08-31 18:39
It created both push and pull using the native API.  When I create them with the REST api there's no problem.  Maybe I'm creating them wrong?  Alway, I've worked around the issue now by using the REST API.  Close the issue for now if you like, I'll reopen if needed.

**Comment by pasin** [comment] 2016-09-14 20:54
Let me try with the Native API.

**Comment by snej** [comment] 2016-09-14 22:03
Closing as dup of #1366.

**Closed** 2016-09-14 22:03 UTC
Labels: bug, P3: low
