### ISSUE TITLE
Continous pull missing documents to pull

### ISSUE THREAD

**Issue by pradipvaghasiya** [couchbase/couchbase-lite-ios#1471] opened 2016-10-01 08:03 UTC
Continuous replication is missing some doc to pull. Doc is properly added to channel. This is not happening all the time. Sometimes Some devices get the doc some devices dont. The device which dint get particular revision gets next revision. 

Setup in different devices is exactly same with same build.

Killing the app and restarting (i. e. Restarting continuous replication ) does not work either. Once it is missed it is never pulled. only pulled on next revision.

I am using latest Couchbase lite and Sync Gateway 1.3.1 version. This is so indeterministic that I cant reproduce but this is happening now and then. Can someone please help?

[Logs missing Doc.txt](https://github.com/couchbase/couchbase-lite-ios/files/504158/Logs.missing.Doc.txt)

I have attached sync gateway  log. 

If you see log of doc id kamero%3Aconfig (kamero:config) in attached file,
There are 3 device with 3 facebook userid logged in
USER-1. 947051868695804
USER-2. 896498073737333
USER-3. 10153418908626890

Through admin rest api. doc (2nd revision) is stored 
`2016-09-28T17:12:03.091Z CRUD: Stored doc "kamero:config" / "2-41185508e93e96a1d501041767845352"`

USER-1 gets the 2nd rev. However other 2 devices don't get even though tried everything like relaunching.
`2016-09-28T17:12:12.322Z HTTP:  #11812: PUT /kamero/_local/e6a72326153c9eb58bc26688f83c6e60a7b63571  (as 947051868695804)
2016-09-28T17:12:12.353Z HTTP:  #11813: GET /kamero/kamero%3Aconfig?rev=2-41185508e93e96a1d501041767845352&revs=true&attachments=true&atts_since=%5B%221-b0c35fa9f4acc02f5a4e2ec2a12729f3%22%5D  (as 947051868695804)
`

Created revision 4
`2016-09-28T17:26:34.497Z CRUD: Stored doc "kamero:config" / "4-8e8978a6885339241adcd48ed9b892aa"`

All user get the revisions.
`
USER-1
2016-09-28T17:26:34.922Z HTTP:  #12257: GET /kamero/kamero%3Aconfig?rev=4-8e8978a6885339241adcd48ed9b892aa&revs=true&attachments=true&atts_since=%5B%223-a688b2c023f30000ffb23c19750f0df7%22%5D  (as 947051868695804)

USER-2
2016-09-28T17:26:53.081Z HTTP:  #12270: GET /kamero/_changes?feed=websocket  (as 10153418908626890)
2016-09-28T17:26:53.578Z HTTP:  #12271: GET /kamero/kamero%3Aconfig?rev=4-8e8978a6885339241adcd48ed9b892aa&revs=true&attachments=true&atts_since=%5B%223-a688b2c023f30000ffb23c19750f0df7%22%5D  (as 10153418908626890)

USER-3
2016-09-28T17:26:54.899Z HTTP:  #12274: GET /kamero/_changes?feed=websocket  (as 896498073737333)
2016-09-28T17:26:55.295Z HTTP:  #12275: GET /kamero/kamero%3Aconfig?rev=4-8e8978a6885339241adcd48ed9b892aa&revs=true&attachments=true&atts_since=%5B%223-a688b2c023f30000ffb23c19750f0df7%22%5D  (as 896498073737333)
`

All devices running same build and same setup. During changes between Revision 2 and Revision 4, nothing changed from client side at all. Still rev 4 pulled by all device and Rev2 by only 1.

All devices are > iOS 10.

---
- Version:   1.3.1
- Client OS: iOS 10
- Server:    Sync Gateway 1.3.1

**Comment by snej** [comment] 2016-10-02 00:52
>Killing the app and restarting (i. e. Restarting continuous replication does not work either. 

Replication is incremental, so I wouldn't expect this to work. If that sequence got missed for some reason, the replicator won't see it again because it's only asking for higher sequences.

One thing you can try as an experiment is resetting the replication:
```objc
replication.customProperties = @{@"reset": @YES};
[replication start];
```
Setting the `reset` property forces the saved checkpoint to be ignored, which makes the replicator start over again from the beginning. This isn't a good idea in general because the replicator will have to scan through every document on the server to find revisions that it doesn't have, but it's a good way to figure out whether it really did miss a revision it was supposed to get.

**Comment by snej** [comment] 2016-10-02 00:55
Are you sure that the SG sync function gave all 3 users access to the document?

**Comment by pradipvaghasiya** [comment] 2016-10-03 08:59
Yes, SG sync function gives permission to all. In fact this particular doc (kamero:config) is accessible to all (GUEST)

Sync function snippet

`case "Config":  //doc type
requireRole("admin");
channel("channelOpen");
break;`

json

`"users": {
        "GUEST": { "disabled": false , "admin_roles" : ["event_viewers"]}
      },
    "roles":{
      "loggedIn_users" : {"admin_roles": ["event_viewers"], "admin_channels" : ["channelLoggedIn"]},
      "event_viewers" : {"admin_channels" : ["channelOpen"]}
    }`

Terminal snippet displaying all users have access to channel channelOpen
`pradip@scw-a66634:~$ curl -X  GET http://127.0.0.1:4985/kamero/_user/947051868695804
{"name":"947051868695804","all_channels":["!","947051868695804","947051868695804-data","947051868695804-events","ahnnsc","ahnnsc-data","ahnnsc-owners","avznfb","avznfb-data","avznfb-owners","channelLoggedIn","channelOpen","cuty8h","cuty8h-data","cuty8h-owners","dayesm","dayesm-data","dayesm-owners","fvusoa","fvusoa-data","fvusoa-owners","knebja","knebja-data","krhhcu","krhhcu-data","ktvuwd","ktvuwd-data","ktvuwd-owners","ldao96","ldao96-data","ldao96-owners","md6ong","md6ong-data","oouhfh","oouhfh-data","oouhfh-owners","sdz8dc","sdz8dc-data","sdz8dc-owners","u9k98r","u9k98r-data","vu5e6j","vu5e6j-data","vu5e6j-owners","xhfxvl","xhfxvl-data","xhfxvl-owners","ysia3o","ysia3pradip@scw-a66634:~$ 
pradip@scw-a66634:~$ curl -X  GET http://127.0.0.1:4985/kamero/_user/896498073737333
{"name":"896498073737333","all_channels":["!","896498073737333","896498073737333-data","896498073737333-events","ahnnsc","ahnnsc-data","ahnnsc-owners","avznfb","avznfb-data","avznfb-owners","channelLoggedIn","channelOpen","cuty8h","cuty8h-data","cuty8h-owners","dayesm","dayesm-data","dayesm-owners","fvusoa","fvusoa-data","fvusoa-owners","knebja","knebja-data","krhhcu","krhhcu-data","ktvuwd","ktvuwd-data","ktvuwd-owners","ldao96","ldao96-data","ldao96-owners","md6ong","md6ong-data","oouhfh","oouhfh-data","oouhfh-owners","sdz8dc","sdz8dc-data","sdz8dc-owners","u9k98r","u9k98r-data","vu5e6j","vu5e6j-data","vu5e6j-owners","xhfxvl","xhfxvl-data","xhfxvl-owners","ysia3o","ysia3o-data"],"email":"diptipkl8@gmail.com","roles":["loggedIn_users","event_viewers"]}pradip@scw-a66634:~$ 
pradip@scw-a66634:~$ 
pradip@scw-a66634:~$ curl -X  GET http://127.0.0.1:4985/kamero/_user/10153418908626890
{"name":"10153418908626890","all_channels":["!","10153418908626890","10153418908626890-data","10153418908626890-events","ahnnsc","ahnnsc-data","ahnnsc-owners","avznfb","avznfb-data","avznfb-owners","channelLoggedIn","channelOpen","cuty8h","cuty8h-data","cuty8h-owners","dayesm","dayesm-data","dayesm-owners","fvusoa","fvusoa-data","fvusoa-owners","knebja","knebja-data","krhhcu","krhhcu-data","krhhcu-owners","ktvuwd","ktvuwd-data","ktvuwd-owners","ldao96","ldao96-data","ldao96-owners","md6ong","md6ong-data","md6ong-owners","oouhfh","oouhfh-data","oouhfh-owners","sdz8dc","sdz8dc-data","u9k98r","u9k98r-data","vu5e6j","vu5e6j-data","vu5e6j-owners","xhfxvl","xhfxvl-data","xhfxvl-owners","ysia3o","ysia3o-data"],"email":"rishabh.thakrar@gmail.com","roles":["loggedIn_users","event_viewers"]}pradip@scw-a66634:~$ `

**Comment by pradipvaghasiya** [comment] 2016-10-03 09:01
I am currently using singleton for continuous replication. So reset will not have impact in between app session. However next time when I face this issue i will try reset and run the app to check whether app fetches the missing doc and let you know.

**Comment by pradipvaghasiya** [comment] 2016-10-10 10:21
I got the same issue again and if I **reset (in customProperties)** the continuous replication it pulls the doc fine. 

Other issue: While checking for above issue, I also came across the other issue where Continuous replication just stops replicating document on poor network (like 3G). On Restarting the replication by restarting app, it works fine (**WITHOUT reset in customProperties**) This is happening more frequently than above issue.

**Comment by snej** [comment] 2016-10-10 17:58
Let's get some logging from CBL. Can you please turn on `SyncVerbose` logging (see the docs for details; you can do this from the Scheme inspector in Xcode), then run the app long enough to reproduce the problem, then upload the log output [which could be large] to a gist or pastebin or something like that? Then paste a link here. Thanks!

**Comment by npomfret** [comment] 2016-10-14 11:53
I've seen this problem too, exactly as described.  For me it happens when a user is added to a channel that has existing documents.  Sometimes maybe one document gets missed from replication and doesn't appear on the client until the next revision.

**Comment by npomfret** [comment] 2016-10-22 20:21
Also, I don't think this is related only to continuous pull.  My app has a feature that allows you to change user.  When this happens the app creates a new database for that user and does a one-shot pull sync in order to get the new users data.  After the one-shot pull sync has finished it's typically missing documents.  Quite easy to reproduce.

**Comment by npomfret** [comment] 2016-10-25 11:51
@snej I think this needs to be a high priority bug.  It's fairly easy to reproduce and pretty serious - replication just isn't working reliably.

Here's an example, and I've included a link to the CBL docs. The user looks like this:

```
{
  name: "0e50ac6e-aef1-438e-b104-2af24d99384d",
  admin_channels: [
    "ch_global_docs",
    "ch_private_0e50ac6e-aef1-438e-b104-2af24d99384d",
    "ch_public_0e50ac6e-aef1-438e-b104-2af24d99384d"
  ],
  all_channels: [
    "!",
    "ch_global_docs",
    "ch_private_0e50ac6e-aef1-438e-b104-2af24d99384d",
    "ch_public_0e50ac6e-aef1-438e-b104-2af24d99384d"
  ]
}
```

And the missing document is this:

```
{
  "owner": "0e50ac6e-aef1-438e-b104-2af24d99384d",
  "account_id": "0a5b25e1755fa5b22e93c2d7f5cdcbba",
  "verified_encrypted_contact_methods": [],
  "audit": {
    "user_id": "admin",
    "client_timestamp_utc": "2016-10-25T11:18:10.121Z"
  },
  "blocked_users": {},
  "_sync": {
    "time_saved": "2016-10-25T12:18:10.124140591+01:00",
    "sequence": 397851,
    "rev": "1-bba8996c6738f66a9878d469e0447482",
    "history": {
      "channels": [
        [
          "ch_private_0e50ac6e-aef1-438e-b104-2af24d99384d",
          "ch_public_0e50ac6e-aef1-438e-b104-2af24d99384d"
        ]
      ],
      "revs": [
        "1-bba8996c6738f66a9878d469e0447482"
      ],
      "parents": [
        -1
      ]
    },
    "channels": {
      "ch_private_0e50ac6e-aef1-438e-b104-2af24d99384d": null,
      "ch_public_0e50ac6e-aef1-438e-b104-2af24d99384d": null
    },
    "recent_sequences": [
      397851
    ]
  },
  "trustees": [],
  "account_alias": "",
  "type": "public-profile",
  "abandoned_chat_groups": {}
}
```

I've checked the changes feed from sequence 0 and the document id isn't there.

Here's the log https://gist.github.com/npomfret/22f8ec4e87d8fc26b307a69044baf9f7

**Comment by pasin** [comment] 2016-12-20 01:23
@npomfret I want to try to reproduce the issue. Can you share the sync-function for the part that involves the issue? Also what is the sync-gateway version are you using?

**Comment by npomfret** [comment] 2016-12-20 05:53
I can't reproduce it with my current set up, but if I do I'll try and capture the data and post it here.

**Comment by pasin** [comment] 2016-12-20 23:20
Then I will close the issue now. When there is more info, we can reopen the issue again. Thank you very much.

**Closed by pasin** 2016-12-20 23:20 UTC
Labels: bug, f: Replication, needsmoreinfo, P2: medium, ready

**Comment by rajshekhar16** [comment] 2017-11-17 15:12
I've seen this problem too, as mentioned by @npomfret and @pradipvaghasiya . Some docs gets missed from replication and doesn't appear on the client until the next revision. Also if I add reset custom properties in pull replicator all docs appear. I am using cbl sync-gateway 1.4.1 and cblite - 1.4 for iOS.App uses filter pull (channel wise) to pull the docs.

**Comment by pasin** [comment] 2017-11-17 16:19
@rajshekhar16 could you turn on Sync, SyncVerbose, ChangeTracker, and ChangeTrackerVerbose on the client side and collect both client and SGW log when reproducing the issue? Without the log, we couldn't pin point the cause of the issue as the issue.

Also we have released CBL 1.4.1 and SGW 1.5. You may try to see if the new version helps fixing the issue.

**Comment by rajshekhar16** [comment] 2017-11-22 11:15
Hi Pasin
I have attached device logs for the following case.

Some documents were shared from device A to device B. Device B got the documents. Now, device B calls an API on the server to change these documents. The new revisions are synced on device B and not on device A.

Also, if I remove the app from stack in device A, and start again, the new revisions are pulled. It is like the puller gets stuck.

I have attached the logs of device A, specifically the last logs of CBLRestPuller.
[A.txt](https://github.com/couchbase/couchbase-lite-ios/files/1495701/A.txt)

If you need more logs, let me know.

Device - iPhone 5S, iOS 11.1.1
CouchbaseLite version - 1.4
Sync Gateway version - 1.4.1

**Comment by pasin** [comment] 2017-11-22 16:47
@rajshekhar16 I couldn't see any issues on the log that you provided. The puller replicator is in the IDLE state waiting for changes. Normally when the pull replicator doesn't pull the document, most likely it because hat SGW doesn't notify any changes to the client. There are several things that you can try to troubleshoot.

1. Try with CBL 1.4.1 and the latest SGW 1.5. 
2. Try to disable using web socket on the replicator. SGW 1.4.1 has an issue that could cause web-socket to stop working. To disable websocket, do this `[pullReplication setCustomProperties:@{@"websocket": @NO}];`
3. Check SGW log to see if there are any errors or not.

If the above couldn't help, I suggested that you create a new issue with both CBL log (with Sync, SyncVerbose, ChangeTracker, and ChangeTrackerVerbose logging enabled) and SGW log.
