### ISSUE TITLE
transitive dependencies when using pods

### ISSUE THREAD

**Issue by VenuKotha** [couchbase/couchbase-lite-ios#1539] opened 2016-12-29 14:27 UTC
--------
* Version:   1.2.1
* Client OS: ios

Hi,
I am using couchbase-lite-ios(1.2.1) using cocoapods version 1.0.0. In my pod file if I use "use_frameworks!"  keyword i am getting below error at the time of pod installation
" The 'Pods-Support' target has transitive dependencies that include static binaries:(xxxxx/Pods/couchbase-lite-ios/CouchbaseLiteListener.framework".

I tried with couchbase-lite-ios(1.3) version also and getting the same issue. 
Can you please tell what can i do to resolve this issue?
please excuse me if i post this in wrong place.
Thank you

**Comment by pasin** [comment] 2017-01-03 18:34
This is a duplicate of #1505. Basically The release version of couchbase-lite-ios currently supports only static library so basically using use_frameworks! will not be working.

**Closed by pasin** 2017-01-03 18:34 UTC
