### ISSUE TITLE
Issue with adding "big" attachments 

### ISSUE THREAD

**Issue by lucatorella** [couchbase/couchbase-lite-ios#1620] opened 2017-02-15 16:51 UTC
I found out an issue with couchbase lite and I managed to create a minimal example to reproduce it. Here is the code:

```
        self.couchbaseQueue.async { [unowned self] in
            let document = self.database.createDocument()
            do {
                let newRevision = try document.putProperties(["type": "session", "name": "pippo"])
            } catch let error as NSError {
                print(error)
            }

            let image = UIImage(named: "bigimage")!
            let data = UIImagePNGRepresentation(image)

            let revision = document.newRevision()
            revision.setAttachmentNamed("name", withContentType: nil, content: data)
            do {
                try revision.save()
            } catch let error as NSError {
                print(error)
            }
        }
```

Basically, I create a new document, and I create a new revision and I attach a ~3MB image. The result is that the document is synced to the cloud db, but not the attachment. And the worse thing is that the replication status hang up in "pending" state. If I restart the app, replication goes to pending and hang up there again, blocking any other push.

Here is the log (with "RemoteRequestVerbose"):

```
17:38:37.521‖ RemoteRequest: Added Authorization header for CBLPasswordAuthorizer[device_478/****]
17:38:37.521‖ RemoteRequest: CBLRemoteJSONRequest[POST https://zzz-staging-data.yyy.com/customer_4/_revs_diff]: Starting...
17:38:37.522‖ RemoteRequest: CBLRemoteSession starting CBLRemoteJSONRequest[POST https://zzz-staging-data.yyy.com/customer_4/_revs_diff]
17:38:37.628‖ RemoteRequest: Got challenge for CBLRemoteJSONRequest[POST https://zzz-staging-data.yyy.com/customer_4/_revs_diff]: method=NSURLAuthenticationMethodServerTrust, err=(null)
17:38:37.632‖ RemoteRequest:     useCredential for trust: <SecTrustRef: 0x6000001045c0>
17:38:37.715‖ RemoteRequest: CBLRemoteJSONRequest[POST https://zzz-staging-data.yyy.com/customer_4/_revs_diff]: Got response, status 200
17:38:37.715‖ RemoteRequest: CBLRemoteJSONRequest[POST https://zzz-staging-data.yyy.com/customer_4/_revs_diff]: Got 79 bytes
17:38:37.715‖ RemoteRequest: CBLRemoteSession done with CBLRemoteJSONRequest[POST https://zzz-staging-data.yyy.com/customer_4/_revs_diff]
17:38:37.716‖ RemoteRequest: CBLRemoteJSONRequest[POST https://zzz-staging-data.yyy.com/customer_4/_revs_diff]: Finished loading
17:38:37.717‖ RemoteRequest: Added Authorization header for CBLPasswordAuthorizer[device_478/****]
17:38:37.717‖ RemoteRequest: CBLRemoteJSONRequest[POST https://zzz-staging-data.yyy.com/customer_4/_bulk_docs]: Starting...
17:38:37.718‖ RemoteRequest: CBLRemoteSession starting CBLRemoteJSONRequest[POST https://zzz-staging-data.yyy.com/customer_4/_bulk_docs]
17:38:37.758‖ RemoteRequest: CBLRemoteJSONRequest[POST https://zzz-staging-data.yyy.com/customer_4/_bulk_docs]: Got response, status 201
17:38:37.758‖ RemoteRequest: CBLRemoteJSONRequest[POST https://zzz-staging-data.yyy.com/customer_4/_bulk_docs]: Got 3 bytes
17:38:37.758‖ RemoteRequest: CBLRemoteSession done with CBLRemoteJSONRequest[POST https://zzz-staging-data.yyy.com/customer_4/_bulk_docs]
17:38:37.758‖ RemoteRequest: CBLRemoteJSONRequest[POST https://zzz-staging-data.yyy.com/customer_4/_bulk_docs]: Finished loading
17:38:38.382‖ RemoteRequest: Added Authorization header for CBLPasswordAuthorizer[device_478/****]
17:38:38.383‖ RemoteRequest: CBLRemoteJSONRequest[POST https://zzz-staging-data.yyy.com/customer_4/_revs_diff]: Starting...
17:38:38.383‖ RemoteRequest: CBLRemoteSession starting CBLRemoteJSONRequest[POST https://zzz-staging-data.yyy.com/customer_4/_revs_diff]
17:38:38.424‖ RemoteRequest: CBLRemoteJSONRequest[POST https://zzz-staging-data.yyy.com/customer_4/_revs_diff]: Got response, status 200
17:38:38.424‖ RemoteRequest: CBLRemoteJSONRequest[POST https://zzz-staging-data.yyy.com/customer_4/_revs_diff]: Got 139 bytes
17:38:38.425‖ RemoteRequest: CBLRemoteSession done with CBLRemoteJSONRequest[POST https://zzz-staging-data.yyy.com/customer_4/_revs_diff]
17:38:38.425‖ RemoteRequest: CBLRemoteJSONRequest[POST https://zzz-staging-data.yyy.com/customer_4/_revs_diff]: Finished loading
17:38:38.425‖ RemoteRequest: Added Authorization header for CBLPasswordAuthorizer[device_478/****]
17:38:38.426‖ RemoteRequest: CBLMultipartUploader[PUT https://zzz-staging-data.yyy.com/customer_4/-Fk2Gb28sEF2eyJaBgnedTr?new_edits=false]: Starting...
17:38:38.426‖ RemoteRequest: CBLRemoteSession starting CBLMultipartUploader[PUT https://zzz-staging-data.yyy.com/customer_4/-Fk2Gb28sEF2eyJaBgnedTr?new_edits=false]
17:38:42.628‖ View 'localviews/product-name' of db 'couchbase.cblite2' starting compaction
17:38:42.657‖ View 'localviews/product-name' of db 'couchbase.cblite2' finished compaction
17:39:39.421‖ RemoteRequest: CBLRemoteSession done with CBLMultipartUploader[PUT https://zzz-staging-data.yyy.com/customer_4/-Fk2Gb28sEF2eyJaBgnedTr?new_edits=false]
```

--------
* Version:   1.3.1
* Client OS: iOS 10.2.1
* Server:    CouchDB 1.6.1

**Comment by lucatorella** [comment] 2017-02-15 16:59
Actually the same thing happens if I add an attachment to an existing document:

```
        self.couchbaseQueue.async { [unowned self] in
            let document = self.database.document(withID: "-XXsezPO1VPfW8Wzbl16quw")
            let image = UIImage(named: "screenshot")!
            let data = UIImagePNGRepresentation(image)

            let revision = document.newRevision()
            revision.setAttachmentNamed("name", withContentType: nil, content: data)
            do {
                try revision.save()
            } catch let error as NSError {
                print(error)
            }
        }
```

I forgot to mention that if the attachment is small (~50Kb), both methods work fine

**Comment by pasin** [comment] 2017-02-16 01:58
We have a unit test that pulls and pushes a very big attachment (~30M) to SGW and the unit test doesn't have the same issue. I will need to test this out with CouchDB.

@sethrosetter do we have any functional tests that test push and pull with big attachments ( > 3 M)?

**Comment by sethrosetter** [comment] 2017-02-16 02:01
We have one that does a large attachment (2.4mb), but not with CouchDB

**Comment by niespodd** [comment] 2017-02-17 17:52
We think we found the potential cause of the issue. We are using AWS setup: there is an ELB load-balancer between clients and CouchDB server. 

For some reason the content of request delivered to the couchdb server has no [boundary closing section](https://tools.ietf.org/html/rfc2046#section-5.1.1) and the `Content-Length` value of the request is higher than the body length.

We performed a test when we disabled ELB and connected our client directly to the server. It worked.

**Comment by pasin** [comment] 2017-02-17 19:55
Thanks for investigating and updating the issue. I'm closing the issue now. We could reopen the issue if it turns out it's a CBL issue.

**Comment by lucatorella** [comment] 2017-02-17 20:35
I wouldn't close the issue straight away because even if it seems like if we remove the ELB layer everything works (and note that except for testing we need that layer for scalability reasons), we forgot to mention that the Android version of couchbase lite doesn't trigger this issue. So we still think that the iOS implementation somehow is different and it's causing this failure. 

Moreover, I don't think couchbase should be completely stuck when it receives a 408 from the server. I mean at the moment, after I add a "big" attachment the replication is completely blocked and all other changes are not pushed (and not even tried). Even after killing and restarting the app.

**Comment by winklerp** [comment] 2017-09-10 15:31
I am also experiencing this issue: latest couchbase iOS lite 1.4 from master branch, Sync Gateway 1.5 beta.
The issue happens on AWS with ELB and NGINX in front of Sync-Gateway but only when SSL is enabled. When i disable SSL on NGINX everything is working as expected. Also the file size of the attachment has to be a little bit "bigger". Eg. the pictures in the Xcode iOS simulator are not syncing. Even worse, the CBLReplicator "hangs", even if the app is restarted and the app is completely blocked. I tried a lot of different SSL settings on NGINX but couldn't find a solution. 

A solution is really needed or at least a recommendation which load balancer with SSL is support by couchbase lite and sync gateway with "bigger" attachments.

Thank you for your support!

**Comment by winklerp** [comment] 2017-09-10 15:32
what I meant was it doesn't work with AWS ELB or NGINX as a reverse proxy in front of Sync Gateway.

**Comment by pasin** [comment] 2017-09-12 21:27
@winklerp , does the replicator get any error (e.g. 408 timeout)?

@adamcfraser has the SGW side received the same or similar errors reported about unable to replicate big attachments when using load balancer & SSL before?

**Comment by adamcfraser** [comment] 2017-09-12 22:09
@pasin I haven't heard any reports of that specific issue.  Does the request make it to SG and then times out (based on the SG logs), or it is failing to make it through the LB to SG?

**Comment by winklerp** [comment] 2017-09-13 04:16
based on the logs of sync gateway the put request to update the document makes it to sync gateway. There was nothing else in the log file of sg -> the last entry was the put request (no timeout or anything else). In the log file of nginx also the put request with return code 408 was the last entry. On iOS in the sync log it showed that the cblmultipartuploader was startet and cblreplication made the put request. That's it, nothing else. Unfortunally I cannot create another log because as a workaround I moved the SSL handling directly to the sync gateway and replaced the elb/nginx with a network load balancer (tcp balancer) which just routes the packages to sync gateway. This works for now bit I would prefer to have the ssl termination in the load balancer.

**Comment by pasin** [comment] 2017-09-13 18:00
> In the log file of nginx also the put request with return code 408 was the last entry.

Do you mean the PUT request from the NGINX to SGW? Does it mean that the PUT request made it through SGW but the result returned as 408? Can you clarify on this? Also Can you provide info about the raw request that has the issue?

**Comment by winklerp** [comment] 2017-09-13 19:13
Yes, the PUT request made it from NGINX through to SGW.  The request was just a small document with one attachment. I used a sample image from iOS Simulator 10.3. With the following setup you can reproduce the bug:

iOS App (Swift, Couchbase lite) --> NGINX (**SSL** termination, config from couchbase doc) --> SGW 1.5 beta 2 --> Couchbase 5.0 beta 2

As I said before, with NGINX without SSL it works (same setup except SSL):

iOS App (Swift, Couchbase lite) --> NGINX --> SGW 1.5 beta 2 (**SSL**) --> Couchbase 5.0 beta 2

**Comment by pasin** [comment] 2018-04-13 04:16
Sorry for taking so long to look at the issue. Today I tried to reproduce the issue with the following setup but it didn't see the same issue.

CBL: 1.4.1
SG: 1.4.1 
NGINX: v1.13.11 + SSL (Self-Sign Certificate)
Attachment Size: 12M
iOS: 9.3, 10.3, 11.2

However all setup are on my local mac. I'm wondering if different NGINX version might be a key to reproduce the issue.

**Comment by pasin** [comment] 2018-04-13 04:50
Similar setup on AWS EC2 doesn't have the issue as well.

CBL: 1.4.1 and 1.3.1
SG: 2.0.0
NGINX: v1.10.3 + SSL (Self-Sign Certificate)
Attachment Size: 12M and 35M
iOS: 9.3, 10.3, 11.2

**Comment by pasin** [comment] 2018-08-21 18:11
Closed as no activity. We can reopen the issue again when there is more info.

**Closed by pasin** 2018-08-21 18:11 UTC
Labels: icebox
