### ISSUE TITLE
-[CBLQueryResult valueAtIndex] never returns NSNull

### ISSUE THREAD

**Issue by snej** [couchbase/couchbase-lite-ios#2102] opened 2018-03-14 23:02 UTC
If a query row contains a JSON `null` column, `-[CBLQueryResult valueAtIndex:]` incorrectly returns its value as `nil`, not an `NSNull` object.

This is because `-fleeceValueToObjectAtIndex:` doesn't consult `_missingColumns`, it simply treats a `null` value as `nil`:

```objc
    if (value == nullptr || FLValue_GetType(value) == kFLNull)
        return nil;
```

**Comment by pasin** [comment] 2018-03-14 23:07
This is expected behavior that CBLDictionary, CBLArray, and CBLQueryResult will not return NSNull Object per cross-platform consistency. To check whether it's null or missing, need to use -containsValueForKey:.

**Comment by snej** [comment] 2018-03-14 23:19
The `-testMissingValue` test didn't detect this because it's looking for the wrong value:
```objc
    AssertNil([r valueAtIndex: 1]);
```
should be
```objc
    AssertEqualObjects([r valueAtIndex: 1], [NSNull null]);
```

(I'm working on a fix.)

**Comment by pasin** [comment] 2018-03-14 23:22
@snej it's not a bug. The current API (CBLDictionary, CBLArray, and CBLQueryResult) doesn't return NSNull for null value.

**Comment by snej** [comment] 2018-03-14 23:23
So how do you check whether it's null by index? There's no `-containsValueAtIndex:` method.

**Comment by pasin** [comment] 2018-03-14 23:27
Currently there is none. That is something we could add to CBLQueryResult.

**Comment by snej** [comment] 2018-03-14 23:31
`-toDictionary` doesn't preserve JSON `null` either. So if you store an NSDictionary containing `[NSNull]` into a document, then get the document as an NSDictionary, the `NSNull` value is missing. That's inconsistent with Java and .NET, isn't it?

**Comment by pasin** [comment] 2018-03-14 23:35
> That's inconsistent with Java and .NET, isn't it?

Yes, that's inconsistent and should be fixed.

**Comment by snej** [comment] 2018-03-14 23:37
^ Actually what I wrote there isn't true (it was an artifact of some local changes I'd made and not backed out) so I deleted the comment before you replied :)

**Closed** 2018-03-15 00:00 UTC
