### ISSUE TITLE
Deleting Database takes long time as compared with 1.0.4 release

### ISSUE THREAD

**Issue by ashvindersingh** [couchbase/couchbase-lite-ios#738] opened 2015-05-22 22:41 UTC
Using the test from worker bee repo: 

https://github.com/couchbaselabs/iOS-WorkerBee/blob/master/Tests/Test10_DeleteDB.m

Test Delete database:
Sum KPI for release 1.0.4: 33.11
Sum KPI for release 1.1.0: 532.26

Total time (in seconds) it took to run the complete test scenario with all the options. Each test scenario consists of multiple sub tests. One sub test is a combination of unique input values(example, size of document and number of documents).  Each sub test was run three times and the result was averaged. Once all the subtests are finished. All the average values were summed to reach the SumKPI.

**Comment by snej** [comment] 2015-05-22 23:34
What's the actual time to delete a database once? Unless it's incredibly long I don't think this is worth investigating — database deletion doesn't happen often in real apps.

**Comment by pasin** [comment] 2015-05-22 23:36
I'm seeing some delay in 1.1.0 as well. I did a quick profiling on 1.1.0 and the majority of time spent was closing the sqlite file. I guessed it because the SQLite DB spent time moving data from the WAL file the main db file.

Delete Database, 1000 Documents, 100 bytes each:
1.0.4:
2015-05-22 12:55:12.065 Perf110[4190:1032882] Time used : 2.384539 msec.
2015-05-22 12:55:27.735 Perf110[4195:1033117] Time used : 2.436206 msec.
2015-05-22 12:55:39.049 Perf110[4201:1033292] Time used : 2.479206 msec.
---
1.1.0:
2015-05-22 12:52:35.026 Perf110[4157:1031232] Time used : 35.057206 msec.
2015-05-22 12:53:13.467 Perf110[4163:1031595] Time used : 36.628039 msec.
2015-05-22 12:53:30.305 Perf110[4168:1031864] Time used : 37.278789 msec.

**Comment by snej** [comment] 2015-05-22 23:39
35ms to delete a database is fine IMHO. That's 30 databases/sec. I agree with Pasin that the regression is probably a side effect of switching to the SQLite WAL (and probably nothing we can do anything about.)

**Comment by pasin** [comment] 2015-05-22 23:39
Note: in 1.0.4, I don't think we really enable the WAL option as I have never seen the WAL file.

**Comment by pasin** [comment] 2015-05-26 18:08
I'm closing as not an issue.

**Closed by pasin** 2015-05-26 18:08 UTC
Labels: ready
