### ISSUE TITLE
LIKE queries are significantly slower in the new Couchbase Lite Enterprise 2.7.0

### ISSUE THREAD

**Issue by PA-Patrick** [couchbase/couchbase-lite-ios#2603] opened 2020-01-27 18:07 UTC
* Version: CouchbaseLite Swift Enterprise 2.7.0
* Client OS: iOS 13.2.3
* Server: Couchbase Sync Gateway Enterprise 2.6.1 and Couchbase Server Enterprise 6.0.3
--------
* Source Code:
```
QueryBuilder
  .select(SelectResult.expression(Meta.id))
  .from(DataSource.database(database))
  .where(Expression.property("type").equalTo(Expression.string("Product"))
    .and(Function.lower(Expression.property("Name")).like(Expression.string("%\(searchStr)%"))
      .or(Function.lower(Expression.property("ProducerName")).like(Expression.string("%\(searchStr)%")))))
  .orderBy(Ordering.expression(Function.lower(Expression.property("Name"))))
  .limit(Expression.int(100), offset: Expression.int(page * 100))
  .execute()
```
--------
* Description:

CouchbaseLite Swift Enterprise 2.6.1 -> Querytime = 0.01 seconds
CouchbaseLite Swift Enterprise 2.7.0 -> Querytime = 10 seconds or more

An index is defined/created and working.

I have discovered the following:

Items sorted by name (type is „Product“):
```
Item 1
Item 2
Item 3
Item 4
Item 5
[…]
Item 194731
Item 194732
Item 194733
Item 194734
Item 194735
```

If the result of query is „Item 3“ and „Item 5“, the time for query is acceptable (0.3 seconds).
If the result of query is „Item 194732“ and „Item 194734“, the time for query is terrible (12 seconds).

I found the following similar issue: https://github.com/couchbase/couchbase-lite-core/issues/902

**Comment by pasin** [comment] 2020-01-27 18:12
Can you provide the index you have created and the Query's plan?

**Comment by PA-Patrick** [comment] 2020-01-27 18:18
````
IndexBuilder.valueIndex(items:
  ValueIndexItem.expression(Expression.property("type")),
  ValueIndexItem.expression(Function.lower(Expression.property("Name"))),
  ValueIndexItem.expression(Function.lower(Expression.property("ProducerName")))
), withName: "TypeNameIndex")
````
Query´s plan? If I execute "explain", I see that the query use the right index. Do you mean that?

**Comment by pasin** [comment] 2020-01-27 18:45
Yes, please provide that as well.

**Comment by pasin** [comment] 2020-01-27 18:46
Also how many docs are in the database and are you able to provide a sample database that we can use to test?

**Comment by PA-Patrick** [comment] 2020-01-28 10:21
In the database are round about 200,000 documents of this type and 4,000,000 total. Unfortunately it is not possible to share the database because of privacy police of our customer.

I try to get all information you need.

All queries run on the same iPad with same iOS Version in the same App. The only different are the CouchbaseLite Version.

---

A similar sample with the following index:
````
IndexBuilder.valueIndex(items:
  ValueIndexItem.expression(Expression.property("type")),
  ValueIndexItem.expression(Function.lower(Expression.property("Bezeichnung"))),
  ValueIndexItem.expression(Expression.property("search"))
), withName: "TypeBezeichnungSearchIndex")
````
---

Query with **iOS Couchbase Lite Enterprise 2.6.3**:

1. without search string:
````
SELECT fl_result(_doc.key) FROM kv_default AS _doc WHERE (fl_value(_doc.body, 'type') = 'Artikel' AND fl_value(_doc.body, 'search') LIKE '101|%') AND (_doc.flags & 1 = 0) ORDER BY N1QL_lower(fl_value(_doc.body, 'Bezeichnung')) LIMIT MAX(0, 100) OFFSET MAX(0, 0)

10|0|0| SEARCH TABLE kv_default AS _doc USING INDEX TypeBezeichnungSearchIndex (<expr>=?)

{"WHAT":[["._id"]],"WHERE":["AND",["=",[".type"],"Artikel"],["LIKE",[".search"],"101|%"]],"LIMIT":100,"ORDER_BY":[["LOWER()",[".Bezeichnung"]]],"OFFSET":0}
````
````
2020-01-28 10:43:32.244 # query time: 0.0102s 
````

2. with search string „bal“:
````
SELECT fl_result(_doc.key) FROM kv_default AS _doc WHERE (fl_value(_doc.body, 'type') = 'Artikel' AND fl_value(_doc.body, 'search') LIKE '101|%bal%') AND (_doc.flags & 1 = 0) ORDER BY N1QL_lower(fl_value(_doc.body, 'Bezeichnung')) LIMIT MAX(0, 100) OFFSET MAX(0, 0)

10|0|0| SEARCH TABLE kv_default AS _doc USING INDEX TypeBezeichnungSearchIndex (<expr>=?)

{"WHAT":[["._id"]],"WHERE":["AND",["=",[".type"],"Artikel"],["LIKE",[".search"],"101|%bal%"]],"LIMIT":100,"ORDER_BY":[["LOWER()",[".Bezeichnung"]]],"OFFSET":0}
````
````
2020-01-28 10:57:08.050 # query time: 0.0199s
````

3. with search string „ballon“:
````
SELECT fl_result(_doc.key) FROM kv_default AS _doc WHERE (fl_value(_doc.body, 'type') = 'Artikel' AND fl_value(_doc.body, 'search') LIKE '101|%ballon%') AND (_doc.flags & 1 = 0) ORDER BY N1QL_lower(fl_value(_doc.body, 'Bezeichnung')) LIMIT MAX(0, 100) OFFSET MAX(0, 0)

10|0|0| SEARCH TABLE kv_default AS _doc USING INDEX TypeBezeichnungSearchIndex (<expr>=?)

{"WHAT":[["._id"]],"WHERE":["AND",["=",[".type"],"Artikel"],["LIKE",[".search"],"101|%ballon%"]],"LIMIT":100,"ORDER_BY":[["LOWER()",[".Bezeichnung"]]],"OFFSET":0}
````
````
2020-01-28 10:44:29.784 # query time: 0.0300s
````

4. with search string „sensurabas“:
````
SELECT fl_result(_doc.key) FROM kv_default AS _doc WHERE (fl_value(_doc.body, 'type') = 'Artikel' AND fl_value(_doc.body, 'search') LIKE '101|%sensurabas%') AND (_doc.flags & 1 = 0) ORDER BY N1QL_lower(fl_value(_doc.body, 'Bezeichnung')) LIMIT MAX(0, 100) OFFSET MAX(0, 0)

10|0|0| SEARCH TABLE kv_default AS _doc USING INDEX TypeBezeichnungSearchIndex (<expr>=?)

{"WHAT":[["._id"]],"WHERE":["AND",["=",[".type"],"Artikel"],["LIKE",[".search"],"101|%sensurabas%"]],"LIMIT":100,"ORDER_BY":[["LOWER()",[".Bezeichnung"]]],"OFFSET“:0}
````
````
2020-01-28 10:46:30.824 # query time: 0.1246s
````
---

Query with **iOS Couchbase Lite Enterprise 2.7.0**:

1. without search string:
````
SELECT fl_result(_doc.key) FROM kv_default AS _doc WHERE (fl_value(_doc.body, 'type') = 'Artikel' AND fl_like(fl_value(_doc.body, 'search'), '101|%')) AND (_doc.flags & 1 = 0) ORDER BY N1QL_lower(fl_value(_doc.body, 'Bezeichnung')) LIMIT MAX(0, 100) OFFSET MAX(0, 0)

10|0|0| SEARCH TABLE kv_default AS _doc USING INDEX TypeBezeichnungSearchIndex (<expr>=?)

{"WHAT":[["._id"]],"WHERE":["AND",["=",[".type"],"Artikel"],["LIKE",[".search"],"101|%"]],"LIMIT":100,"ORDER_BY":[["LOWER()",[".Bezeichnung"]]],"OFFSET":0}
````
````
2020-01-28 10:49:42.229 # query time: 0.0041s
````

2. with search string „bal“:
````
SELECT fl_result(_doc.key) FROM kv_default AS _doc WHERE (fl_value(_doc.body, 'type') = 'Artikel' AND fl_like(fl_value(_doc.body, 'search'), '101|%bal%')) AND (_doc.flags & 1 = 0) ORDER BY N1QL_lower(fl_value(_doc.body, 'Bezeichnung')) LIMIT MAX(0, 100) OFFSET MAX(0, 0)

10|0|0| SEARCH TABLE kv_default AS _doc USING INDEX TypeBezeichnungSearchIndex (<expr>=?)

{"WHAT":[["._id"]],"WHERE":["AND",["=",[".type"],"Artikel"],["LIKE",[".search"],"101|%bal%"]],"LIMIT":100,"ORDER_BY":[["LOWER()",[".Bezeichnung"]]],"OFFSET":0}
````
````
2020-01-28 10:55:01.392 # query time: 0.5878s
````

3. with search string „ballon“:
````
SELECT fl_result(_doc.key) FROM kv_default AS _doc WHERE (fl_value(_doc.body, 'type') = 'Artikel' AND fl_like(fl_value(_doc.body, 'search'), '101|%ballon%')) AND (_doc.flags & 1 = 0) ORDER BY N1QL_lower(fl_value(_doc.body, 'Bezeichnung')) LIMIT MAX(0, 100) OFFSET MAX(0, 0)

10|0|0| SEARCH TABLE kv_default AS _doc USING INDEX TypeBezeichnungSearchIndex (<expr>=?)

{"WHAT":[["._id"]],"WHERE":["AND",["=",[".type"],"Artikel"],["LIKE",[".search"],"101|%ballon%"]],"LIMIT":100,"ORDER_BY":[["LOWER()",[".Bezeichnung"]]],"OFFSET":0}
````
````
2020-01-28 10:50:47.239 # query time: 3.2902s
````

4. with search string „sensurabas“:
````
SELECT fl_result(_doc.key) FROM kv_default AS _doc WHERE (fl_value(_doc.body, 'type') = 'Artikel' AND fl_like(fl_value(_doc.body, 'search'), '101|%sensurabas%')) AND (_doc.flags & 1 = 0) ORDER BY N1QL_lower(fl_value(_doc.body, 'Bezeichnung')) LIMIT MAX(0, 100) OFFSET MAX(0, 0)

10|0|0| SEARCH TABLE kv_default AS _doc USING INDEX TypeBezeichnungSearchIndex (<expr>=?)

{"WHAT":[["._id"]],"WHERE":["AND",["=",[".type"],"Artikel"],["LIKE",[".search"],"101|%sensurabas%"]],"LIMIT":100,"ORDER_BY":[["LOWER()",[".Bezeichnung"]]],"OFFSET":0}
````
````
2020-01-28 10:51:45.196 # query time: 9.0975s
````

---
### Comparing times
query | 2.6.3 | 2.7.0
-- | -- | --
1: | 0.0102s | 0.0041s
2: "bal" | 0.0199s | 0.5878s
3: "ballon" | 0.0300s | 3.2902s
4: "sensurabas" | 0.1246s | 9.0975s

---

I suspect that in version 2.6.3 the LIKE operator uses the value of the index to compare, but in 2.7.0 it takes the value to compare from the document instead.

**Comment by pasin** [comment] 2020-01-28 18:51
The different is that:

2.6.3 uses fl_value(_doc.body, 'search') LIKE '101|%ballon%') 

2.7.0 uses fl_like(fl_value(_doc.body, 'search'), '101|%ballon%')) --> which is probably the cause of the slowness.

@PA-Patrick I just noticed that you are using the enterprise edition. If you are a Couchbase customer, the best channel to report or submit an issue is thru the customer support. In general, the issues submitted thru the customer support will get resolved much faster and higher priority.

**Comment by pasin** [comment] 2020-01-28 18:53
Seem like this is the same issue as https://github.com/couchbase/couchbase-lite-core/issues/902.

**Comment by pasin** [comment] 2020-01-28 18:55
@PA-Patrick Again, if you are a Couchbase customer, please submit the issue through the support channel to get the issue resolved faster.

**Comment by snej** [comment] 2020-01-29 18:30
Now filed in Jira as [CBL-657](https://issues.couchbase.com/browse/CBL-657).

**Comment by jayahariv** [comment] 2020-06-11 18:31
Closing this, since we already taken care in 2.7.1.

**Closed by jayahariv** 2020-06-11 18:31 UTC
Labels: ffc
