### ISSUE TITLE
Cocoapods codesign fails

### ISSUE THREAD

**Issue by iosdev-republicofapps** [couchbase/couchbase-lite-ios#1486] opened 2016-10-12 04:35 UTC
I installed via cocoapods in my Podfile:

```
pod 'couchbase-lite-osx', '~> 1.3.1'
```

Then when I go to build the workspace I get:

```
CodeSign /Users/joel/Library/Developer/Xcode/DerivedData/CouchbaseTestApp-dvtubogaapgbwigxjwsjptkuuaun/Build/Products/Debug/CouchbaseTestApp.app
    cd /Users/joel/src/CouchbaseTestApp
    export CODESIGN_ALLOCATE=/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/codesign_allocate

Signing Identity:     "-"

    /usr/bin/codesign --force --sign - --timestamp=none /Users/joel/Library/Developer/Xcode/DerivedData/CouchbaseTestApp-dvtubogaapgbwigxjwsjptkuuaun/Build/Products/Debug/CouchbaseTestApp.app

/Users/joel/Library/Developer/Xcode/DerivedData/CouchbaseTestApp-dvtubogaapgbwigxjwsjptkuuaun/Build/Products/Debug/CouchbaseTestApp.app: replacing existing signature
/Users/joel/Library/Developer/Xcode/DerivedData/CouchbaseTestApp-dvtubogaapgbwigxjwsjptkuuaun/Build/Products/Debug/CouchbaseTestApp.app: code object is not signed at all
In subcomponent: /Users/joel/Library/Developer/Xcode/DerivedData/CouchbaseTestApp-dvtubogaapgbwigxjwsjptkuuaun/Build/Products/Debug/CouchbaseTestApp.app/Contents/Frameworks/CouchbaseLite.framework
Command /usr/bin/codesign failed with exit code 1
```

The solution is to go into your project's Build Settings -> Signing -> Other Code Signing Flags and add the value `--deep`.  Then it builds and links and codesigns just fine.

You might want to add this to your Wiki or Cocoapods page to help others avoid this issue.

Either way, thanks for making Couchbase available - nice work!  :-)

---
- Version:   1.3.1
- Client OS: macOS Sierra 10.12 
- Server:    NAME_AND_VERSION

**Comment by pasin** [comment] 2016-12-20 01:21
I have run into the same issue when I linted the podspec for CBL MacOS v1.3.1. The issue was recently fixed in cocoapods (See https://github.com/CocoaPods/CocoaPods/pull/5645). Today I updated my cocoapods to the latest (1.1.1), and I couldn't reproduce the issue. We can close the issue now.

**Closed by pasin** 2016-12-20 01:21 UTC
Labels: P1: high, ready
