### ISSUE TITLE
Allow REST API to be called from JS in a WKWebView

### ISSUE THREAD

**Issue by snej** [couchbase/couchbase-lite-ios#851] opened 2015-08-07 22:35 UTC

**Comment by snej** [comment] 2015-08-12 17:16
As far as I can tell there's no direct way to do this. All we can do is go through a very limited one-way RPC interface to pass a JSON object to native code. Any responses would have to come via another facility where native code can evaluate a JS string.

We could use that to kludge together an API to Couchbase Lite. I don't know whether it would look like the REST API or not; there's no reason it has to.

**Comment by snej** [comment] 2015-09-04 18:58
It might be better to open a real socket on the loopback interface, the way Android does. It would be less work and more compatible.

**Comment by msanilkumar2020** [comment] 2017-01-10 07:13
@pasin  ,please let us know when this issue is getting fixed. Our application is not working if we use WKWebView.

Using of WKWebview is having more advantage in terms of memory compared to UIWeviewView.

**Comment by snej** [comment] 2017-01-11 20:40
You're receiving notifications for this issue, so you'll see when it gets assigned to a milestone, then updated, then closed.
Currently this work isn't scheduled.

**Comment by geraldapeoples** [comment] 2017-10-17 16:38
Is WKWebView going to be scheduled in future at all?

**Comment by pasin** [comment] 2017-10-17 18:37
Sorry, currently the issue hasn't been scheduled. I don't have the timeline for this issue.

**Comment by geraldapeoples** [comment] 2017-10-20 09:32
Hi Pasin, thanks for responding ... it is such a critical component for us, we use Ionic framework and the experience on the mobile without WKWebView is not as good. How difficult is it to get the code building on Xcode from scratch, and would you be able to provide some guidance to us so that we could try and implement the necessary functionality?

**Comment by pasin** [comment] 2017-10-20 16:58
@geraldapeoples I assumed that you are using [couchbase-lite-phonegap-plugin](https://github.com/couchbaselabs/Couchbase-Lite-PhoneGap-Plugin). You could replace the following line by starting the CBLListener object and use the localhost URL instead of the internal NSURLProtocol URL.

**Comment by geraldapeoples** [comment] 2017-10-30 15:21
@pasin Hi Pasin, yes we are using that plugin ... haven't managed to get your change to work.

Using -

```
CBLListener* dblsnr = [[CBLListener alloc] initWithManager:(CBLManager*)dbmgr port:(UInt16)8123];
    NSLog(@"Couchbase Lite dblsnr = %@", dblsnr);
    NSLog(@"Couchbase Lite port = %d", dblsnr.port);
```
when the port logs out it is always 0?

**Comment by msanilkumar2020** [comment] 2018-06-25 08:50
@snej / @pasin ,

Now officially UIWebview is depreciated in iOS 12, we are forced to use WKWebview. Please let us know when we will have support for WKWebview.
https://developer.apple.com/documentation/uikit/uiwebview?changes=_6

**Comment by geraldapeoples** [comment] 2018-06-25 09:19
There are folks working on a plugin for couchbase lite 2 - https://github.com/makbari/cordova-plugin-couchbase-lite-2.0, I haven't used it yet as it does not yet support using a session token for the replication agreements.

Is there going to be an official fully featured plugin for couchbase lite 2?

**Comment by snej** [comment] 2018-06-27 01:14
"Deprecated" doesn't mean removed. You can still use UIWebView in iOS 12, as far as I know.

**Comment by snej** [comment] 2018-06-27 16:19
Couchbase Lite 2 doesn't have a REST API. It could be implemented separately (which I think is what the 3rd party plugin mentioned above does.) We're still considering how to support JavaScript / PhoneGap clients; it's more likely that we'll implement a JavaScript binding to Couchbase Lite, since going through a REST API is awkward and inefficient and doesn't work well with modern WebViews.

**Comment by msanilkumar2020** [comment] 2018-06-28 06:03
@snej 
Thanks for clarification, do you have any timeline or plan to support/implement JavaScript binding to Couchbase Lite?

**Comment by snej** [comment] 2018-06-28 16:41
No schedule yet; it's one of those things where "we're assessing how much demand there is", so it would be useful to let our dev advocates (or sales people) know.

**Comment by geraldapeoples** [comment] 2018-06-29 08:32
That's not very encouraging

**Comment by snej** [comment] 2018-06-29 23:18
It's not a euphemism for "we're not doing it"! We're just trying to be realistic about the number of languages/platforms we support, and which we should add. So please do let people know you're interested.

**Comment by Chethan-21** [comment] 2018-08-07 12:08
@pasin 

Need your inputs on below.

Trying to use CBLListener as said by you earlier in the post using UIWebview. 
"I assumed that you are using couchbase-lite-phonegap-plugin. You could replace the following line by starting the CBLListener object and using the localhost URL instead of the internal NSURLProtocol URL."

Following is the code snippet

NSError *err = nil;
CBLListener* dblsnr = [[CBLListener alloc] initWithManager:(CBLManager*)cblManager port:(UInt16)0];
[dblsnr start:&err];

The HTTP Server is getting started on available port and getting the localhost URL.

But the problem is, we are not getting any response for any of our XMLHttpRequest.

Do we need to any to do any additional setup apart from the above.

Note: As part of CocoaHTTPServer Code, it says you must setDocumentRoot else HTTPServer will not serve anything

**Comment by pasin** [comment] 2018-08-07 15:27
@Chethan-21 Can you check a couple of things?

1. Check if you can connect to the listener via the real device/simulator IP Address and port from your Mac. This will help isolate to see if the issue is at listener or at WKWebView.

2. Apart from the first bullet, what if you are using UIWebView, can you access the listener?

3. When you are saying "not getting any response for any of our XMLHttpRequest", do you mean the request kept hanging without returning?

**Comment by Chethan-21** [comment] 2018-08-08 17:12
@pasin
1> I will give a try with real device IP Address, but i didn't tried this CBLListener using WKWebview. I was using UIWebview

2> I tried with UIWebview only. I could able to start the CBLListener.
On Success,  it will give me the local URL at which listener can be reached along with PORT number..
URL will be something like this
http://Chethans-iPhone6.local:5984/

3> XMLHttpRequest are getting TimeOUT


How do i make sure whether WebServer is running, i am not able to access this URL even using Safari browser?

**Comment by pasin** [comment] 2018-08-08 17:34
@Chethan-21 `http://Chethans-iPhone6.local:5984` is a boujour URL. You may try with either localhost or 127.0.0.1.

**Comment by DSaurabh** [comment] 2018-12-26 08:41
@pasin 

We are facing the same issue After app suspended state. After restart CBLListener works. But it is extra overhead to restart every time in the background. Is there any other way to determine CBLListener URL got the change to avoid restarting CBLListener of every time

**Comment by pasin** [comment] 2019-01-02 18:32
Currently `CBLListener` doesn't handle app backgrounding. Please restart the listener when the app becomes foreground.

**Comment by jayahariv** [comment] 2021-10-01 00:44
Closing 1.x issue!

**Closed by jayahariv** 2021-10-01 00:44 UTC
Labels: enhancement, reproduce/investigate, f: REST, icebox
