### ISSUE TITLE
Document reverts to original when deleted

### ISSUE THREAD

**Issue by GeorgeIvanov** [couchbase/couchbase-lite-ios#1788] opened 2017-06-17 13:05 UTC
https://forums.couchbase.com/t/document-reverts-to-original-when-deleted/9778

* Version:   CBL 1.4v
* Client OS: iOS 10.3.2
* Server:    CouchDB

**Comment by pasin** [comment] 2017-06-29 14:59
We couldn't reproduce the issue, and nobody has reported the same issue before. Can you provide a sample app, sync function, and steps to reproduce the issue?

**Comment by GeorgeIvanov** [comment] 2017-06-29 17:47
the config is like this: Couchbase Server, Sync Gateway, multiple iOS devices that have a pull and push replication; i create a document (original doc) on a device (the document has more properties: timestamps, etc, the main property is a an array which contains, let's say 3 objects); then i split the original document in 3 different documents(each receives an object from the main property of the original doc and the object is retrieved from the original docs array), when the original documents array remains without objects, the doc is deleted;

After deletion the original document disappears on all devices, then it pops back in on the device that it was created and it has the properties from rev1. On the other devices the document does not exist any more.

But it doesn't happen all the time, 1 out of 10 or 15.

**Comment by pasin** [comment] 2017-06-29 18:00
Can you check if the document that gets popped back has conflicts? You can use CBLDocument's --getConflictingRevisions method to check. I suspected that there is a conflict going on and the deletion revision also loses the conflict.

**Comment by GeorgeIvanov** [comment] 2017-06-29 18:10
there were no conflicts

**Comment by pasin** [comment] 2017-06-29 18:17
Sorry to ask again, would it be possible to abstract the logic to a sample app along with SGW config/sync function that we can use to reproduce the issue?

**Comment by skela** [comment] 2018-01-05 18:09
I'm seeing something similar, I call delete on a document, then soon after I call to query and the deleted record is returned in the results. :(

**Comment by snej** [comment] 2018-01-05 18:12
@skela Can you write that as a series of steps? I ask because the exact order things happen in is important here. (For example, if this is a live query, the query might have run a moment before you deleted the document, then was delivered to your thread asynchronously just after you deleted it. In this case the LiveQuery will update again in a second or so with the current results.)

**Comment by skela** [comment] 2018-01-05 18:20
@snej yeah sorry I'll try, I'm still looking at it , trying to figure out what's going wrong.
This is happening for some docs that do get updated quite often, but basically the device that's doing the deletion is completely re-installed, completely finished the syncing (push / pull continuous replication on the database), I dont use live queries, I'm doing this kind of stuff:

1) Download list of stuff from webserver
2) Do some calcs to see if couchbase needs updating
3) Based on the calcs, it will do a series of updates / inserts or deletes, in my state right now its doing just 3 deletes not in 1 transaction though, but 1 after another.
4) After all that is done, it queries and i get deleted records.

Im gonna keep looking, sorry to be so vague about it, I know how difficult it is.

**Comment by skela** [comment] 2018-01-05 18:28
This is even weirder... After trying to debug it, I've been "Refreshing" the docs, i.e. the steps i listed above, after many times, the delete count went from 3 to 1. In other words, when I first noticed the problem I had 3 documents that should have been deleted that get returned in my final query, now its just 1 document that should have been deleted.

If it helps I'm doing an AllDocs query.

**Comment by snej** [comment] 2018-01-05 18:43
In step 4, how are you querying? Do you run a CBLQuery, or is there a LiveQuery that you're observing changes to?
Are you checking for errors from the delete calls?
Turning on 'Database' and 'Query' logging will dump logs showing what's going on in the database; this might be helpful.

**Comment by skela** [comment] 2018-01-05 18:48
So yeah, I'm querying the allDocumentsQuery, not changing any of the defaults there apart from the startKey / endKey / inclusiveEnd and prefetch. I don't use LiveQuery at all. I do check for errors when deleting the record, the app reports the deletion as having succeeded, but when I query a short time afterwards it is still there.

 	guard let q = table.database?.createAllDocumentsQuery() else { return res }        
    q.startKey = groupID + "|"
    q.endKey = groupID + "}" // '}' is the character after '|' in ASCII order
    q.inclusiveEnd = false
    q.prefetch = true

I'll poke around.

**Comment by skela** [comment] 2018-01-05 20:44
Note to self: Version 2 of the pre-release notes state that:
	
>Default conflict resolver algorithm changes as follows:
	Deletion always wins.
	

Does that imply that version 1.4.x of the SDK does not have deletion always wins as default? Because I suppose that could maybe be the problem here. Possibly.

In any case, I've got a reproducible slimmed down project for you that I can send over, just need to know how :+1:

**Comment by skela** [comment] 2018-01-08 17:37
Bump...

**Comment by snej** [comment] 2018-01-10 19:53
>Does that imply that version 1.4.x of the SDK does not have deletion always wins as default? 

1.4 doesn't have automatic conflict resolvers; you have to detect resolve conflicts manually. If you don't, both conflicting revisions remain in the db but you will only see the 'default' (aka 'winning') one; the algorithm for picking that will never choose a deletion, so effectively the deletion loses.

You can email the test project to jens and pasin (domain couchbase dot com.)

**Comment by skela** [comment] 2018-01-19 08:14
Just for the record, I tested this in V2 of the SDK, with the same result. I also tested what would happen if I stuck the delete call in a for loop, and it took more than 8 calls to delete before the document was finally deleted.

**Comment by snej** [comment] 2018-01-19 18:29
This really really really sounds like you have a bunch of conflicts in that document, and each deletion you make decapitates one conflict revealing the next.

CBL 2 builds come with a handy `cblite`command-line tool for inspecting databases.  The `revs` subcommand will list a document's revisions. That should help you figure out what's going on here.

**Comment by skela** [comment] 2018-01-19 18:32
If it was just conflicts, then what is the solution ? Where do I solve it?

**Comment by snej** [comment] 2018-01-19 20:37
The CBL 1.x documentation describes how to find and resolve conflicts.

CBL 2 doesn't let you create local conflicts, but this brings up the question of what happens when an existing 1.x database with conflicts is upgraded to CBL 2. I don't think we've considered that before. I'll bring it up with the team.

**Comment by skela** [comment] 2018-01-20 12:37
With CBL 2 right around the corner, I don't think we are going to start doing that stuff locally on the phones anyway. Is there any way to resolve the conflicts server side?

**Comment by snej** [comment] 2018-01-22 20:09
Sure, same technique but use the REST API.

**Comment by pasin** [comment] 2018-02-22 19:52
I'm closing this issue now.

@skela if the issue is not related the conflicts, we could reopen the issue.
@GeorgeIvanov if you could provide more info, we could reopen the issue.

**Closed by pasin** 2018-02-22 19:52 UTC
Labels: icebox
