### ISSUE TITLE
Couldn't enable SQLite mmap warning message

### ISSUE THREAD

**Issue by pasin** [couchbase/couchbase-lite-ios#761] opened 2015-06-08 20:10 UTC
@mdfw reported to me via an email about this warning message. I don't know if this is an issue or not especially for SQLite v3.8.5 so I'm creating this ticket to track this.

```
11:29:07.242| Couchbase Lite using SQLite version 3.8.5 (2014-08-15 22:37:57 c8ade949d4a2eb3bba4702a4a0e17b405e9b6ace)
11:29:07.243| FYI, couldn't enable SQLite mmap
```

**Comment by snej** [comment] 2015-06-16 16:36
This isn't really a problem since mmap support is just a performance boost, but it's odd that it would happen. This appears to be on OS X 10.10 (it's exactly the SQLite version that's reported on my Mac) so mmap support is definitely enabled, but there's some error turning it on. Unfortunately the log message doesn't give the error code.

If this is reproducible for the originator, we could ask them to modify the code slightly to log the error code; it might be a clue.

**Comment by mdfw** [comment] 2015-06-16 16:57
@snej It's definitely still happening, but only in my test app that I wrote to dig into #758 . The code is pretty simple:
```
    [CBLManager enableLogging:@"Sync"];
    [CBLManager enableLogging:@"SyncVerbose"];

    self.manager = [CBLManager sharedInstance];
    NSError *error;
    self.db = [self.manager databaseNamed:@"test_db" error:&error];
```

The error shows up between manager setup and db setup. I'm happy to add something to log the error. Just let me know.

**Comment by snej** [comment] 2015-06-16 17:20
Weird that it only happens in that one app … yes, I'd be curious to know the SQLite error code. If you get a chance, could you change CBL_SQLiteStorage.m lines 92-93 to:
```objc
    int err = sqlite3_config(SQLITE_CONFIG_MMAP_SIZE, (SInt64)kSQLiteMMapSize, (SInt64)-1);
    if (err != SQLITE_OK)
        Log(@"FYI, couldn't enable SQLite mmap: error %d", err);
```
That will cause the error code to be logged. Thanks!

**Comment by mdfw** [comment] 2015-06-16 21:36
I will make the changes when I get a chance, but I realized that I didn't have the same logging flags on in my non-testing app. When I add;
```
    [CBLManager enableLogging:@"Sync"];
    [CBLManager enableLogging:@"SyncVerbose"];
```
I get the same messages:
```
Couchbase Lite using SQLite version 3.8.5 (2014-08-15 22:37:57 c8ade949d4a2eb3bba4702a4a0e17b405e9b6ace)
FYI, couldn't enable SQLite mmap
```
More when I can get to adding the extra logging.

**Comment by pasin** [comment] 2015-06-18 07:04
I couldn't reproduce the issue on both iPhone 6 device and simulator. The SQLite version is the same.

```
14:03:18.974| Couchbase Lite using SQLite version 3.8.5 (2014-08-15 22:37:57 c8ade949d4a2eb3bba4702a4a0e17b405e9b6ace)
```

**Comment by mdfw** [comment] 2015-06-29 01:47
I apologize for the delay in getting back to this. I was able to modify my local copy of CBL and run my test:
```
18:43:39.708| Couchbase Lite using SQLite version 3.8.5 (2014-08-15 22:37:57 c8ade949d4a2eb3bba4702a4a0e17b405e9b6ace)
18:43:39.709| FYI, couldn't enable SQLite mmap: error 21
```

**Comment by snej** [comment] 2015-06-29 02:35
Error 21 is SQLITE_MISUSE, "Library used incorrectly". It's weird that something like that would happen intermittently...

**Comment by mdfw** [comment] 2015-06-29 03:09
Sorry, no, it happens every time - I just didn't have the logging turned on. However, I just transferred my test app to a clean installed Yosemite running on a Parallels virtual machine and I'm not seeing the error. I'm guessing I've done something to my install (hey, this install has been around in some form or another since Mac OS 7). If you have suggestions on where to poke around, I'll take them, but we can assume this is a local issue to my machine.

**Comment by snej** [comment] 2015-06-29 16:07
OK, and since it's harmless anyway, let's close the issue.

**Closed by snej** 2015-06-29 16:07 UTC
Labels: in progress, needsmoreinfo, P3: low, S4: minor, size-medium

**Comment by philmitchell** [comment] 2016-02-13 00:42
I am seeing this error. On OS X 10.10.5.

**Comment by snej** [comment] 2016-02-17 01:56
It's not actually an error, just a note that we couldn't enable a specific SQLite optimization.

I wonder if the discrepancy has something to do with sandboxed vs non-sandboxed apps?

**Comment by numist** [comment] 2018-08-06 19:46
I was able to reproduce this and found where [SQLite was returning the error](https://www.sqlite.org/src/artifact/3c7f2159687af1b1):

``` c
/*
** This API allows applications to modify the global configuration of
** the SQLite library at run-time.
**
** This routine should only be called when there are no outstanding
** database connections or memory allocations.  This routine is not
** threadsafe.  Failure to heed these warnings can lead to unpredictable
** behavior.
*/
int sqlite3_config(int op, ...){
  va_list ap;
  int rc = SQLITE_OK;

  /* sqlite3_config() shall return SQLITE_MISUSE if it is invoked while
  ** the SQLite library is in use. */
  if( sqlite3GlobalConfig.isInit ) return SQLITE_MISUSE_BKPT;

  va_start(ap, op);
  switch( op ){
```

Looks like applications returning the `FYI, couldn't enable SQLite mmap: error 21` message are running in environments where some other piece of code (likely the application or another of its dependencies) has already caused `sqlite3_initialize` to be invoked.

Because `sqlite3_config` is global in nature (and is [not thread-safe!](https://www.sqlite.org/c3ref/config.html)), it's not very good to use from library code and should be avoided. Luckily, the `SQLITE_CONFIG_MMAP_SIZE` configuration can still be set on a per-connection basis by using [`PRAGMA [schema.]mmap_size(N)`](https://www.sqlite.org/pragma.html#pragma_mmap_size).
