### ISSUE TITLE
CBLPusher bad_request error 400 Missing digest in stub attachment

### ISSUE THREAD

**Issue by pahmed** [couchbase/couchbase-lite-ios#824] opened 2015-07-26 12:11 UTC
Hi, I see an error that frequently appears from the CBLPusher, which causes the document not to be synced with the sync-gateway

```
WARNING: CBLRestPusher[https://xxxxx.xxxxx.com:443/xxxx]: _bulk_docs got an error: {
    error = "bad_request";
    id = "contact:A1BB65C1-DC31-43F9-A1B3-9935CE6B6DCC";
    reason = "Missing digest in stub attachment \"small_picture:C2A50F35-BAC4-4CB7-9720-F8B5C55C1CD0\"";
    status = 400;
}
```
i checked the `_attachments` for that document and found that the digest for `small_picture:C2A50F35-BAC4-4CB7-9720-F8B5C55C1CD0` exists

whenever this error appears, i see this one also:
```
Domain=CBLHTTP Code=400 "400 bad_request" UserInfo=0x7fd437b233c0 {NSURL=https://xxxxx.xxxxx.com:443/xxxx/contact:A1BB65C1-DC31-43F9-A1B3-9935CE6B6DCC, NSLocalizedFailureReason=bad_request, NSLocalizedDescription=400 bad_request}
```

The error happens on version `1.1`, i tried also the master branch and the same problem exists, BUT this problem does not happen in version `1.0.3`

This is the document:

```
{
    "_attachments" =     {
        "large_picture:7FCEE8FB-97F4-4D11-80A6-08DD787B3A4B" =         {
            "content_type" = "image/jpeg";
            digest = "sha1-7zigjZkX0y9ZhpW2ENt85ldePQI=";
            length = 826850;
            revpos = 1;
            stub = 1;
        };
        "small_picture:C2A50F35-BAC4-4CB7-9720-F8B5C55C1CD0" =         {
            "content_type" = "image/jpeg";
            digest = "sha1-+Lgl0qT8Vt2YDxjqCn+e4lnfgSg=";
            length = 15451;
            revpos = 1;
            stub = 1;
        };
    };
    "_id" = "contact:A1BB65C1-DC31-43F9-A1B3-9935CE6B6DCC";
    "_rev" = "5-452d89f8849bab4758014458e7870e55";
    act = "contact:9cbc445b-61cd-4ff5-aef7-e0019e91b7e4_9cbc445b-61cd-4ff5-aef7-e0019e91b7e4";
    acn =     {
        primary =         {
            "_state" = 0;
            first = xxxx;
            last = xxxx;
            modifiedAt = 1437664925795;
            visibility = 2;
        };
    };
    ad =     (
    );
    av =     {
        "_state" = 6;
        large = "large_picture:7FCEE8FB-97F4-4D11-80A6-08DD787B3A4B";
        modifiedAt = 1437828543453;
        small = "small_picture:C2A50F35-BAC4-4CB7-9720-F8B5C55C1CD0";
        visibility = 2;
    };
    da =     (
    );
    docState = new;
    em =     (
                {
            "_state" = 0;
            isActive = 1;
            modifiedAt = 12345;
            primary = 0;
            type = xxxx;
            value = "xxxx";
            verified = 1;
            visibility = 2;
        }
    );
    inm =     (
    );
    isA = 1;
    isL = 0;
    isO = 0;
    lUBy = n;
    lIds =     (
        "contact:0AEA67FF-C924-4F86-BE32-F60D351996E2",
        "contact:9cbc445b-61cd-4ff5-aef7-e0019e91b7e4_9cbc445b-61cd-4ff5-aef7-e0019e91b7e4"
    );
    locations =     {
        c =         {
            "_state" = 0;
            country = xxx;
            modifiedAt = 23123123;
            timezone = "xxx/xxx";
            visibility = 2;
        };
        h =         {
            "_state" = 0;
            country = xxx;
            modifiedAt = 24234234;
            timezone = "xxx/xxx";
            visibility = 2;
        };
    };
    names =     {
        primary =         {
            "_state" = 6;
            first = xxxx;
            last = xxxx;
            modifiedAt = 1437824591807;
            visibility = 2;
        };
    };
    organizations =     (
                {
            "_state" = 6;
            department = "";
            isActive = 1;
            modifiedAt = 234234234;
            name = "";
            title = "";
            visibility = 2;
        }
    );
    owner = "9cbc445b-61cd-4ff5-aef7-e0019e91b7e4";
    ph =     (
                {
            "_state" = 0;
            isActive = 1;
            mo = "xxxx";
            modifiedAt = 1437664925792;
            primary = 0;
            type = xxxx;
            value = "xxxxxx";
            verified = 0;
            visibility = 2;
        },
                {
            "_state" = 0;
            mo = "xxxxx";
            modifiedAt = 1437824591813;
            primary = 0;
            type = mo;
            value = "xxxx";
            verified = 0;
            visibility = 2;
        },
                {
            "_state" = 0;
            isActive = 1;
            modifiedAt = 1437817747736;
            primary = 0;
            type = mo;
            value = "xxxx";
            verified = 0;
            visibility = 2;
        },
                {
            "_state" = 0;
            isActive = 1;
            modifiedAt = 1437825168292;
            primary = 0;
            type = mo;
            value = "xxxx";
            verified = 0;
            visibility = 2;
        }
    );
    related =     (
    );
    rena =     (
        "xxxx",
        "xxxx"
    );
    soc =     (
                {
            "_state" = 0;
            display = "xxxx";
            id = xxxx;
            isActive = 1;
            modifiedAt = 1437664925802;
            profilePictureURL = "xxxx";
            provider = xxxx;
            verified = 1;
            visibility = 2;
        }
    );
    type = contact;
    urls =     (
    );
}
```

**Comment by snej** [comment] 2015-07-26 16:18
This might be a Sync Gateway bug. Could you paste the server's copy of the document? You can find that by doing an HTTP GET of `https://xxxxx.xxxxx.com:443/xxxx/contact:A1BB65C1-DC31-43F9-A1B3-9935CE6B6DCC?revs=true`.

**Comment by pahmed** [comment] 2015-07-26 17:08
This is what i get for this document, i tried other docs and they are returned successfully
{
error: "Forbidden",
reason: "forbidden"
}

**Comment by snej** [comment] 2015-07-26 17:21
Use the admin port then.

**Comment by pahmed** [comment] 2015-07-27 11:42
I have missed the original document from CBL by accident, but the issue happened with another document, i tried to get it from the sync gateway and it returned `Forbidden`, but when i tried to get it from the server this is what i got

```
 {
  "_deleted": true,
  "_sync": {
    "rev": "2-9f23acb3d9f4c39f717e2a4ecf09e478",
    "flags": 1,
    "sequence": 190873,
    "recent_sequences": [
      190871,
      190873
    ],
    "history": {
      "revs": [
        "2-9f23acb3d9f4c39f717e2a4ecf09e478",
        "1-6faf0ee084a17645710874f9979d93ee"
      ],
      "parents": [
        1,
        -1
      ],
      "deleted": [
        0
      ],
      "bodies": [
        "",
        ""
      ],
      "channels": [
        null,
        [
          "bfdec78a-b273-4977-a851-f7a960071965"
        ]
      ]
    },
    "channels": {
      "bfdec78a-b273-4977-a851-f7a960071965": {
        "seq": 190873,
        "rev": "2-9f23acb3d9f4c39f717e2a4ecf09e478",
        "del": true
      }
    },
    "time_saved": "2015-07-26T17:00:59.409754651Z"
  }
} 
```
I found the document is deleted, btw in some cases i do something that could be the reason for this problem, i.e. in some cases i delete the document and then recreate with the same old id.

**Comment by snej** [comment] 2015-07-27 16:36
This issue is about the "Missing digest in stub attachment" error. To troubleshoot it I need to see both the client and server versions of a document that gets this error when replicating.

**Comment by pasin** [comment] 2015-07-30 16:58
@pahmed Are you using CouchDb or SyncGateway? There was a similar issue (#817) that has the exact same error, "Missing digest in stub attachment" but the issue happens only with CouchDB.

**Comment by zgramana** [comment] 2015-07-31 22:33
@pahmed thanks for the report. We still don't have enough information to move forward, so we'll close this in 7 days if we don't hear back.

**Comment by pahmed** [comment] 2015-07-31 22:57
I'm using sync gateway, this is the same problem for different document, i've included the client & server versions for the document

WARNING: CBL_Pusher[https://xxx.xxx.com:443/xxx]: _bulk_docs got an error: {
    error = "bad_request";
    id = "profile:fe9356eb-0359-4902-b685-93def64d7349";
    reason = "Missing digest in stub attachment \"small_picture:A7165BE2-0E6C-4CCE-BB95-2DB546833D31\"";
    status = 400;
}

Error Domain=CBLHTTP Code=400 "400 bad_request" UserInfo=0x170f7250 {NSURL=https://xxx.xxx.com:443/xxx/profile:fe9356eb-0359-4902-b685-93def64d7349, NSLocalizedFailureReason=bad_request, NSLocalizedDescription=400 bad_request}


Client version:
```
{
    "_attachments" =     {
        "large_picture:7BD0D1F2-0875-434B-8B6D-580EA0A3E79E" =         {
            "content_type" = "image/jpeg";
            digest = "sha1-z6b81tk6EhsR1eDCEya79YZxpSc=";
            length = 60293;
            revpos = 2;
            stub = 1;
        };
        "small_picture:A7165BE2-0E6C-4CCE-BB95-2DB546833D31" =         {
            "content_type" = "image/jpeg";
            digest = "sha1-z6b81tk6EhsR1eDCEya79YZxpSc=";
            length = 60293;
            revpos = 2;
            stub = 1;
        };
    };
    "_id" = "profile:fe9356eb-0359-4902-b685-93def64d7349";
    "_rev" = "13-5a614058a186d9b22c519bc44794159f";
    "_revisions" =     {
        ids =         (
            7d2c424e33eef5251e2ee79e5da395a1,
            1d99391b4125a141e57c9b9c3b78256c,
            e558748924cd7d0ebdef9c941acd7149,
            eba8eb0c572c9a6febfdba4f29e053df,
            901c94663d41a644d5afb33225c01f74,
            d8b024791e3dd52d469d88bf7714abe5,
            a28ea27834dc41a7b96aba5a07f99205,
            e082784e9e292cd1118abb6b3950034f,
            ad77b8bc6a85da011af9177cc0015c2f,
            29624f4d599ea57a874006d8b579c96a,
            c7c6c71ec400d8dcb3ba1c01c7791121
        );
        start = 11;
    };
    avatars =     {
        "_state" = 0;
        isRandom = 0;
        large = "large_picture:7BD0D1F2-0875-434B-8B6D-580EA0A3E79E";
        modifiedAt = 1438168194236;
        small = "small_picture:A7165BE2-0E6C-4CCE-BB95-2DB546833D31";
        visibility = 2;
    };
    createdAt = 1438168143882;
    docState = dirty;
    emails =     (
                {
            "_state" = 0;
            modifiedAt = 1438168143448;
            primary = 0;
            type = home;
            value = "xxx";
            verified = 1;
            visibility = 2;
        },
                {
            "_state" = 7;
            modifiedAt = 1438170704332;
            primary = 0;
            type = personal;
            value = "wwww@w.w";
            verified = 0;
            visibility = 2;
        },
                {
            "_deleted" = 1;
            "_state" = 4;
            modifiedAt = 1438170601075;
            primary = 0;
            type = personal;
            value = "q@q.qqq";
            verified = 0;
            visibility = 2;
        }
    );
    isActive = 0;
    locations =     {
        current =         {
            "_state" = 0;
            country = xxx;
            modifiedAt = 1438168143476;
            timezone = "Europe/Amsterdam";
            visibility = 2;
        };
        home =         {
            "_state" = 0;
            country = xxx;
            modifiedAt = 1438168143476;
            timezone = "Europe/Amsterdam";
            visibility = 2;
        };
    };
    names =     {
        primary =         {
            "_state" = 0;
            first = xxx;
            last = xxx;
            modifiedAt = 1438168143475;
            visibility = 2;
        };
    };
    organizations =     (
                {
            "_state" = 0;
            department = "";
            modifiedAt = 1438168641337;
            name = "";
            title = "";
            visibility = 2;
        }
    );
    phones =     (
                {
            "_state" = 0;
            mobile = "+201005219056";
            modifiedAt = 1438168143464;
            primary = 0;
            type = mobile;
            value = "xxx";
            verified = 0;
            visibility = 2;
        }
    );
    socialAccounts =     (
                {
            "_state" = 0;
            display = "xxx";
            id = 1018908587;
            modifiedAt = 1438168143490;
            profilePictureURL = "xxx";
            provider = xxx;
            verified = 1;
            visibility = 2;
        }
    );
}
```
===================

Server version:
```
{
  "_attachments": {
    "large_picture:7BD0D1F2-0875-434B-8B6D-580EA0A3E79E": {
      "content_type": "image/jpeg",
      "digest": "sha1-z6b81tk6EhsR1eDCEya79YZxpSc=",
      "length": 60293,
      "revpos": 2,
      "stub": true
    },
    "small_picture:A7165BE2-0E6C-4CCE-BB95-2DB546833D31": {
      "content_type": "image/jpeg",
      "digest": "sha1-z6b81tk6EhsR1eDCEya79YZxpSc=",
      "length": 60293,
      "revpos": 2,
      "stub": true
    }
  },
  "_id": "profile:fe9356eb-0359-4902-b685-93def64d7349",
  "_rev": "13-fd8f6f260da721e9838cad9a64088770",
  "avatars": {
    "_state": 0,
    "isRandom": false,
    "large": "large_picture:7BD0D1F2-0875-434B-8B6D-580EA0A3E79E",
    "modifiedAt": 1438168194236,
    "small": "small_picture:A7165BE2-0E6C-4CCE-BB95-2DB546833D31",
    "visibility": 2
  },
  "createdAt": 1438168143882,
  "docState": "pristine",
  "emails": [
    {
      "_state": 0,
      "modifiedAt": 1438168143448,
      "primary": false,
      "type": "home",
      "value": "xxx",
      "verified": true,
      "visibility": 2
    },
    {
      "_deleted": true,
      "_state": 4,
      "modifiedAt": 1438170601075,
      "primary": false,
      "type": "personal",
      "value": "q@q.qqq",
      "verified": false,
      "visibility": 2
    },
    {
      "_state": 0,
      "modifiedAt": 1438170704332,
      "primary": false,
      "type": "personal",
      "value": "wwww@w.w",
      "verified": false,
      "visibility": 2
    }
  ],
  "isActive": 0,
  "locations": {
    "current": {
      "_state": 0,
      "country": "xxx",
      "modifiedAt": 1438168143476,
      "timezone": "Europe/Amsterdam",
      "visibility": 2
    },
    "home": {
      "_state": 0,
      "country": "xxx",
      "modifiedAt": 1438168143476,
      "timezone": "Europe/Amsterdam",
      "visibility": 2
    }
  },
  "names": {
    "primary": {
      "_state": 0,
      "first": "xxx",
      "last": "xxx",
      "modifiedAt": 1438168143475,
      "visibility": 2
    }
  },
  "organizations": [
    {
      "_state": 0,
      "department": "",
      "modifiedAt": 1438168641337,
      "name": "",
      "title": "",
      "visibility": 2
    }
  ],
  "phones": [
    {
      "_state": 0,
      "mobile": "xxx",
      "modifiedAt": 1438168143464,
      "primary": false,
      "type": "mobile",
      "value": "xxx",
      "verified": false,
      "visibility": 2
    }
  ],
  "socialAccounts": [
    {
      "_state": 0,
      "display": "xxx",
      "id": "1018908587",
      "modifiedAt": 1438168143490,
      "profilePictureURL": "xxx",
      "provider": "xxx",
      "verified": true,
      "visibility": 2
    }
  ]
}
```

**Comment by pasin** [comment] 2015-08-03 18:59
I tried to replicate similar revision structures on both client and sync gateway, but I couldn't reproduce the issue. What sync gateway version are you using?

**Comment by pasin** [comment] 2015-08-03 19:04
Also you have mentioned that " in some cases i delete the document and then recreate with the same old id.". In general it should be fine as it should create a new revision based on the previous revision when you deleted the document. But if you could explain a little bit more on how you does this (e.g. showing code snippets), it would be helpful just in case there is something to discuss.

**Comment by snej** [comment] 2015-08-03 19:23
Yeah, there's definitely a conflict — the client has revision `13-5a614058a186d9b22c519bc44794159f`while the server has `13-fd8f6f260da721e9838cad9a64088770`. That shouldn't cause an error of course, but it may not be what you wanted, @pahmed .

**Comment by pahmed** [comment] 2015-08-05 11:11
@pasin i'm using sync gateway version 1.1, i have an object `Profile` which has a reference to the CBLDocument and i delete the document using `[profile.document deleteDocument:NULL]`, after that i create another `Profile` object which has the same id of the deleted one, then i insert it to couch with code similar to this:
```objc
CBLDocument *doc = [database documentWithID:OLD_DOCUMENT_ID];
// Then update the document 
[doc update:^BOOL(CBLUnsavedRevision *revesion) {
    [revesion.properties addEntriesFromDictionary:PROPERTIES_FOR_THE_NEW_DOC];
    return YES;
} error:&error];
```

@snej yes sometimes conflicts happen, and usually conflict is handled from the client side, the problem here is that the replicator was not able to retrieve the server version after the bad_request error appeared.

**Comment by pasin** [comment] 2015-08-05 18:49
@pahmed Thanks for more information. I was able to reproduce the issue now. I reproduced the issue by updating the deleted document with the same attachment added to the document prior deletion and pushing that update to the sync gateway.

Sync Gateway Error:
```
2015-08-05T11:43:56.704-07:00 	BulkDocs: Doc "doc1" --> 400 Missing digest in stub attachment "attach1" (400 Missing digest in stub attachment "attach1")
```

Couchbase Lite Error:
```
11:43:56.706‖ WARNING: CBLRestPusher[http://127.0.0.1:4984/db]: _bulk_docs got an error: {
    error = "bad_request";
    id = doc1;
    reason = "Missing digest in stub attachment \"attach1\"";
    status = 400;
}
2015-08-05 11:43:56.717 CBL Test[36118:2655319] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Warn() was called: CBLRestPusher[http://127.0.0.1:4984/db]: _bulk_docs got an error: <CFBasicHash 0x7fbe59c1e840 [0x10fc9a180]>{type = immutable dict, count = 4,
entries =>
	0 : <CFString 0x7fbe59c1efe0 [0x10fc9a180]>{contents = "status"} = <CFNumber 0xb000000000001903 [0x10fc9a180]>{value = +400, type = kCFNumberSInt64Type}
	1 : <CFString 0x7fbe59c1f100 [0x10fc9a180]>{contents = "id"} = <CFString 0x7fbe59c10e70 [0x10fc9a180]>{contents = "doc1"}
	3 : <CFString 0x7fbe59c1cb90 [0x10fc9a180]>{contents = "reason"} = <CFString 0x7fbe59c1efb0 [0x10fc9a180]>{contents = "Missing digest in stub attachment "attach1""}
	5 : <CFString 0x7fbe5861d3b0 [0x10fc9a180]>{contents = "error"} = <CFString 0x7fbe59c1ad80 [0x10fc9a180]>{contents = "bad_request"}
}
'
*** First throw call stack:
(
	0   CoreFoundation                      0x000000010f9eec65 __exceptionPreprocess + 165
	1   libobjc.A.dylib                     0x000000010f687bb7 objc_exception_throw + 45
	2   CoreFoundation                      0x000000010f9eeaca +[NSException raise:format:arguments:] + 106
	3   CBL Test                            0x000000010ce1e325 Warn + 565
	4   CBL Test                            0x000000010cd9e403 __40-[CBLRestPusher uploadBulkDocs:changes:]_block_invoke + 547
	5   CBL Test                            0x000000010cd914c4 __61-[CBLRestReplicator sendAsyncRequest:path:body:onCompletion:]_block_invoke + 452
	6   CBL Test                            0x000000010cdae271 -[CBLRemoteRequest respondWithResult:error:] + 209
	7   CBL Test                            0x000000010cdb08bc -[CBLRemoteJSONRequest connectionDidFinishLoading:] + 732
	8   CFNetwork                           0x000000010d950d6c __65-[NSURLConnectionInternal _withConnectionAndDelegate:onlyActive:]_block_invoke + 69
	9   CFNetwork                           0x000000010d950d10 -[NSURLConnectionInternal _withConnectionAndDelegate:onlyActive:] + 199
	10  CFNetwork                           0x000000010d950e77 -[NSURLConnectionInternal _withActiveConnectionAndDelegate:] + 48
	11  CFNetwork                           0x000000010d820347 ___ZN27URLConnectionClient_Classic26_delegate_didFinishLoadingEU13block_pointerFvvE_block_invoke + 107
	12  CFNetwork                           0x000000010d8eda71 ___ZN27URLConnectionClient_Classic18_withDelegateAsyncEPKcU13block_pointerFvP16_CFURLConnectionPK33CFURLConnectionClientCurrent_VMaxE_block_invoke_2 + 273
	13  CFNetwork                           0x000000010d80b5d6 _ZN19RunloopBlockContext13_invoke_blockEPKvPv + 72
	14  CoreFoundation                      0x000000010f8f5354 CFArrayApplyFunction + 68
	15  CFNetwork                           0x000000010d80b497 _ZN19RunloopBlockContext7performEv + 133
	16  CFNetwork                           0x000000010d80b2d6 _ZN17MultiplexerSource7performEv + 256
	17  CFNetwork                           0x000000010d80b0ec _ZN17MultiplexerSource8_performEPv + 72
	18  CoreFoundation                      0x000000010f922431 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 17
	19  CoreFoundation                      0x000000010f9182fd __CFRunLoopDoSources0 + 269
	20  CoreFoundation                      0x000000010f917934 __CFRunLoopRun + 868
	21  CoreFoundation                      0x000000010f917366 CFRunLoopRunSpecific + 470
	22  Foundation                          0x000000010effbf92 -[NSRunLoop(NSRunLoop) runMode:beforeDate:] + 275
	23  CBL Test                            0x000000010cd89f6e -[CBL_RunLoopServer runServerThread] + 542
	24  Foundation                          0x000000010effa09d __NSThread__main__ + 1194
	25  libsystem_pthread.dylib             0x00000001109ce268 _pthread_body + 131
	26  libsystem_pthread.dylib             0x00000001109ce1e5 _pthread_body + 0
	27  libsystem_pthread.dylib             0x00000001109cc41d thread_start + 13
)
libc++abi.dylib: terminating with uncaught exception of type NSException
```

**Comment by pahmed** [comment] 2015-08-05 19:34
Great

**Comment by pasin** [comment] 2015-08-05 20:43
The issue seems to be at the Sync-Gateway side. SyncGateway looks for the attachment from its intermediate parent but not upper than that. I have created an issue on the SyncGateway as https://github.com/couchbase/sync_gateway/issues/1034.

@adamcfraser , could you help looking at this?

**Closed** 2015-08-07 22:20 UTC
Labels: f: Replication
