### ISSUE TITLE
Documents sometimes not saved

### ISSUE THREAD

**Issue by marbetschar** [couchbase/couchbase-lite-ios#962] opened 2015-10-27 13:43 UTC
We got a strange issue over here:

For any unknown reason some documents are not saved to the couchbase lite database when mutated. We only noticed this, when the user updates to a new version of the app and then suddenly are some (previously selected) relationships missing.

For example we got an Address Model containing a country defined as follows:

```
@objc(Address)
class Address: Model{
    ...
    @NSManaged var country: Country?
    ...
}
```

By an end user now, this country is now set to ```nil``` - but was for sure set before the app was updated. Also, the update process did not mutate any document in the database. Any Idea why this is happening?

*As a quick fix*
Is there a possibility to make sure all unsaved documents are stored to the database before the application enters the background? For example by adding some custom behaviour to ```applicationDidEnterBackground``` in AppDelegate?

**Comment by snej** [comment] 2015-10-27 16:50
By default, CBLModel objects only save changes to the database when explicitly told to. As a convenience, NSDatabase has a `-saveAllModels:` method that calls save on every model with changes.

You can enable autosave on individual objects, and you can set the autosave delay. There's also an `-autosaveAllModels:` method that immediately triggers autosave on all models.

> Is there a possibility to make sure all unsaved documents are stored to the database before the application enters the background?

`-autosaveAllModels:` is called when the app enters the background. If you don't want autosave but do want this behavior, you can easily call `-saveAllModels` from your app delegate's notification handler.

**Comment by snej** [comment] 2015-10-27 16:52
Oh, and `-saveAllModels` is called when a database is closed. So make sure to close your database(s) when the app quits. (We can't do it for you because there are race conditions — CBL might receive the app-will-quit notification before your app delegate does, so it can't close the databases or your delegate might try to write to an already-closed db.)

Is the issue you're reporting something caused by not saving models? Or is there something else wrong?

**Comment by marbetschar** [comment] 2015-10-28 04:38
Cool! Seems like ```saveAllModels``` is what I'm looking for! Just one question: How may I make sure, only models are saved to the database which are containing any value?

Because I've got the use case when the user adds for example a new expense, the input form is presented to him; populated by a new & empty model (on an edit the model is loaded before).

Now, if the user sends the app to the background an empty (apart from type='Expense') model is stored to the database.

I've seen there is also an ```unsavedModels``` property on the database, so is the following code correct for the needed behaviour?

```
func applicationWillTerminate(application: UIApplication) {
   do{
      try database.close()
			
      } catch let error as NSError{
         NSLog(error.localizedDescription)
      }
}

func applicationDidEnterBackground(application: UIApplication) {
	let unsavedModels = database.unsavedModels as! [CBLModel]

	for unsavedModel in unsavedModels{
		let properties = unsavedModel.propertiesToSave()
		
		for (k,_) in properties{
			if let key = k as? String, let firstCharacter = key.characters.first{
				if firstCharacter != "_" && key != "type" {
					do {
						try unsavedModel.save()
						NSLog("Saved model with properties \(properties)")
						
					} catch let error as NSError {
						NSLog(error.localizedDescription)
					}
					break
				}
			}
		}
	}
}
```

**Comment by marbetschar** [comment] 2015-10-28 04:42
I'm not quite sure what is causing the issue; what I'm seeing is, that sometimes not all models get stored in the database.

As I was not closing the database at all till now: Can this lead to a data loss when ```database.close()``` is not called on ```applicationWillTerminate```?

**Comment by snej** [comment] 2015-10-28 05:08
>How may I make sure, only models are saved to the database which are containing any value?

Newly created models aren't marked as needing to be saved. If `-saveAllModels` is saving those, then they must have gotten marked as dirty somehow. Did you set a property earlier?

>As I was not closing the database at all till now: Can this lead to a data loss when database.close() is not called on applicationWillTerminate?

Yes, if you had models with unsaved changes, and didn't call `-saveAllModels` before quitting.

**Comment by snej** [comment] 2015-10-28 05:10
Update: You probably set the `type` property after creating the new model. That's enough to mark it as dirty. It might be better to set the `type` property in a `propertiesToSave` override.

**Comment by snej** [comment] 2015-10-30 22:25
Let me know if you're still seeing problems after adding the necessary save calls.

**Comment by zgramana** [comment] 2015-11-06 23:15
@marbetschar will close in 7 days unless there are further updates.

**Comment by marbetschar** [comment] 2015-11-13 14:17
The issue seems now only to occur when the App crashes. I still see an occasional dataloss then.

How to close the database just before the app crashes?
Is there some sort of event fired just before?

Also would it be a good practice to save any unsaved changes in a didReceiveMemoryWarning event?

**Comment by snej** [comment] 2015-11-13 19:37
>How to close the database just before the app crashes?
>Is there some sort of event fired just before?

You can't do that. If the app crashes, it's by definition in a bad state and it would be a bad idea to try to do anything, especially if it involves updating persistent data. It is possible to get called immediately when the crash occurs using a Unix signal handler, but there's very little you can safely do in one of those and they are notoriously hard to work with.

>Also would it be a good practice to save any unsaved changes in a didReceiveMemoryWarning event?

Yes. Especially because the OS may soon decide to terminate your app without notice if it doesn't reduce its memory usage. (Note: This isn't a crash. It's just the kernel making your process go away.)

**Closed by snej** 2015-11-13 19:37 UTC
Labels: core-data, f: Model, needsmoreinfo
