### ISSUE TITLE
CBLIS : Data loss

### ISSUE THREAD

**Issue by cflorion** [couchbase/couchbase-lite-ios#966] opened 2015-10-30 10:56 UTC
We have had a problem since we started working with Couchbase-lite-iOS. We have crashes and data loss, but we kind of had saved that for later since we had more important bugs to deal with. But no we have been kind of stuck for the last few weeks/months since we can't put our app in production for two reasons: the performance on the device are not good enough (that's the another problem, the next) and the crashes/data loss mentioned above. We are out of ideas, so maybe someone has some for us :)

(We use CBLIncrementalStore, CBL-iOS (latest commit on the master branch) and CB Sync Gateway 1.1.1).

1. We have a Core Data Model. In the model, we use  Core Data object validation (https://developer.apple.com/library/ios/documentation/Cocoa/Conceptual/CoreData/ObjectValidation.html). We use it the simple way by just unchecking the "optional" box on properties and relationships of Entities in the Model Editor UI in Xcode. This is quite handy since the app crashes (and produces a detailed exception) when one of theses constraints are not fulfilled. But the problem is that we have random crashes telling us that some relationship object is missing. For example we have a Tax entity. We tried to look for problems in our implementation but we realized that in our app we have no way nor code to delete a Tax managed object in our code...

2. Sometimes the app crashes because an object is saved with all its properties being nil. The save is therefore prevented by the Core Data Object Validation. We relaunch the app, and all seems fine again after a replication.

3. One more example. We have another to-many relationship (users) where we forgot to uncheck the "optional" box. So this obviously doesn't produce crashes. But this is via our app UI that we noticed the problem. While debugging several times, once we saw that all users were missing in the database (via a core data fetch request) and another time only one user was missing.

We are trying to find a pattern to reproduce this bug, but this is quite difficult. It looks like it gets worse overtime, but not sure of it... We're digging.

Could this be related to the number of revisions that is too high ?
Have you ever heard something like this ?

Thanks! 
:)

**Comment by pasin** [comment] 2015-10-30 17:16
> 1. But the problem is that we have random crashes telling us that some relationship object is missing. For example we have a Tax entity. We tried to look for problems in our implementation but we realized that in our app we have no way nor code to delete a Tax managed object in our code...

Would it be possible to scope this down? For example, can you make a small simple app that I can use to reproduce the missing relationship or crash (even though I need to run multiple times to reproduce)?

> 2. Sometimes the app crashes because an object is saved with all its properties being nil. The save is therefore prevented by the Core Data Object Validation. We relaunch the app, and all seems fine again after a replication.

I couldn't think of the reason why the properties being nil. The same as #1, can we scope this down into something / test app that we can reproduce?

> While debugging several times, once we saw that all users were missing in the database (via a core data fetch request) and another time only one user was missing.

This is the same as #1? Again, same as #1, can we scope this down into something / test app that we can reproduce?

**Comment by pasin** [comment] 2015-10-30 17:23
One question, if using only main context model (I knew it's slow), will it help on any issues? Can you also check that?

**Comment by cflorion** [comment] 2015-10-30 21:48
Okay good idea. I'll try to make a sample app.
Thanks!

**Comment by zgramana** [comment] 2015-11-06 23:11
Potential duplicate of #958.

**Comment by mastohhh** [comment] 2015-11-12 15:56
We found something interesting : missing objects have in common to have a lot of revisions.

When we kill the app and relaunch it : the object is still missing, that means it's not a core data context problem.

When we uninstall reinstall the app, objects reappeared !

And more strange : when we launch the app 24 or 48 hours after objects disappeared, objects comes back.

My first thought is : it's a `CBLReplication` problem. The continuous replication sometimes missed something. (I read that older revisions are marked as deleted ...) And 24/48h after when we launch the app, the replication gets the full data.

It's not a part that I understand well (now I good in CBLIncrementalStore :smile:) and I hope you understand me.

**Comment by mastohhh** [comment] 2015-11-12 17:18
@pasin I don't understand the `defaultConflictHandler`.

Why do you create a new revision for each revision you loop into ?

``` objc
CBLUnsavedRevision *newRev = [rev createRevision];
newRev.isDeletion = YES;
if (![newRev saveAllowingConflict: &error])
    return NO;
```

And why this revision is marked as `isDeletion` ?

**Comment by pasin** [comment] 2015-11-13 06:45
Basically it merges all of the conflicting revision.

1. It loops to create a new `delete` revision to each conflicting revision except the first one on the list which is the current winning revision.
2. At the end, it creates a new revision of the merged properties of all conflicting revisions to the first revision on the list.

**Comment by pasin** [comment] 2015-11-13 06:55
> And more strange : when we launch the app 24 or 48 hours after objects disappeared, objects comes back.

Is it possible that there are new revisions of those missing documents coming from the replication?

**Comment by pasin** [comment] 2015-11-13 06:56
One thing that I'm not quite sure when looking at the code is that what dispatch queue that the default conflict handler is running on. It should be running on the same dispatch queue as the root context.

**Comment by mastohhh** [comment] 2015-11-19 09:57
Yes, there are new revisions of those missing documents coming from the replication that gets document back.

When we loss a document, every devices that are in sync get the document lost, at the same time. When we add a new device with a fresh install, the document is not missing on it.

Have you heard something like that in couchbase-lite-ios without CBLIS ? Does it can come from `sync_gateway` ? Or the `_change` endpoint ?

If it's a pure CBLIS bug, what happens if we don't delete old revisions in the `defaultConflictHandler` ?

**Comment by pasin** [comment] 2015-11-21 04:24
This is like the document get either deleted or purged from the device. I have never heard this issue with cbl or sync gateway before.

If you know the doc id of the missing doc, we can quickly check the status of the doc directly from the SQLite REVS table. If the doc rev is not there, it means that yhe doc got purged somehow by client code. SyncGateway cannot purge the doc.

As CBLIS doesn't compact the DB, leaving all conflicting revs will not change anything.

**Comment by pasin** [comment] 2015-12-11 18:33
@mastohhh Have you found the root cause of the issue or new information?

**Comment by mastohhh** [comment] 2015-12-11 19:31
No. Unfortunately we don't have something new. This is a huge problem for us. The objects that disappeared are the ones with a lot of revision, the ones that are important. For example a User object that disappeared and we can't login in our app. 

I saw you did recently lots of commits about queues and contexts. I will give the master version to our testers next week to see if things are better.

**Comment by pasin** [comment] 2015-12-11 22:52
Also if you somehow have perform any database operations (e.g. purge or delete) outside CBLIS, please ensure to call that on the same dispatch queue as the root context dispatch queue.

**Comment by pasin** [comment] 2016-03-04 02:38
@mastohhh Could you please try with the latest fix in the [dev](https://github.com/couchbase/couchbase-lite-ios/tree/dev) branch?  The fix has fixed the threading / dispatch queue issue which might be the root cause of all these.

**Closed** 2016-04-08 22:27 UTC
Labels: bug, core-data, needsmoreinfo, reproduce/investigate
