### ISSUE TITLE
Replication goes to IDLE state unexpectedly on certain WiFi networks

### ISSUE THREAD

**Issue by tleyden** [couchbase/couchbase-lite-ios#1687] opened 2017-03-27 19:22 UTC
I was forwarded the following issue report via email.

It to me feels like a couchbase lite issue based on the description, so I'm defaulting here.  If it looks more like  a Sync Gateway issue, I can move it over there.

From @HodGreeley: 

> The gist is iOS replications are hanging after 5 minutes of idle time, and sockets are hanging around on sync gateway for a very long time.  They seem to have isolated it to happening when using a particular wifi.

From original reporter:

> I was noticing the ESTABLISHED sockets, I think the socket "FIN_WAIT1" state while the app is still in fore ground and the sync stopped

> We did several rounds of testing and following are our observations. For all tests we bypassed Nginx and connected directly to sync gateway on 4984 (without SSL) to rule out all other possible issues.
> 
> - If there is no data to be synced for 5 min and app remains in fore ground then the sync is idle state and no changes to the docs are synced from server.
> - If we stop replication and start it again then it again works for about 5min.
> - Once the issue starts, the socket on the server remains in "ESTABLISHED" state for a very long time. During that time if I stop replication on the app, it has no effect on the socket, it remains in "ESTABLISHED" state.
> - How ever if I stop replication before 5min then the socket is properly released immediately.
> - This means both app and server did not detect the problem for a very long time.
> - The issues are noticed on one particular wifi connection and working fine on 4 other connections (including wifi and 4G).
>
> From these observations it looks like one of the network elements (mostly the D-Link wifi router) is dropping a keep alive connection prematurely. May be issue is specific to web sockets. For some reason neither sync gateway nor the server is able to detect the issue. Irrespective of network issues, I presume sync api and gateway have a way of detecting connection problems and either rectify automatically or change the state to "NOT RUNNING" but neither of this happened. A simple ping-pong can perhaps detect the issue. What puzzles me is long after the app is killed the server still thinks connection is active and doesn't close the connection. I am taking bout hours here not minutes. This is not only an issue of syncing but accumulation of open sockets will eventually cause widespread problems.

and a previous email:

> Attached the logs from IOS app. look for "2017-03-25 05:15:38 +0000 Push Replication Status: IDLE" after which sync stopped working. You can also search for "Push Replication Status" for status changes in the logs. ....  tried on 2 different networks to rule out any network issue and is able to reproduce the issue. I too tried several scenarios but I was not able to reproduce the issue. Would like to know if you guys suspect any scenarios when these issues can happen.

--------
* Version:   1.4
* Client OS: iOS
* Server:    Sync Gateway 1.4 (ubuntu servers hosted on EC2)

**Comment by tleyden** [comment] 2017-03-27 19:32
>  What puzzles me is long after the app is killed the server still thinks connection is active and doesn't close the connection. I am taking bout hours here not minutes. 

If the client is abruptly disappearing (maybe due to network connectivity issues?), then the server will never be notified to tear down the socket, and the server will only be able to clean up it's side of the socket after the `tcp_keepalive_time` expires.  On Linux, that [defaults to 2 hours](http://tldp.org/HOWTO/TCP-Keepalive-HOWTO/usingkeepalive.html)

**Comment by tleyden** [comment] 2017-03-27 19:36
> Push Replication Status: IDLE" after which sync stopped working.

@pasin I just forwarded you the client side logs.  Can you take a look and comment if anything looks broken on the Couchbase Lite side?

**Comment by pasin** [comment] 2017-03-27 20:40
Do I understand correctly that we are looking into a push replicator not pull replicator issue?

When leaving the push replicator idle for 5 mins, what did happen on the client side if there are new docs or new updates to push? Is there an error?

**Comment by pasin** [comment] 2017-03-27 20:41
I looked at the Simulator-WiFi-Logs.txt and I saw the following but I don't know if I was looking at the right lines in the log messages or not.

```
2017-03-27 22:04:49.770 ShopInbox[24414:1680163] [CouchbaseManager.swift:165] replicationChanged - Push Replication Status: IDLE
2017-03-27 16:34:49 +0000 Completed changes count 0/0
2017-03-27 22:09:03.985 ShopInbox[24414:1708724] [error] Connection failed. Server error., bad gateway
2017-03-27 22:09:03.986 ShopInbox[24414:1708724] [info] Status was: 502
2017-03-27 22:09:03.987 ShopInbox[24414:1708724] [info] ApptentiveAPIRequest failed: Server error., bad gateway
20
```

**Comment by varmax** [comment] 2017-03-28 10:07
I meant pull replication. The issue is with data getting syncing from Server to the App.

**Comment by pasin** [comment] 2017-03-28 21:06
I was confused because only push replication is mentioned the the comments here. I need some clarification. 

1. After the pull replication became IDLE for 5 mins, the pull replication stopped working and kept in IDEL state without an error?

2. Does it help if you bring the device offline and online? 

3. Does it help if using longpoll instead of websocket? You can disable the websocket by setting a CBLReplication.customProperties with ["websocket": NO].

I suspected that the issue here is related to the half close connection, the same or similar to #1551. I couldn't comment the reason why it is happening only on a specific router.

**Comment by varmax** [comment] 2017-03-29 06:44
Hi Pasin,
     Please find my replies inline

     1. After the pull replication became IDLE for 5 mins, the pull replication stopped working and kept in IDEL state without an error?
     Ans: Correct

    2. Does it help if you bring the device offline and online?
    Ans: Yes. Replication starts working immediately.

    3. Does it help if using longpoll instead of websocket? You can disable the websocket by setting a CBLReplication.customProperties with ["websocket": NO].
   Ans: Did not make any difference with ["websocket": NO]

About the issue being specific to a router, after we sent those details, we checked on different routers using same Internet Service Provider. Issue still persists. So I think issue is not specific to the router but to the ISP.

**Comment by pasin** [comment] 2017-03-29 18:30
It seems like the issue you are seeing the half close connection issue that the socket of the other side of the connection is closed without notice by the client/replicator. 

We have a workaround that helps detecting the half close connection. Basically if the replicator is idle for a specific timeout, calculated as 110% of the heartbeat value (the default value of the heartbeat is 5 mins.) set to the replication, the replicator will restart itself so that it will recreate the current socket connection.

The timeout implementation was not included in 1.4.0 but is currently in the Master branch as the fix for #1551. Are you able to build the binary from the master branch?

**Comment by pasin** [comment] 2017-03-29 18:30
To build from the master branch, you could do the following steps:
1. $git clone https://github.com/couchbase/couchbase-lite-ios.git
2. $git submodule update --init --recursive
3. Open the project with the xcode.
4. Select `Ci iOS` scheme with the Generic iOS Device.
5. Run Product > Archive
6. You can get the build binary from the archive.

**Comment by kamalk2** [comment] 2017-03-30 11:12
I created the binary with the procedure mentioned above. But when I try to add it to the project manually or from Build Phases-> Link Binary with Libraries in XCode, it keeps throwing the following errors:
1. Use of undeclared type 'CBLModel'
2. Use of undeclared type 'CBL Database'; 'CBL Replication'; 'CBLManager', etc
3. Type 'NSNotification.Name' has no member 'cblReplicationChange'

Can you please tell me what I am missing here?!

**Comment by pasin** [comment] 2017-03-30 15:11
I'm not sure what the issue is. I will try that with XCode 8.3.

Meanwhile, you can download the prebuilt binary from here http://latestbuilds.hq.couchbase.com/couchbase-lite-ios/1.4.1/ios/1.4.1-45/.

**Comment by kamalk2** [comment] 2017-03-31 10:13
The issue I mentioned earlier about the errors in XCode 8.3 was because of the Bridging Header. It was not imported properly. I tried with the prebuilt binary link that you provided, still the sync issue persists, sync stops after 3-5 minutes of idle foreground time.

**Comment by pasin** [comment] 2017-03-31 17:12
With 1.4.1-45, could you enable Sync, SyncVerbose, ChangeTracker, and ChangeTrackerVerbose logging by using CBLManager.enableLogging() and post the log?  Could you also wait for about 6 - 7 mins after the replicator IDLE as well?

**Comment by varmax** [comment] 2017-04-04 06:05
We sent the logs by email on Saturday.

**Comment by pasin** [comment] 2017-04-04 06:07
Who did you sent the email to?

**Comment by varmax** [comment] 2017-04-04 06:09
Sent them to Sachin and Traun as couldn't find your email address. These logs are for both 1.4.0 and 1.4.1

**Comment by pasin** [comment] 2017-04-04 06:10
Can you resend the email to pasin@couchbase.com?

**Comment by varmax** [comment] 2017-04-04 06:11
Done

**Comment by pasin** [comment] 2017-04-04 06:44
From the 1.4.1 log, I can see that the pull replicator restarted after IDLE for 330 seconds, which indicates that the replicator IDLE timeout fix has been activated. 

As the log is fairly wrong, could you point me to the location in 1.4.1 log file where the issue happened? With the IDLE timeout implementation in change tracker, the issue should be resolved.

**Comment by varmax** [comment] 2017-04-04 07:22
We will send the relevant line numbers in the log file. 

Is it possible for the app to notify the Sync API to check the connection and reconnect if needed? We have use cases where users actions trigger some doc changes on server side which need to be synced back to the app so that user can proceed with rest of the workflow. Without this feature it is not possible to guaranty a smooth workflow for the users as there can be huge delays in syncing!

**Comment by pasin** [comment] 2017-04-04 07:38
> Is it possible for the app to notify the Sync API to check the connection and reconnect if needed? 

You could periodically call restart yourself after the replicator is in the IDLE state.

> Without this feature it is not possible to guaranty a smooth workflow for the users as there can be huge delays in syncing!

You could try to reduce the heartbeat to about 50 seconds. The timeout value will be 60 seconds as the minimum value set in the ChangeTracker.

**Comment by pasin** [comment] 2017-04-04 07:51
> Line # 7802, 9097, 8498

All of those lines indicate that the pull replicator was IDLE for more than 330 seconds and the replicator was restarting itself. After the replicator got restarted, from the log, the replicator could pull some data again. This indicates that the change tracker timeout is working in 1.4.0.

If 330 seconds is to long now, you can try to fine tune the heartbeat value in the customProperties (e.g. 50000 ms).

**Comment by varmax** [comment] 2017-04-04 08:01
You mean 1.4.1 right (the line numbers were for 1.4.1 one logs)?
In 1.4.0 it doesn't work after 330. It just stays in that state.

**Comment by pasin** [comment] 2017-04-04 14:54
Sorry, I meant 1.4.1 not 1.4.0.

**Closed** 2017-06-02 21:44 UTC
Labels: pmin
