### ISSUE TITLE
iOS dylib was compiled for MacOSX

### ISSUE THREAD

**Issue by LutherBaker** [couchbase/couchbase-lite-ios#2213] opened 2018-10-07 14:31 UTC
`ld: warning: linking ObjC for iOS Simulator, but dylib (<redacted_project_path>/Couchbase_2-1-1/CouchbaseLite.framework/CouchbaseLite) was compiled for MacOSX`

Steps to recreate

1. New project
2. Download the Objective-C Couchbase from https://docs.couchbase.com/couchbase-lite/2.1/objc.html
3. Unzip and navigate to the `iOS` folder (did this 2x to make sure)
4. Move the entire iOS directory into my Xcode project and rename directory to Couchbase_2-1-1
5. Drag the actual Couchbase.framework and dylib files into Xcode project
6. Configure Xcode to Embed the binary
7. Build

It builds successfully but results in the following linker warning:

`ld: warning: linking ObjC for iOS Simulator, but dylib (<redacted_project_path>/Couchbase_2-1-1/CouchbaseLite.framework/CouchbaseLite) was compiled for MacOSX`

--------
* Version:   couchbase-lite-objc_community_2.1.1
* Client OS: iOS, Xcode 9.4.1
* Server:    none

**Comment by pasin** [comment] 2018-10-07 17:57
I just tested the steps above and I couldn't reproduce this issue. From the error, it does seem like the MacOS framework was used in the project somehow.

**Comment by djpongh** [comment] 2018-10-08 15:37
problem with Xcode 9.4.1? @pasin, I assume you're on Xcode 10.0?

**Comment by pasin** [comment] 2018-10-08 22:43
Yes, I can reproduce the warning with XCode 9.4.1 but not with XCode 10. The binary seems to be usable with the simulator. I'm not sure what is causing that.

**Comment by pasin** [comment] 2018-10-08 22:45
@LutherBaker Are there any other issues when using with binary except the warning?

**Comment by LutherBaker** [comment] 2018-10-10 18:27
Preliminary testing was successful (copied in some code from a tutorial) but I didn't test it significantly.

**Comment by djpongh** [comment] 2018-10-11 16:17
@LutherBaker, thanks for the update. We'll close this for now but reopen if you do find an issue.

**Closed by djpongh** 2018-10-11 16:17 UTC
