### ISSUE TITLE
CBL Swift 2.0 Replicator Failed to Notify TCP Disconnection

### ISSUE THREAD

**Issue by jayzhanghs** [couchbase/couchbase-lite-ios#1997] opened 2017-12-26 19:32 UTC
We found whenever the connection got dropped, e.g. due to server side timeout, between CBL and Server, the CBLSwift SDK does output a log with something like "TIC TCP Conn Error", but it doesn't notify the user via the DB change listener or replicator change listener, so our application still sees the replication status as "busy" and keeps waiting.

Could you add a notification of such in CBL? 

Thanks,

--------
* Version:   DB21
* Client OS: iOS 11
* Server:    NAME_AND_VERSION

**Comment by rajagp** [comment] 2017-12-27 04:06
Seems to be a duplicate of https://github.com/couchbase/couchbase-lite-ios/issues/1978

**Comment by djpongh** [comment] 2017-12-28 17:31
agreed. closing as dup of #1978

**Closed by djpongh** 2017-12-28 17:31 UTC
