### ISSUE TITLE
Crash saving to database in dev branch

### ISSUE THREAD

**Issue by brendand** [couchbase/couchbase-lite-ios#1224] opened 2016-04-26 05:27 UTC
I'm not sure if I should be posting crash reports on dev branch builds, but I thought you might want to see this. I'm using autosave with an autosaveDelay of 2. So when I make a change and then wait a couple seconds, I get this crash. A possible format string error.

```
23:21:46.762| Database: PUT _id=rec-9c14821deb634801b05fd74e6ff94b6b, _rev=11-2c0ae770fd2626cd292bd56d92b3b18a, _deleted=0, allowConflict=0
23:21:46.762| Database: Begin transaction (level 1)...
23:21:46.762| Database: Commit transaction (level 1)
23:21:46.763| Database: Added: {rec-9c14821deb634801b05fd74e6ff94b6b #12-7a2ac803b9dd77d8dae80fe0580bea94}
23:21:46.763| Database: CBLDatabase[<0x610000120dc0>db-bd6707ed08814faca5a5edd955612d0f]: Posting change notifications: seq 3190494
23:21:46.763| Database: CBLDatabase[<0x618000124560>db-bd6707ed08814faca5a5edd955612d0f]: Notified of 1 changes by CBLDatabase[<0x610000120dc0>db-bd6707ed08814faca5a5edd955612d0f]
23:21:46.763| Database: CBLDatabase[<0x608000134280>db-bd6707ed08814faca5a5edd955612d0f]: Notified of 1 changes by CBLDatabase[<0x610000120dc0>db-bd6707ed08814faca5a5edd955612d0f]
23:21:46.763‖ Database: CBLDatabase[<0x618000124560>db-bd6707ed08814faca5a5edd955612d0f]: Posting change notifications: seq (3190494)
23:21:46.763| Database: --> created {rec-9c14821deb634801b05fd74e6ff94b6b #12-7a2ac803b9dd77d8dae80fe0580bea94}
23:21:46.763‖ Database: CBLDatabase[<0x608000134280>db-bd6707ed08814faca5a5edd955612d0f]: Posting change notifications: seq (3190494)
2016-04-25 23:21:46.768 Tap Forms[67040:7496521] push state: 3
2016-04-25 23:21:46.847 Tap Forms[67040:7496728] *** ASSERTION FAILED: !object || [object isKindOfClass: [CBL_RevID class]]
2016-04-25 23:21:46.847 Tap Forms[67040:7496728] *** Assertion failure in -[CBL_RevID isEqual:](), /Users/brendan/Projects/iPhone/couchbase-lite-ios/Source/CBL_RevID.m:40
!object || [object isKindOfClass: [CBL_RevID class]]

2016-04-25 23:22:15.523 Tap Forms[67040:7496728] An uncaught exception was raised
2016-04-25 23:22:15.523 Tap Forms[67040:7496728] !object || [object isKindOfClass: [CBL_RevID class]]
2016-04-25 23:22:15.523 Tap Forms[67040:7496728] (
	0   CoreFoundation                      0x00007fff8ee9c4f2 __exceptionPreprocess + 178
	1   libobjc.A.dylib                     0x00007fff89f9bf7e objc_exception_throw + 48
	2   CoreFoundation                      0x00007fff8eea11ca +[NSException raise:format:arguments:] + 106
	3   Foundation                          0x00007fff91cb516e -[NSAssertionHandler handleFailureInFunction:file:lineNumber:description:] + 169
	4   CouchbaseLite                       0x0000000100dac6e1 _AssertFailed + 833
	5   CouchbaseLite                       0x0000000100df0ed1 -[CBL_RevID isEqual:] + 177
	6   CoreFoundation                      0x00007fff8ee34d4c -[__NSSingleObjectSetI member:] + 44
	7   CoreFoundation                      0x00007fff8ee053a6 -[NSSet containsObject:] + 22
	8   CouchbaseLite                       0x0000000100d6b723 -[CBL_SQLiteStorage getRevisionHistory:backToRevIDs:] + 1011
	9   CouchbaseLite                       0x0000000100cc79b4 -[CBLDatabase(Internal) getRevisionHistory:backToRevIDs:] + 244
	10  CouchbaseLite                       0x0000000100cea780 -[CBLRestPusher uploadChanges:fromDiffs:] + 1872
	11  CouchbaseLite                       0x0000000100ce9d0c __30-[CBLRestPusher processInbox:]_block_invoke + 300
	12  CouchbaseLite                       0x0000000100cfebd2 -[CBLRemoteRequest respondWithResult:error:] + 258
	13  CouchbaseLite                       0x0000000100d012b3 -[CBLRemoteJSONRequest didFinishLoading] + 883
	14  CouchbaseLite                       0x0000000100da8486 __57-[CBLRemoteSession URLSession:task:didCompleteWithError:]_block_invoke + 166
	15  CouchbaseLite                       0x0000000100da6a87 __38-[CBLRemoteSession requestForTask:do:]_block_invoke + 183
	16  CoreFoundation                      0x00007fff8ee314ac __CFRUNLOOP_IS_CALLING_OUT_TO_A_BLOCK__ + 12
	17  CoreFoundation                      0x00007fff8ee10d05 __CFRunLoopDoBlocks + 341
	18  CoreFoundation                      0x00007fff8ee10a6b __CFRunLoopRun + 2347
	19  CoreFoundation                      0x00007fff8ee0fed8 CFRunLoopRunSpecific + 296
	20  Foundation                          0x00007fff91b85dd9 -[NSRunLoop(NSRunLoop) runMode:beforeDate:] + 270
	21  CouchbaseLite                       0x0000000100cd401a -[CBL_RunLoopServer runServerThread] + 506
	22  Foundation                          0x00007fff91b96d64 __NSThread__start__ + 1351
	23  libsystem_pthread.dylib             0x00000001013c0805 _pthread_body + 131
	24  libsystem_pthread.dylib             0x00000001013c0782 _pthread_body + 0
	25  libsystem_pthread.dylib             0x00000001013bdfa1 thread_start + 13
)
```
--------
* Version:   1.3 dev branch commit e0cddbe0175c52a5839acd19be07aef52fa0effc using debug build.
* Client OS: OS X 10.11.4
* Server:    Cloudant

**Comment by snej** [comment] 2016-04-26 19:01
Yes, please do report dev-branch bugs! It's very helpful to find problems early. Just make sure to specify the commit (as you did, thanks.)

This is a regression from a recent refactoring to represent revision IDs as a `CBL_RevID` class instead of NSStrings. Looks like there is a code path in the replicator where something is still using a string…

**Comment by snej** [comment] 2016-04-26 19:53
Merged to dev branch; closing.

**Closed by snej** 2016-04-26 19:53 UTC
