### ISSUE TITLE
One-shot replication crashing

### ISSUE THREAD

**Issue by dyowee** [couchbase/couchbase-lite-ios#1232] opened 2016-04-28 01:03 UTC
--------
* Version:   1.2
* Client OS: iOS
* Server:    CouchDB 1.5.x

---------

2016-04-27 20:55:53.565 TM[1644:44494] CFNetwork SSLHandshake failed (-9806)
2016-04-27 20:55:53.566 TM[1644:44494] NSURLSession/NSURLConnection HTTP load failed (kCFStreamErrorDomainSSL, -9806)
2016-04-27 20:55:53.567 TM[1644:44484] critical: 
Native stacktrace:

2016-04-27 20:55:53.748 TM[1644:44484] critical: 	0   TM                       0x002bb0dd mono_handle_native_sigsegv + 317
2016-04-27 20:55:53.748 TM[1644:44484] critical: 	1   TM                       0x002c5f36 mono_sigsegv_signal_handler + 214
2016-04-27 20:55:53.748 TM[1644:44484] critical: 	2   libsystem_platform.dylib            0x04c4001b _sigtramp + 43
2016-04-27 20:55:53.749 TM[1644:44484] critical: 	3   ???                                 0xffffffff 0x0 + 4294967295
2016-04-27 20:55:53.749 TM[1644:44484] critical: 	4   TM                       0x004aaf24 -[CBLRemoteRequest respondWithResult:error:] + 75
2016-04-27 20:55:53.749 TM[1644:44484] critical: 	5   TM                       0x004ac1e2 -[CBLRemoteRequest connection:didFailWithError:] + 282
2016-04-27 20:55:53.749 TM[1644:44484] critical: 	6   CFNetwork                           0x02c78458 ___ZL23_NSURLConnectionDidFailP16_CFURLConnectionP9__CFErrorPKv_block_invoke + 154
2016-04-27 20:55:53.749 TM[1644:44484] critical: 	7   CFNetwork                           0x02ca71d2 __65-[NSURLConnectionInternal _withConnectionAndDelegate:onlyActive:]_block_invoke + 81
2016-04-27 20:55:53.750 TM[1644:44484] critical: 	8   CFNetwork                           0x02c77570 -[NSURLConnectionInternalConnection invokeForDelegate:] + 145
2016-04-27 20:55:53.750 TM[1644:44484] critical: 	9   CFNetwork                           0x02ca716e -[NSURLConnectionInternal _withConnectionAndDelegate:onlyActive:] + 190
2016-04-27 20:55:53.750 TM[1644:44484] critical: 	10  CFNetwork                           0x02ca735e -[NSURLConnectionInternal _withConnectionAndDelegate:] + 58
2016-04-27 20:55:53.750 TM[1644:44484] critical: 	11  CFNetwork                           0x02c76b96 _ZL23_NSURLConnectionDidFailP16_CFURLConnectionP9__CFErrorPKv + 91
2016-04-27 20:55:53.750 TM[1644:44484] critical: 	12  CFNetwork                           0x02bf2d25 ___ZN27URLConnectionClient_Classic17_delegate_didFailEP9__CFErrorU13block_pointerFvvE_block_invoke + 158
2016-04-27 20:55:53.751 TM[1644:44484] critical: 	13  CFNetwork                           0x02bf0686 ___ZN27URLConnectionClient_Classic18_withDelegateAsyncEPKcU13block_pointerFvP16_CFURLConnectionPK33CFURLConnectionClientCurrent_VMaxE_block_invoke_2 + 113
2016-04-27 20:55:53.751 TM[1644:44484] critical: 	14  libdispatch.dylib                   0x049086fd _dispatch_client_callout + 14
2016-04-27 20:55:53.751 TM[1644:44484] critical: 	15  libdispatch.dylib                   0x048ed228 _dispatch_block_invoke + 377
2016-04-27 20:55:53.751 TM[1644:44484] critical: 	16  libdispatch.dylib                   0x04905f18 ___dispatch_block_create_block_invoke + 20
2016-04-27 20:55:53.751 TM[1644:44484] critical: 	17  CFNetwork                           0x02ada48e _ZN19RunloopBlockContext13_invoke_blockEPKvPv + 24
2016-04-27 20:55:53.751 TM[1644:44484] critical: 	18  CoreFoundation                      0x032cc9a9 CFArrayApplyFunction + 57
2016-04-27 20:55:53.752 TM[1644:44484] critical: 	19  CFNetwork                           0x02ada389 _ZN19RunloopBlockContext7performEv + 143
2016-04-27 20:55:53.752 TM[1644:44484] critical: 	20  CFNetwork                           0x02c9245a _ZThn16_N19RunloopBlockContext24multiplexerClientPerformEv + 20
2016-04-27 20:55:53.752 TM[1644:44484] critical: 	21  CFNetwork                           0x02ada246 _ZN17MultiplexerSource7performEv + 326
2016-04-27 20:55:53.752 TM[1644:44484] critical: 	22  CFNetwork                           0x02ada05e _ZN17MultiplexerSource8_performEPv + 76
2016-04-27 20:55:53.752 TM[1644:44484] critical: 	23  CoreFoundation                      0x032fc6ff __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 15
2016-04-27 20:55:53.753 TM[1644:44484] critical: 	24  CoreFoundation                      0x032f238b __CFRunLoopDoSources0 + 523
2016-04-27 20:55:53.753 TM[1644:44484] critical: 	25  CoreFoundation                      0x032f17a8 __CFRunLoopRun + 1032
2016-04-27 20:55:53.753 TM[1644:44484] critical: 	26  CoreFoundation                      0x032f10e6 CFRunLoopRunSpecific + 470
2016-04-27 20:55:53.753 TM[1644:44484] critical: 	27  CoreFoundation                      0x032f0efb CFRunLoopRunInMode + 123
2016-04-27 20:55:53.753 TM[1644:44484] critical: 	28  Foundation                          0x00c347c2 -[NSRunLoop(NSRunLoop) runMode:beforeDate:] + 308
2016-04-27 20:55:53.753 TM[1644:44484] critical: 	29  TM                       0x0048ffdb -[CBL_RunLoopServer runServerThread] + 349
2016-04-27 20:55:53.754 TM[1644:44484] critical: 	30  Foundation                          0x00c329ba -[NSThread main] + 76
2016-04-27 20:55:53.754 TM[1644:44484] critical: 	31  Foundation                          0x00ce71cc __NSThread__start__ + 1346
2016-04-27 20:55:53.754 TM[1644:44484] critical: 	32  libsystem_pthread.dylib             0x04c2aa26 _pthread_body + 138
2016-04-27 20:55:53.754 TM[1644:44484] critical: 	33  libsystem_pthread.dylib             0x04c2a99c _pthread_body + 0
2016-04-27 20:55:53.754 TM[1644:44484] critical: 	34  libsystem_pthread.dylib             0x04c27f96 thread_start + 34

**Comment by snej** [comment] 2016-04-28 01:17
The crash looks like one that's fixed in 1.2.1, which is about to be released. But that doesn't explain the SSL error. Do connections to this server usually work?

**Comment by dyowee** [comment] 2016-04-28 01:35
Yes sir. We didn't have issues with Couchbase Lite 1.0.x or earlier

**Comment by dyowee** [comment] 2016-04-28 02:59
Updating to 1.2.1 from http://latestbuilds.hq.couchbase.com/couchbase-lite-ios/release/1.2.1/ios/ 
no longer crashes, but still logs this error, and causes the replication to fail

**Comment by snej** [comment] 2016-04-28 03:25
Does it fail every time, or is it intermittent?

When using CBL 1.0.x, were you linking with the iOS 9 SDK? If not, your app wasn't subject to iOS 9's App Transport Security. That might be the difference.

**Comment by dyowee** [comment] 2016-04-28 03:40
I am actually using Xamarin. Do I need to do this for CouchbaseLite 1.2.1?

<key>NSAppTransportSecurity</key>
<dict>
    <key>NSAllowsArbitraryLoads</key>
    <true/>
</dict>

**Comment by dyowee** [comment] 2016-04-28 03:50
Didn't make a difference :(

**Comment by snej** [comment] 2016-04-28 05:07
You're not using the Xamarin/.NET version of Couchbase Lite — there are symbols like `-[CBLRemoteRequest respondWithResult:error:]` in the backtrace.

**Comment by snej** [comment] 2016-04-28 05:10
Try connecting to your CouchDB from the Safari browser on the device. Enter the replication URL into the address bar and see whether it shows a JSON document, or if you get an error about SSL.

Also, on a Mac OS 10.11 system you can use the shell command `nscurl --ats-diagnostics` followed by the URL.

**Comment by dyowee** [comment] 2016-04-28 06:03
Sorry, I am using Xamarin.iOS bindings

**Comment by dyowee** [comment] 2016-04-28 07:27
Using nscurl --ats-diagnostics, all the results are 'FAIL'. What changes do I need to do?

**Comment by snej** [comment] 2016-04-28 16:20
Sounds like the ATS override isn't configured properly. The section in the Info.plist needs to look like
```xml
<key>NSAppTransportSecurity</key>  
     <dict>  
          <key>NSAllowsArbitraryLoads</key><true/>  
     </dict>  
```

**Comment by snej** [comment] 2016-04-28 16:23
By the way, adding `NSAllowsArbitraryLoads` is a good debugging tool, but if ATS turns out to be the cause of the error, you should not ship your app that way. Instead, upgrade the SSL settings of your CouchDB server. That's the purpose of ATS — to get developers to improve the security of their servers.

**Comment by dyowee** [comment] 2016-04-28 21:03
Not sure what you mean by upgrade the SSL settings of the CouchDB server. We have been using it for two years now.

**Comment by snej** [comment] 2016-04-28 22:22
If ATS is rejecting the connection, that means the server doesn't follow current SSL best practices — it may not support TLS 1.2, it may use weak ciphers, the cert may be signed with MD-5 or SHA-1, etc. The `nscurl` command should tell you more.

There are a lot of attacks in the wild against weak SSL connections, so this is something you should pay attention to.

**Comment by dyowee** [comment] 2016-04-29 02:08
Already updated the server, and got all 'PASS' using nscurl, but still getting this issue. :(

**Comment by snej** [comment] 2016-05-26 17:50
Hi, the symptoms have changed a lot since the original report, so could you please file a new issue, with the details of the current (timeout) problem? Thanks.

**Closed by snej** 2016-05-26 17:50 UTC
