### ISSUE TITLE
1.4 Encrypting a new database fails. Existing database encrypt fine.

### ISSUE THREAD

**Issue by brendand** [couchbase/couchbase-lite-ios#1887] opened 2017-09-05 18:08 UTC
Whenever I create a new database and try to encrypt it right away without re-launching my app, I get a failure and the database is not encrypted, but the `_encrypted` file is created within the attachments folder.

I'm receiving the following output and error when calling `changeEncryptionKey:` on my `CBLDatabase` instance.

```
2017-09-05 11:52:29.570181-0600 Tap Forms[1496:743255] Database: Closing <0x1c012c080> /private/var/mobile/Containers/Data/Application/78AF764E-7844-463D-BB90-BA861C5A6D49/Documents/1234.tapforms/db-071ebf165b2f4d6aaa88dbab80452b8b.cblite2
2017-09-05 11:52:29.570949-0600 Tap Forms[1496:743255] Database: Opening CBLDatabase[<0x1c012c080>db-071ebf165b2f4d6aaa88dbab80452b8b]
2017-09-05 11:52:29.571061-0600 Tap Forms[1496:743255] Database: Using CBL_SQLiteStorage for db at /private/var/mobile/Containers/Data/Application/78AF764E-7844-463D-BB90-BA861C5A6D49/Documents/1234.tapforms/db-071ebf165b2f4d6aaa88dbab80452b8b.cblite2; upgrade=0
2017-09-05 11:52:29.571120-0600 Tap Forms[1496:743255] Database: Opening <CBL_SQLiteStorage: 0x1c4676040>
2017-09-05 11:52:29.571143-0600 Tap Forms[1496:743255] Database: Open /private/var/mobile/Containers/Data/Application/78AF764E-7844-463D-BB90-BA861C5A6D49/Documents/1234.tapforms/db-071ebf165b2f4d6aaa88dbab80452b8b.cblite2/db.sqlite3 with SQLite (flags=6(null))
2017-09-05 11:52:29.572885-0600 Tap Forms[1496:743255] Database: No pending doc expirations
2017-09-05 11:52:29.813163-0600 Tap Forms[1496:743255] CBLBlobStore: encrypting /private/var/mobile/Containers/Data/Application/78AF764E-7844-463D-BB90-BA861C5A6D49/Documents/1234.tapforms/db-071ebf165b2f4d6aaa88dbab80452b8b.cblite2/attachments
2017-09-05 11:52:29.813218-0600 Tap Forms[1496:743255]     No blobs to copy; done.
2017-09-05 11:52:29.840866-0600 Tap Forms[1496:743255] Database: Opening <CBL_SQLiteStorage: 0x1c4676040>
2017-09-05 11:52:29.840920-0600 Tap Forms[1496:743255] Database: Open /private/var/mobile/Containers/Data/Application/78AF764E-7844-463D-BB90-BA861C5A6D49/Documents/1234.tapforms/db-071ebf165b2f4d6aaa88dbab80452b8b.cblite2/db.sqlite3 with SQLite (flags=6, encryption key given)
2017-09-05 11:52:29.843054-0600 Tap Forms[1496:743255] SQLite message: recovered 60 frames from WAL file /private/var/mobile/Containers/Data/Application/78AF764E-7844-463D-BB90-BA861C5A6D49/Documents/1234.tapforms/db-071ebf165b2f4d6aaa88dbab80452b8b.cblite2/db.sqlite3-wal
2017-09-05 11:52:29.843176-0600 Tap Forms[1496:743255] WARNING: SQLite error (code 26): file is encrypted or is not a database {at errorLogCallback:117}
2017-09-05 11:52:29.843200-0600 Tap Forms[1496:743255] DB Error: 26 "file is encrypted or is not a database"
2017-09-05 11:52:29.843214-0600 Tap Forms[1496:743255] DB Query: SELECT count(*) FROM sqlite_master
2017-09-05 11:52:29.843234-0600 Tap Forms[1496:743255] WARNING: CBL_SQLiteStorage: database is unreadable (err 26) {at -[CBL_SQLiteStorage decryptWithKey:error:]:300}
2017-09-05 11:52:29.843372-0600 Tap Forms[1496:743255] WARNING: MYAction: Error cleaning up step #3: Error Domain=CBLHTTP Code=401 "unauthorized" UserInfo={NSLocalizedFailureReason=unauthorized, NSLocalizedDescription=unauthorized} {at -[MYAction cleanUp:]:127}
```

I've tried pre-closing my CBLManager (including a separate background CBLManager), then opening up just the main CBLManager (without the background one this time) to see if that helps, but it doesn't. 

But if I create the database, then quit my app completely, then open the database, I can encrypt it fine. 

So there's something odd about a newly created database that's preventing it from completing the encryption process.

When I look inside the cblite2 folder, I see the database and am able to open it in a separate SQLiteManager tool without requiring a key, but inside the attachments folder I see the `_encryption` file is there. So it tried to encrypt, but aborted the process.

I'm not sure what's causing this problem yet though. So I'm not sure if it's something wrong with my code or something wrong inside CBLDatabase causing the encryption to fail.

In any case, the weird thing is that YES is returned from the call to `changeEncryptionKey:`, so it thinks it succeeded and there is nothing in the NSError either.

--------
* Version:   1.4.1
* Client OS: iOS 11 && macOS 10.12.6
* Server:    n/a

**Comment by brendand** [comment] 2017-09-12 15:40
So is this something wrong I might be doing? Or is there a bug in CBL 1.4.1 that's not passing in the encryption key when it re-opens the database?

Really all I'm doing is this:

```
NSString *key = get key from user...

BOOL didEncrypt = [self.databaseDocument.couchDatabase changeEncryptionKey:key error:&error];
if (!didEncrypt) {
   // Couchbase Lite reports back that didEncrypt is YES, even though it's failing and there's no error in the NSError.
  // So this block doesn't get called in this situation.
}
```

**Comment by snej** [comment] 2017-09-12 17:33
It's definitely a bug. To clarify: does this happen only if you rekey immediately after creating the db, not if you add a doc first?

**Comment by brendand** [comment] 2017-09-12 18:59
It happens even after adding a document to the database. So it doesn't matter if the database is empty or has data in it. But only after creating the database in the first session.

If I create the database, then quit the app, then launch the app, which re-opens the already created database, then rekey works.

**Comment by snej** [comment] 2017-09-12 19:13
That's very strange, because we have unit tests that exercise that exact scenario. (DatabaseEncryptionTests.m:284-362)

**Comment by brendand** [comment] 2017-09-12 20:15
Ya, I was looking at that test and I didn't understand why it's failing for me after creating a new db.

**Comment by pasin** [comment] 2017-10-03 03:30
I couldn't reproduce this issue. Ether one of the following code works fine on an iOS Simulator:

Using databaseNamed:
```Objective-C
    NSError *error;
    _db = [[CBLManager sharedInstance] databaseNamed:@"db" error:&error];
    if (!_db) {
        NSLog(@"Cannot create a database: %@", error);
    }
    
    if (![_db changeEncryptionKey: @"seekrit" error: &error]) {
        NSLog(@"Cannot set the encryption key: %@", error);
    }
    
    CBLDocument *doc = [_db createDocument];
    if (![doc putProperties:@{@"foo": @"bar"} error:&error])
        NSLog(@"Cannot save a document : %@", error);
```

Using openDatabaseNamed:
```Objective-C
    NSError *error;

    CBLDatabaseOptions *options = [[CBLDatabaseOptions alloc] init];
    options.create = YES;
    _db = [[CBLManager sharedInstance] openDatabaseNamed:@"db" withOptions:options error:&error];
    if (!_db) {
        NSLog(@"Cannot create a database: %@", error);
    }
    
    if (![_db changeEncryptionKey: @"seekrit" error: &error]) {
        NSLog(@"Cannot set the encryption key: %@", error);
    }
    
    CBLDocument *doc = [_db createDocument];
    if (![doc putProperties:@{@"foo": @"bar"} error:&error])
        NSLog(@"Cannot save a document : %@", error);
```

**Comment by pasin** [comment] 2017-10-03 03:56
Please provide more info about reproducible steps or a sample app that reproduces the issue.

I'm closing the issue as not being able to reproduce. We could reopen the issue when we have more info. Thanks!

**Closed by pasin** 2017-10-03 03:56 UTC
Labels: bug, ready

**Comment by brendand** [comment] 2017-10-08 01:54
It turns out this issue was caused by Couchbase and Couchbase Listener still being in memory when I closed the database. Solving that leak problem fixed this for me too.
