### ISSUE TITLE
Support for Apple Silicon (arm64) for macOS

### ISSUE THREAD

**Issue by WarWithinMe** [couchbase/couchbase-lite-ios#2775] opened 2020-11-15 12:23 UTC
**Describe the bug**
CouchbaseLite currently can't build for the arch Apple Silicon (arm64)

**Expected behavior**
Couchbaselite should produce a framework that contains x86_64 and arm64 arch.

**Platform (please complete the following information):**
 - OS: macOS 10.15
 - Couchbase Version2.8.1
- XCode 12.2

**Comment by jayahariv** [comment] 2020-11-30 00:35
You can follow its here: [CBL-1474](https://issues.couchbase.com/browse/CBL-1474)

Closing this, since duplicate of the Jira ticket.

**Closed by jayahariv** 2020-11-30 00:35 UTC

**Comment by jasonsilberman** [comment] 2021-02-18 17:59
I saw this issue and I am still having this issue. I checked out the Jira ticket mentioned above and it is marked as closed, however, there has not been a new release of the framework since then.

When might there be a new release that would Apple Silicon?

**Comment by jayahariv** [comment] 2021-02-18 22:44
There is an upcoming release 2.8.4, which will include the Apple Silicon support. Once it's available, you can download the XCFramework or use the SPM.
