### ISSUE TITLE
CBL syncing crash without any bug report

### ISSUE THREAD

**Issue by Tamil-Arya** [couchbase/couchbase-lite-ios#2092] opened 2018-03-06 09:00 UTC
**Problem** : After 8 hours, while come to online app start crashing. below are scenario to reproduce the issues.  

1. Put device in offline and enable Airplane mode
2. Create around 50-60 document each with 20-30 images and attachments 
3. Leave device idle in offline/airplane mode for at-least 8 hours 
4. Come online try to sync changes 
5. App crashes continuously

Same crash is not happing with less number of document.

**Crash log report** :

There is no crash report for the issue, while reproducing the issue device automatically lost the connection from the Xcode (look at below image). So, there is no report for the issue where the crash and why this crash happens. 

![screen shot 2018-03-01 at 5 14 38 pm](https://user-images.githubusercontent.com/13419184/37023073-ce1bf28c-214a-11e8-8b85-e4e32aa47d62.png)

( **Note** : if offline it working fine when comes online app start crashing )

* Version:   CBL v1.4
* Client OS: iOS 9.3, iPad 3
* Server:    CouchDB

**Comment by pasin** [comment] 2018-03-06 16:45
Can you try to connect your device with the XCode and rerun the app in debug mode? XCode should break at the place that it crashes. It is also possible to be a memory issue. Can you do the memory profile and see if the app crashes because of running out of memory?

**Comment by martinrybak** [comment] 2018-04-18 18:58
This appears to be a duplicate of #2130.

**Comment by djpongh** [comment] 2018-04-20 21:40
Closing and will track from #2130

**Closed by djpongh** 2018-04-20 21:40 UTC
Labels: needsmoreinfo
