### ISSUE TITLE
Why CBLModel use key named 'type' for different model?

### ISSUE THREAD

**Issue by ufosky** [couchbase/couchbase-lite-ios#852] opened 2015-08-10 04:32 UTC
The key 'type' is such a common use in many data models,so for these cases cannot use CBLModel as the model class.
I also try use `_type` for different model for my own model implemetion，but all keys prefixed with `_` are reserved for system use,I cannot save data with a custom key prefix with '_' which returns error.
So I try use other prefix like '@',so the key is '@type',which throws exception,'$type' is conflict CBLQueryBuilder which the where expression use '$' for context variables,'#type' when use CBLQueryBuilder for query the explanation result shows the '#' character is filtered out,like this
```
view.map = {
    if (type == "member")
        emit([id, name], (null));
};
```

**Comment by snej** [comment] 2015-08-10 06:47
Why can't you use the key `type` in CBLModel? That's exactly what it's for.

**Comment by ufosky** [comment] 2015-08-10 08:35
But my data has key 'type' for indicating other thing.Like this:
{
"name":"a.png",
"type":"image",
...
}

**Comment by snej** [comment] 2015-08-11 16:41
CBLModel isn't preventing you from using that. It just adds a mapping to an Obj-C property for convenience. Can you show an actual problem that's occurring in your code because of this?

**Comment by snej** [comment] 2015-08-11 16:43
As for CBLQueryBuilder: I don't have any control over Apple's NSPredicate/NSExpression syntax. There may be a way to quote special characters in property names; take a look at Apple's documentation.

**Comment by ufosky** [comment] 2015-08-12 11:23
Now I implement custom model class using JsonModel,and use `model_type` as the key for distinguish models,the hard work now is how to use the living query for custom model.

**Comment by snej** [comment] 2015-08-12 16:42
I'm closing this since you haven't described any actual problem caused by the `type` property in CBLModel. If you can explain what actual problem is caused for your code, I can reopen the issue.

**Closed by snej** 2015-08-12 16:42 UTC
