### ISSUE TITLE
Blobs sync error when pulling

### ISSUE THREAD

**Issue by vellori** [couchbase/couchbase-lite-ios#2062] opened 2018-02-08 19:05 UTC
Sorry if this is known, I've been trying to figure this out for a while.

My Swift code is as follows:
```
       let chosenImage = info[UIImagePickerControllerOriginalImage] as! UIImage
        let newBlob = "blob_\(Date().timeIntervalSince1970)"
        guard let data = UIImageJPEGRepresentation(chosenImage, 0.6) else {
            return
        }
        let mutableDoc = doc.toMutable()
        let blobData = Blob(contentType: "image/png", data: data)
        mutableDoc.setBlob(blobData, forKey: newBlob)
        try! database.saveDocument(doc)
        dismiss(animated: true) ...
```

Pushing and Pulling worked with NO PROBLEM until I've added the above piece of code. Now when an attachment is added, the doc will not sync to other devices anymore and I can see in Xcode console the following:

```
2018-02-08 18:38:22.316029+0000 Work POC[26268:8974127] CouchbaseLite Sync ERROR: {1}--> blob->blip:40.114.212.35:4984/beer-sample/_blipsync
2018-02-08 18:38:22.316208+0000 Work POC[26268:8974127] CouchbaseLite Sync ERROR: {1} Got error response: HTTP 403 'Attachment's doc not being synced'
```

It looks like a pulling problem, because if I browse **http://xxxxxxxxx/beer-sample/_all_docs?include_docs=true** I see blobs are there:
`
"blob_1518111731.37322":{"@type":"blob","content-type":"image/png","digest":"sha1-zzeKkZrt4024bECpzaqNhut1698=","length":954556},"blob_1518111773.6599":{"@type":"blob","content-type":"image/png","digest":"sha1-zzeKkZrt4024bECpzaqNhut1698=","length":954556},"blob_1518111803.39381":{"@type":"blob","content-type":"image/png","digest":"sha1-FMNpvqoKrpWdue0mIq3yQ/qtAiM=","length":922139},"blob_1518113999.72245":{"@type":"blob","content-type":"image/png","digest":"sha1-9qEL1/DH38Afw2q4M2Nnc/3Wx98=","length":1318156}
`

so I guess Sync/Pulling is not working properly?

Follow my Sync Gateway configuration:
```
{
    "log":["CRUD+", "REST+", "Changes+", "Attach+","HTTP+"],
    "databases": {
        "beer-sample": {
            "server":"http://XXXX",
			"username": "XXXX",
            "password": "XXXX",
			"users": {
                "XXXXXX": {
                    "password": "XXXXX",
                    "disabled": false,
                    "admin_channels": ["*"]
                }
            },
			"unsupported": {
				"replicator_2":true
				},
			"bucket": "beer-sample",
			"import_docs": "continuous",
			"enable_shared_bucket_access": true,
			 "sync":`function(doc) {channel(doc.channels);}`
            }
    },
	"CORS": {
        "Origin":["*"],
        "LoginOrigin":["*"],
        "Headers":["Content-Type"],
        "MaxAge": 1728000
    }
}
```

--------
* Version:   CouchbaseLiteSwift 2.0 DB21
* Client OS: ios 11
* Server:    Sync GW 1.5.1

**Comment by rajagp** [comment] 2018-02-08 19:11
Hmm...I don't know if this is the reason  but I noticed that you have a JPEG image (`UIImageJPEGRepresentation`) but you are setting contentType to `image/png`.

Regardless, can you specify the right content type
```
 let blob = Blob.init(contentType: "image/jpeg", data: imageData) 
```

**Comment by pasin** [comment] 2018-02-08 21:29
We have fixed pulling blob issues in DB22 which will be released soon. Meanwhile you could build the binary from `feature/2.0` branch and try to see if the problem is gone or not.

**Comment by vellori** [comment] 2018-02-09 08:33
thanks, I give it a spin but I've got two errors. I've made the small adaptions on the API and then I've got the error "blip scheme not supported, only ws and was are". so I've changed blip:// to ws:// and now it won't sync at all. I've tried removing the app and reinstalling.

Here's an excerpt of the log:
```
2018-02-09 08:30:26.704690+0000 Work POC[9978:119989] <CBLHTTPLogic: 0x60400009a360>: Auth challenge; credential = <NSURLCredential: 0x60400000d920>: XXXXXXX
2018-02-09 08:30:26.732916+0000 Work POC[9978:119991] [] nw_connection_fillout_tcp_statistics 2 Connection is not ready
2018-02-09 08:30:26.733099+0000 Work POC[9978:119991] [] tcp_connection_get_statistics Failed to get statistics from connection
2018-02-09 08:30:26.758006+0000 Work POC[9978:119989] CouchbaseLite BLIP Info: {Connection#1} Connected!
2018-02-09 08:30:26.783434+0000 Work POC[9978:119988] CouchbaseLite BLIP ERROR: {BLIPIO#2}==> litecore::blip::BLIPIO ->ws:XXXXX:YYYY/beer-sample/_blipsync
2018-02-09 08:30:26.783723+0000 Work POC[9978:119988] CouchbaseLite BLIP ERROR: {BLIPIO#2} Caught exception handling incoming BLIP message: BLIP message invalid checksum
2018-02-09 08:30:26.828699+0000 Work POC[9978:120008] TIC TCP Conn Missing Error [2:0x6080001711c0]: Generating 1:54
```

This is how I init the Database plus replicator with DB22:
```
        let url = URL(string: Global.SYNCGWURL)!
        let endpoint = URLEndpoint(url: url)
        let replConfig = ReplicatorConfiguration(database: database, target: endpoint)
        let auth = BasicAuthenticator(username: Global.username, password: Global.password)
```

I've checked available docs but I'm not sure what I'm doing wrong now. All help is very appreciated.

**Comment by rajagp** [comment] 2018-02-09 12:40
Ah - so you are on DB22 Couchbase Lite now . Yes- the URI scheme has changed .   I presume you are on SGW 1.5. We should have mentioned it but You will have to update your Sync Gateway to 2.0. This is not (pre) released as yet. But that will happen very shortly - hopefully in next day or two .

**Comment by vellori** [comment] 2018-02-09 13:15
Thanks, this clarify a lot. I suggest to add this requirements on the DB22 release notes as well. Also a clearer log message would help!

Thanks for the support on this, it helped!

**Comment by snej** [comment] 2018-02-12 18:11
>Also a clearer log message would help!

There's protocol version-checking now, but it's only on the server side and doesn't exist in SG 1.5. We should add some on the client side as well to handle this case.

**Comment by snej** [comment] 2018-02-12 18:43
Filed #2063 to handle the version checking.

**Comment by djpongh** [comment] 2018-02-12 22:12
Closing. If there are still issues, please reopen.

**Closed by djpongh** 2018-02-12 22:12 UTC
Labels: P1: high, backlog
