### ISSUE TITLE
2.0: Swift: SesssionAuthenticator doesn't work

### ISSUE THREAD

**Issue by jayzhanghs** [couchbase/couchbase-lite-ios#1927] opened 2017-10-10 14:50 UTC
After logging in and get all the sync_session information, I'm trying to authenticate with SessionAuthenticator: 

        replicatorConfig.authenticator = SessionAuthenticator(sessionID: syncSessionInfo.sessionID, expires: syncSessionInfo.expiration, cookieName: syncSessionInfo.cookieName)

But it always fails with 401 unauthorized. 

The same user login and server works with Android login though.

Tried also BasicAuthenticator with Swift, and it does work.

--------
* Version:   2.0DB016
* Client OS: iOS 11
* Server:    Sync Server 1.5

**Comment by pasin** [comment] 2017-10-10 14:58
Thanks. I will look into this.

**Comment by pasin** [comment] 2017-10-11 18:31
I was not able to reproduce this issue. Here is my configuration:

```Swift
var config = ReplicatorConfiguration(database: db, targetURL: kSyncGatewayUrl)
config.continuous = true
config.authenticator = SessionAuthenticator(sessionID: "9f0b52a91b7190967d0a7edbe2ad65a67dfa262c", expires: "2017-10-12T11:24:06.099959-07:00", cookieName: "SyncGatewaySession")
```

I also inspect the raw request and here is the request header:
```
Sec-WebSocket-Version: 13
Sec-WebSocket-Key: PsxACUoik9koivUBDXfE5Q==
Upgrade: websocket
Connection: Upgrade
User-Agent: CouchbaseLite/2.0.0 (Swift; iOS 11.0; iPhone) Build/0 Commit/4373a8c8
Cookie: SyncGatewaySession=9f0b52a91b7190967d0a7edbe2ad65a67dfa262c
Host: 127.0.0.1:4984
```

@jayzhanghs Can you inspect the session info to see if it's valid or not? If possible, can you capture the HTTP raw request (e.g. using HTTPScoop, Wireshark, or Charles proxy)?

**Comment by jayzhanghs** [comment] 2017-10-12 16:00
@pasin  I double checked the session info is correct. Are you using 2.0DB016 or some other builds? I tried Wireshark, but it just shows binary data or encrypted messages and I can't see the actual request. But here is what is output in Xcode console, not sure if it provides any info?

2017-10-12 11:43:49.216526-0400 CouchBaseLiteTrial[46625:16669125] [] nw_connection_fillout_tcp_statistics 2 Connection is not ready
2017-10-12 11:43:49.216849-0400 CouchBaseLiteTrial[46625:16669125] [] tcp_connection_get_statistics Failed to get statistics from connection
2017-10-12 11:43:49.217174-0400 CouchBaseLiteTrial[46625:16669125] [] nw_connection_copy_host_endpoint 2 Connection has no connected handler
2017-10-12 11:43:49.217307-0400 CouchBaseLiteTrial[46625:16669125] [] nw_connection_copy_host_endpoint 2 Connection has no connected handler
2017-10-12 11:43:49.557674-0400 CouchBaseLiteTrial[46625:16669125] CredStore - performQuery - Error copying matching creds.  Error=-25300, query={
    class = inet;
    "m_Limit" = "m_LimitAll";
    ptcl = htps;
    "r_Attributes" = 1;
    sdmn = "Couchbase Sync Gateway";
    srvr = "jay.xxxxx.com";
    sync = syna;
}
2017-10-12 11:43:49.557900-0400 CouchBaseLiteTrial[46625:16669125] <CBLHTTPLogic: 0x60c000093970>: Auth challenge; credential = (null)
2017-10-12 11:43:49.558030-0400 CouchBaseLiteTrial[46625:16669125] <CBLHTTPLogic: 0x60c000093970>: HTTP auth failed; sent Authorization: (null)  ;  got WWW-Authenticate: Basic realm="Couchbase Sync Gateway"
2017-10-12 11:43:49.558522-0400 CouchBaseLiteTrial[46625:16669125] CouchbaseLite WS WARNING: {1}--> blips:jay.xxxx.com:4984/db/_blipsync
2017-10-12 11:43:49.558712-0400 CouchBaseLiteTrial[46625:16669125] CouchbaseLite WS WARNING: {1} Unexpected or unclean socket disconnect! (reason=WebSocket status, code=401)
2017-10-12 11:43:49.558879-0400 CouchBaseLiteTrial[46625:16669125] CouchbaseLite WS Info: {1} sent 0 bytes, rcvd 0, in 0.000 sec (nan/sec, nan/sec)
2017-10-12 11:43:49.559295-0400 CouchBaseLiteTrial[46625:16669125] CouchbaseLite  Info: ~BLIPIO: Max outbox depth was 0, avg nan
2017-10-12 11:43:49.561186-0400 CouchBaseLiteTrial[46625:16669124] CouchbaseLite Sync ERROR: {1}--> Repl->blips:jay.xxxxx.com:4984/db/_blipsync
2017-10-12 11:43:49.561405-0400 CouchBaseLiteTrial[46625:16669124] CouchbaseLite Sync ERROR: {1} Got LiteCore error: HTTP/1.1 401 Unauthorized (7/401)

**Comment by jayzhanghs** [comment] 2017-10-16 21:38
@pasin we resolved this issue. It turns out that we saved the new sync session info to the disk, then read it out to log into the CB sync gateway. There's a tiny delay of disk write/read, thus we're actually submitting an invalidated credential.

**Comment by jayzhanghs** [comment] 2017-10-17 14:30
@pasin Actually I was too quick in concluding it was working now. Turns out it's related to running the sync_gateway in SSL (blips) and non-SSL (blip). When running the gateway in SSL version (and the client side uses blips), there is always a CBL error 

```
2017-10-17 09:40:17.385739-0400 CouchBaseLiteTrial[90601:18621590] <CBLHTTPLogic: 0x600000284790>: Auth challenge; credential = (null)
2017-10-17 09:40:17.385850-0400 CouchBaseLiteTrial[90601:18621590] <CBLHTTPLogic: 0x600000284790>: HTTP auth failed; sent Authorization: (null)  ;  got WWW-Authenticate: Basic realm="Couchbase Sync Gateway"
```

followed by 401. 

Running the gateway in non-SSL version (and swift side use blip) then there is no such complaints and the authentication works fine.

Please double check that you're using SSL or not on your side too.

**Comment by pasin** [comment] 2017-10-17 14:37
@jayzhanghs, thanks for the info. Are you using self-sign certificate?

**Comment by jayzhanghs** [comment] 2017-10-17 14:49
@pasin, no, we're using real certificate, not self-signed.

**Comment by pasin** [comment] 2017-10-17 15:51
@jayzhanghs Do you have a test server that I can quickly hit to see the behavior? Does the SSL work on Android?

**Comment by pasin** [comment] 2017-10-17 18:46
@snej could the HTTPS alter the cookie behavior?

**Comment by jayzhanghs** [comment] 2017-10-17 20:09
@pasin we prepared a test server with SSL for you. Is there anyway we can private messaging you?

**Comment by jayzhanghs** [comment] 2017-10-17 20:53
thanks. email sent.

**Comment by pasin** [comment] 2017-10-17 21:29
I have received the email. I have run the test, and I was able to connect/sync without a problem.

Test Code:

```Swift
    func test() {
        Database.setLogLevel(.info, domain: .replicator)
        Database.setLogLevel(.info, domain: .network)
        
        db = try! Database.init(name: "db")
        
        let activity = ["stopped", "offline", "connecting", "idle", "busy"];
        
        let url = URL(string: "blips://couchssl.dev.handshake.com:4984/db")!
        var config = ReplicatorConfiguration(database: db, targetURL: url)
        config.continuous = true
        config.authenticator = SessionAuthenticator(sessionID: "1f97dbb60043f18196469c17628343b30938ef9d",
                                                    expires: "2017-10-18T15:05:00.270000-0400",
                                                    cookieName: "SyncGatewaySession")
        replicator = Replicator(config: config)
        replicator.addChangeListener { (change) in
            let s = change.status
            let a = s.activity
            let e = change.status.error as NSError?
            
            NSLog("> Replicator: \(activity[Int(a.rawValue)]) \(s.progress.completed)/\(s.progress.total), error: \((e != nil) ? e!.description: "<nil>")")
        }
        replicator.start()
    }
```

Log:
```
2017-10-17 14:26:27.774797-0700 TestReplicatorSwift[66527:960786] CouchbaseLite default log level is Debug and above
2017-10-17 14:26:27.797769-0700 TestReplicatorSwift[66527:960786] CouchbaseLite WebSocket Info: CBLWebSocket registered as C4SocketFactory
2017-10-17 14:26:27.798097-0700 TestReplicatorSwift[66527:960786] CouchbaseLite Sync Info: CBLReplicator[<*> blips://couchssl.dev.handshake.com:4984/db]: Starting
2017-10-17 14:26:27.799377-0700 TestReplicatorSwift[66527:960786] CouchbaseLite BLIP Info: {1}--> ->blips:couchssl.dev.handshake.com:4984/db/_blipsync
2017-10-17 14:26:27.799506-0700 TestReplicatorSwift[66527:960786] CouchbaseLite BLIP Info: {1} Opening connection...
2017-10-17 14:26:27.800082-0700 TestReplicatorSwift[66527:960786] CouchbaseLite Sync Info: CBLReplicator[<*> blips://couchssl.dev.handshake.com:4984/db] is connecting, progress 0/0, error: (null)
2017-10-17 14:26:27.802399-0700 TestReplicatorSwift[66527:960864] CouchbaseLite WebSocket Info: CBLWebSocket connecting to couchssl.dev.handshake.com:4984...
2017-10-17 14:26:27.834838-0700 TestReplicatorSwift[66527:960786] CouchbaseLite Sync Info: CBLReplicator[<*> blips://couchssl.dev.handshake.com:4984/db] is connecting, progress 0/0, error: (null)
2017-10-17 14:26:27.840224-0700 TestReplicatorSwift[66527:960786] > Replicator: connecting 0/0, error: <nil>
2017-10-17 14:26:27.855520-0700 TestReplicatorSwift[66527:960864] [] nw_connection_fillout_tcp_statistics 1 Connection is not ready
2017-10-17 14:26:27.855687-0700 TestReplicatorSwift[66527:960864] [] tcp_connection_get_statistics Failed to get statistics from connection
2017-10-17 14:26:27.855965-0700 TestReplicatorSwift[66527:960864] [] nw_connection_copy_host_endpoint 1 Connection has no connected handler
2017-10-17 14:26:27.856117-0700 TestReplicatorSwift[66527:960864] [] nw_connection_copy_host_endpoint 1 Connection has no connected handler
2017-10-17 14:26:27.856273-0700 TestReplicatorSwift[66527:960864] [] nw_connection_copy_host_endpoint 1 Connection has no connected handler
2017-10-17 14:26:27.918523-0700 TestReplicatorSwift[66527:960862] CouchbaseLite WebSocket Info:     useCredential for trust: <NSURLCredential: 0x600000007ba0>: (null)
2017-10-17 14:26:27.996799-0700 TestReplicatorSwift[66527:960862] CouchbaseLite WebSocket Info: CBLWebSocket CONNECTED!
2017-10-17 14:26:27.996988-0700 TestReplicatorSwift[66527:960861] CouchbaseLite BLIP Info: {1} Connected!
2017-10-17 14:26:27.997191-0700 TestReplicatorSwift[66527:960864] CouchbaseLite Sync Info: {1}--> Repl->blips:couchssl.dev.handshake.com:4984/db/_blipsync
2017-10-17 14:26:27.997397-0700 TestReplicatorSwift[66527:960864] CouchbaseLite Sync Info: {1} BLIP Connected
2017-10-17 14:26:27.997655-0700 TestReplicatorSwift[66527:960864] CouchbaseLite Sync Info: {1} now busy
2017-10-17 14:26:27.997847-0700 TestReplicatorSwift[66527:960786] CouchbaseLite Sync Info: CBLReplicator[<*> blips://couchssl.dev.handshake.com:4984/db] is busy, progress 0/0, error: (null)
2017-10-17 14:26:27.997958-0700 TestReplicatorSwift[66527:960786] > Replicator: busy 0/0, error: <nil>
2017-10-17 14:26:27.998575-0700 TestReplicatorSwift[66527:960861] CouchbaseLite Sync Info: {2}--> DB->blips:couchssl.dev.handshake.com:4984/db/_blipsync
2017-10-17 14:26:27.998745-0700 TestReplicatorSwift[66527:960864] CouchbaseLite Sync Info: {1} Local checkpoint 'cp-bdNGRK5ksTimHrV5tRsQ3vwSBLE=' is [88, '(null)']; getting remote ...
2017-10-17 14:26:27.998979-0700 TestReplicatorSwift[66527:960861] CouchbaseLite Sync Info: {2} now idle
2017-10-17 14:26:28.032320-0700 TestReplicatorSwift[66527:960861] CouchbaseLite Sync Info: {1} Received remote checkpoint: '{"local":88}'
2017-10-17 14:26:28.032530-0700 TestReplicatorSwift[66527:960861] CouchbaseLite Sync Info: {1} ...got remote checkpoint: [88, '(null)'] rev='0-1'
2017-10-17 14:26:28.032739-0700 TestReplicatorSwift[66527:960862] CouchbaseLite Sync Info: {3}--> Push->blips:couchssl.dev.handshake.com:4984/db/_blipsync
2017-10-17 14:26:28.032887-0700 TestReplicatorSwift[66527:960864] CouchbaseLite Sync Info: {4}--> Pull->blips:couchssl.dev.handshake.com:4984/db/_blipsync
2017-10-17 14:26:28.033024-0700 TestReplicatorSwift[66527:960862] CouchbaseLite Sync Info: {3} Starting continuous push from local seq 1
2017-10-17 14:26:28.033189-0700 TestReplicatorSwift[66527:960864] CouchbaseLite Sync Info: {4} Starting pull from remote seq (null)
2017-10-17 14:26:28.033307-0700 TestReplicatorSwift[66527:960862] CouchbaseLite Sync Info: {3} Reading 200 changes since sequence 88 ...
2017-10-17 14:26:28.033494-0700 TestReplicatorSwift[66527:960864] CouchbaseLite Sync Info: {4} now busy
2017-10-17 14:26:28.033755-0700 TestReplicatorSwift[66527:960862] CouchbaseLite Sync Info: {3} now busy
2017-10-17 14:26:28.033931-0700 TestReplicatorSwift[66527:960861] CouchbaseLite Sync Info: {2} Reading up to 200 local changes since #88
2017-10-17 14:26:28.034448-0700 TestReplicatorSwift[66527:960861] CouchbaseLite Sync Info: {3} Caught up, at lastSequence 88
2017-10-17 14:26:28.034653-0700 TestReplicatorSwift[66527:960861] CouchbaseLite Sync Info: {3} now idle
2017-10-17 14:26:28.081919-0700 TestReplicatorSwift[66527:960863] CouchbaseLite Sync Info: {2} Looking up 88 revisions in the db (seq '111:6'..'111:110')
2017-10-17 14:26:28.084058-0700 TestReplicatorSwift[66527:960863] CouchbaseLite Sync Info: {2} Responding w/request for 0 revs
2017-10-17 14:26:28.166036-0700 TestReplicatorSwift[66527:960860] CouchbaseLite Sync Info: {4} Caught up with remote changes
2017-10-17 14:26:28.166262-0700 TestReplicatorSwift[66527:960860] CouchbaseLite Sync Info: {4} now idle
2017-10-17 14:26:28.166585-0700 TestReplicatorSwift[66527:960862] CouchbaseLite Sync Info: {1} now idle
2017-10-17 14:26:28.166896-0700 TestReplicatorSwift[66527:960786] CouchbaseLite Sync Info: CBLReplicator[<*> blips://couchssl.dev.handshake.com:4984/db] is idle, progress 0/0, error: (null)
2017-10-17 14:26:28.167036-0700 TestReplicatorSwift[66527:960786] > Replicator: idle 0/0, error: <nil>
```

**Comment by jayzhanghs** [comment] 2017-10-17 21:40
@pasin I copied your code exactly in and still got 401. What's the CBLSwift SDK version you're using? Mine is 2.0.0 build 434 per info list.

**Comment by pasin** [comment] 2017-10-17 21:42
I linked to the code in the current feature/2.0 branch, but that is pretty much the same thing as build 434.

**Comment by pasin** [comment] 2017-10-17 21:48
I tested with iOS 11 iPhoneX simulator. What OS are you testing?

**Comment by jayzhanghs** [comment] 2017-10-17 21:57
I was testing on iOS 11 iPad Air 2 simulator. I switched to iOS 10 iPad Air 2 simulator and it suddenly worked. Then I switched back to iOS 11 and it also worked. Repeated multiple times and it was fine. I also switched back to my original method and it is also working. Very weird.

**Comment by pasin** [comment] 2017-10-17 22:01
Very strange, not quite sure what was going on. Can we close the issue?

**Comment by jayzhanghs** [comment] 2017-10-17 22:56
I tested more and found out the pattern: dynamically obtained session cookie always failed with 401; hard coded cookie information (as in your example code) works only if the app is fresh and didn’t have failed attempts before. Otherwise I’ll have to delete the app then the hard coded session cookie works. 

Please keep this issue open for a few more days.

**Comment by pasin** [comment] 2017-10-17 23:36
I'm wondering if the issue is at the cookie storage or not. Maybe you could test the following scenarios:
1. Having a fresh app installed. Start the Replicator with a session that will expired in 10 mins.
2. Assuming that the replicator work fine, close the app and wait for more than 10 mins to allow the session to be expired.
3. Run the app again with a new session. I'm wondering if the new session will be used or not. If possible, use HTTPScoop or any proxy to capture the header. I believe the issue could be independent from HTTPS.

**Comment by jayzhanghs** [comment] 2017-10-25 17:19
@pasin It turns out this is related to cookies. As we get the credentials from our server before trying the couch sync, the process populated the client HTTP cookies. Then somehow the Swift SDK picks up the cookies and probably overwrote the syncGateWay cookies. I tried commenting out the part of code in Swift SDK repo, but of no avail, so it must be hidden somewhere else in the SDK.

**Comment by pasin** [comment] 2017-10-25 20:47
@jayzhanghs could you help me understand the issue? Do you mean there is a SyncGateway cookie stored in the Apple shared cookie storage and that cookie overwrite the SyncGateway cookie set to SessionAuthenticator?

CBL (down to the LiteCore level) implements its own cookie storage, and CBL should not use any cookies from the Apple shared cookie storage when creating an NSURLSession to connect to SGW. However I have just noticed [this](https://github.com/couchbase/couchbase-lite-ios/blob/feature/2.0/Objective-C/Internal/Replicator/CBLHTTPLogic.m#L142-L150) and I think that might be the root cause of the issue. You may try to comment that part of code and rebuild the binary. Please let me know if that works?

**Comment by jayzhanghs** [comment] 2017-10-26 14:19
@pasin The cookies stored in Apple shared cookie storage might become from our own server's login process, which also passed the SyncGateWay authentication details.

I actually suspected the code part you highlighted in the snippet too and I had tried commenting it out, but didn't help. I had to remove all Apple shared cookies before starting sync to make it work. Tried removing the cookies one by one instead of all, but it didn't help.

**Comment by pasin** [comment] 2017-11-01 05:46
I was able to reproduce the issue that the cookie in the iOS shared cookie storage overwrites the cookie set by Session Authenticator. The fix is very simple and I'm working on it now.

**Comment by pasin** [comment] 2017-11-01 06:04
@jayzhanghs actually comment out this [line](https://github.com/couchbase/couchbase-lite-ios/blob/feature/2.0/Objective-C/Internal/Replicator/CBLHTTPLogic.m#L142-L150) works for me.

**Comment by jayzhanghs** [comment] 2017-11-01 13:53
@pasin Nice that you could reproduce the issue. Weird that commenting out the lines didn't work for me, or maybe when I was trying too many things at a same time when I didn't know what the problem was. Looking forward to the release of the fixed version.

A side question, is there anyway you can list the CouchbaseLite databases created in a mobile app? And when I deleted documents on server via Sync Gateway I received deleted DocumentIDs in database change listener, but the documents are already gone in mobile db. Is there anyway I can get hold of the documents before they were wiped out on mobile so I can do some local conversion work?

**Closed** 2017-11-03 21:32 UTC
Labels: needsmoreinfo

**Comment by jayzhanghs** [comment] 2017-11-08 20:52
@pasin The CBL Swift 2.0 download page still has build 18. When will 19 come out? Build 18 doesn't work with Xcode 9.1.

**Comment by pasin** [comment] 2017-11-09 16:48
What is the issue with XCode 9.1? I have used the DB18 binary with XCode 9.1 and I don't see any issues.

**Comment by jayzhanghs** [comment] 2017-11-09 16:51
It was complaining about Swift code compiled in 4.0 cannot be used in 4.0.2 or 3.2.2. Did you download the DB 18 binary from couchbase [download page](https://www.couchbase.com/downloads/thankyou/community?product=couchbase-lite&version=2.0&platform=swift&prerelease=true)  or you compiled it yourself?

**Comment by pasin** [comment] 2017-11-09 21:13
@jayzhanghs I could see the same error. I was previously using XCode 9 not XCode 9.1. I created a new #1956 to track and fix this for DB20. FYI, DB19 is out but that doesn't work for XCode 9.1. For now, you will need to build the binary yourself or use `Carthage` to build the binary for you. The info about how to build the binary is [here](https://github.com/couchbase/couchbase-lite-ios/tree/feature/2.0). Sorry for the inconvenience.
