### ISSUE TITLE
Deleting Documents in 1.1 release takes more time as compared to release1.0.4

### ISSUE THREAD

**Issue by ashvindersingh** [couchbase/couchbase-lite-ios#737] opened 2015-05-22 20:26 UTC
Executed the following test 
https://github.com/couchbaselabs/iOS-WorkerBee/blob/master/Tests/Test11_DeleteDocs.m for both the 1.0.4 release and 1.1 release.

The sum kpi from 1.04 release = 40.93
The sum kpi from 1.1.0 release =  50.88

**Comment by pasin** [comment] 2015-05-22 23:25
Based on my own test of deleting 1000 docs, 100 bytes each (run 3 times), the result is opposite.

1.0.4:
2015-05-22 12:46:40.648 Perf110[4112:1028184] Time used : 20446.434748 msec.
2015-05-22 12:47:29.750 Perf110[4118:1028498] Time used : 20421.973373 msec.
2015-05-22 12:48:02.625 Perf110[4124:1028824] Time used : 20430.754081 msec.

1.1.0:
2015-05-22 12:48:47.144 Perf110[4132:1029318] Time used : 10315.324748 msec.
2015-05-22 12:49:14.808 Perf110[4137:1029647] Time used : 10327.220748 msec.
2015-05-22 12:50:41.665 Perf110[4150:1030633] Time used : 10349.712914 msec.

@ashvindersingh , could you please review?

**Comment by pasin** [comment] 2015-05-26 18:09
I'm closing this as cannot reproduce.

**Closed by pasin** 2015-05-26 18:09 UTC
Labels: cannotreproduce, chore, performance, ready
