### ISSUE TITLE
Not all documents replicated from sync gateway

### ISSUE THREAD

**Issue by snej** [couchbase/couchbase-lite-ios#2024] opened 2018-01-17 18:55 UTC
[From the forum](https://forums.couchbase.com/t/not-all-documents-replicated-from-sync-gateway/15445), by user davidj:

--------
My iOS app, with CB Lite 1.4.1, uses continuous replication from sync gateway version 1.4 (Couchbase server 4.6.2-3905) to pull documents. When the app is first run it starts pulling down data and eventually the replication goes idle, but not all documents have been replicated. If I kill and restart the app, more documents are replicated. It may require several restarts before all of the documents are replicated from sync gateway. I've turned on logging and I see this pattern in the log:

First app run...
```
    2018-01-15 17:00:43.158 [info][tid:com.facebook.react.JavaScript] Starting Couchbase Sync Gateway replication with https://sgw.CENSORED/master/
    17:00:43.163‖ Router: POST http://lite.couchbase./_replicate + body stream
        Accept: application/json
        Content-Type: application/json
        Connection: keep-alive
        Authorization: Basic dXNlcjpwdw==
        Content-Length: 246
    17:00:43.164‖ Sync: CBLRestPuller[https://sgw.CENSORED/master/] STARTING ...
    17:00:43.165‖ Database: {{ Begin transaction (level 1)...
    17:00:43.165‖ Database: }} Commit transaction (level 1)
    17:00:43.167‖ Sync: CBLRestPuller[https://sgw.CENSORED/master/]: Reachability state = 
    <sgw.CENSORED>:reachable (02), suspended=0
    17:00:43.167‖ Sync: CBLRestPuller[https://sgw.CENSORED/master/]: Going online
    17:00:43.167‖ Sync: CBLRestPuller[https://sgw.CENSORED/master/]: No local checkpoint; not getting 
    remote one
    17:00:43.167‖ Sync: CBLRestPuller[https://sgw.CENSORED/master/] Progress: set active = 1
    17:00:43.167‖ ChangeTracker: CBLSocketChangeTracker[0x6080001da7c0 master]: Starting...
    17:00:43.168‖ ChangeTracker: CBLSocketChangeTracker[0x6080001da7c0 master]: POST 
    //sgw.CENSORED/master/_changes?feed=normal&heartbeat=300000&style=all_docs {
        "Accept-Encoding" = gzip;
        Authorization = "Basic CENSORED";
        "Content-Length" = 80;
        "Content-Type" = "application/json";
        Host = "sgw.CENSORED";
        "User-Agent" = "CouchbaseLite/1.3 (iOS 1.4.1/86c63659b56d87406eac3b1e4db631fe67098139)";
    }
    17:00:43.168‖ ChangeTracker: Changes feed using proxy settings {
        ExceptionsList =     (
            "*.local",
            "169.254/16"
        );
        FTPPassive = 1;
        "__SCOPED__" =     {
            en4 =         {
                ExceptionsList =             (
                    "*.local",
                    "169.254/16"
                );
                FTPPassive = 1;
            };
        };
    }
    17:00:43.168‖ ChangeTracker: CBLSocketChangeTracker[0x6080001da7c0 master]: Started... 
    <https://sgw.CENSORED/master/_changes?feed=normal&heartbeat=300000&style=all_docs>
    17:00:43.169‖ Router: Response -- status=200, body=24 bytes
            Server: CouchbaseLite 1.4.1 (build 88)
            Content-Type: application/json
    17:00:43.169‖ ChangeTracker: CBLSocketChangeTracker[0x6080001da7c0 master]: Event 1 on 
    <__NSCFInputStream: 0x60800010f300>
    17:00:46.952‖ Sync: CBLRestPuller[https://sgw.CENSORED/master/]: Server is Couchbase Sync 
    Gateway/1.4.0
    17:00:46.953‖ Sync: CBLRestPuller[https://sgw.CENSORED/master/] Progress: 0 / 100
    17:00:46.954‖ Sync: CBLRestPuller[https://sgw.CENSORED/master/] queued 100 remote revisions from 
    seq=973093:878993 (100 in bulk, 0 individually)
    17:00:46.954‖ Sync: CBLRestPuller[https://sgw.CENSORED/master/] bulk-fetching 100 remote 
    revisions...
    17:00:46.955‖ RemoteRequest: CBLBulkDownloader[/master/_bulk_get]: Starting...
    17:00:46.955‖ RemoteRequest: CBLRemoteSession starting CBLBulkDownloader[/master/_bulk_get]
    17:00:46.957‖ Sync: CBLRestPuller[https://sgw.CENSORED/master/] Progress: 0 / 200`
```

Eventually getting to this point...

```
    17:07:05.065‖ Sync: CBLRestPuller[https://sgw.CENSORED/master/] Progress: 92712 / 92800
    17:07:05.066‖ Sync: CBLRestPuller[https://sgw.CENSORED/master/] queued 100 remote revisions from seq=973093:972921 (100 in bulk, 0 individually)    
    17:07:05.066‖ Sync: 
    CBLRestPuller[https://sgw.CENSORED/master/] bulk-fetching 100 remote 
    revisions...
    17:07:05.066‖ RemoteRequest: CBLBulkDownloader[/master/_bulk_get]: Starting...
    17:07:05.066‖ RemoteRequest: CBLRemoteSession starting CBLBulkDownloader[/master/_bulk_get]
    17:07:05.070‖ ChangeTracker: CBLSocketChangeTracker[0x6080001da7c0 master]: EndEncountered 
    <__NSCFInputStream: 0x60800010f300>
    17:07:05.070‖ ChangeTracker: CBLSocketChangeTracker[0x6080001da7c0 master]: RESUME
    17:07:05.073‖ Sync: CBLRestPuller[https://sgw.CENSORED/master/]: Caught up with changes!
```

At that point no more documents are replicated. After the restart replication starts again from this 973093 and finds more documents:

```
    17:22:08.747‖ Sync: CBLRestPuller[https://sgw.CENSORED/master/] queued 15 remote revisions from seq=973093:887952 (15 in bulk, 0 individually)
    17:22:08.747‖ Sync: CBLRestPuller[https://sgw.CENSORED/master/] bulk-fetching 15 remote revisions...
```

In this case I had to restart my app two more times before it completed replication. It looks like the rest puller thinks it's caught up when it isn't. Any ideas what's wrong here?

EDIT: I just tried this on the Android version of my app and I'm seeing similar behavior. I had to force stop the app a couple of times to get all documents replicated.

Thanks,
David

--------
* Version:   1.4.1
* Server:    sync gateway version 1.4 (Couchbase server 4.6.2-3905)

**Comment by snej** [comment] 2018-01-17 19:04
(Note: there are more logs in the forum thread that I'm not copying over here.)

David, when you said "At that point no more documents are replicated" — what happens after the log ends? There should be more replicator logging, because the log shows a bulk-GET of 100 revisions starting. And if the replicator received 100 revisions starting at sequence `973093:972921`, it wouldn't be starting from that sequence on its next run.

**Comment by tleyden** [comment] 2018-01-17 19:07
From @pasin:

> Something strange with the last sequence ID. When the replicator is caught up the last sequence ID used to get the changes feed is 94107. But when restarting the replicator, the last sequence ID is 94106:30367.

The compound sequence means that sequence `30367` was triggered by `94106` (typically a channel access grant)

I'm wondering if this is somehow related to https://github.com/couchbase/sync_gateway/issues/3108

David, are you using roles to grant access to docs?  Any chance you can share your sync function?

**Comment by dieseldjango** [comment] 2018-01-17 20:39
I'm not yet using roles to grant access, but I am assigning channels to documents and granting channels to users.

Here's my sync function:
      "sync": `
        function (doc, oldDoc) {
          requireRole('cbadmin_writers');
          if (!doc._deleted && oldDoc && !oldDoc._deleted && oldDoc.tenantId !== doc.tenantId) {
            throw({forbidden: 'tenantId cannot be changed'});
          }
          channel(doc.channels);
        }
      `,

I've attached a complete dump of client and sync gateway logs from a test pass I just ran. I had to kill and restart the app three times to get all docs replicated.

[couchbase-lite-ios-issue-2024.zip](https://github.com/couchbase/couchbase-lite-ios/files/1640509/couchbase-lite-ios-issue-2024.zip)

**Comment by dieseldjango** [comment] 2018-02-09 19:11
I see this issue is in the icebox, and I'm sure your team is largely focused on your 2.0 effort, but can you provide any idea when someone will start looking into this, or suggested workaround? This is preventing us from going to production with our app.

One thing I've thought about trying is to detect when the sync gateway replication goes idle, and to stop and restart it to see if it picks up any more docs. Ugly, but I might give it a try unless you can suggest something better.

**Comment by dieseldjango** [comment] 2018-02-14 15:08
I have a couple more clues about this problem:

- When the client gets into this 'hung' state, checking the _active_tasks API shows completed changes matching changes, but the status is not idle. After one or more restarts and it finally catches up, the status transitions to idle.

- I'm seeing the same problem with P2P pull replication.

**Comment by snej** [comment] 2018-02-14 17:10
Sorry, with 2.0 in the final stretch it's not likely we'll have resources to investigate this until next month (March), unless you're a Couchbase customer and file an urgent support request.

**Comment by geraldapeoples** [comment] 2018-05-22 09:29
I guess replication isn't really important in couchase?

**Comment by tleyden** [comment] 2018-05-22 17:11
@geraldapeoples replication is definitely a core feature!  If you (or anyone) can somehow provide a reproducible test case, it will accelerate the turnaround time on this issue.

**Comment by pasin** [comment] 2018-08-14 20:40
@dieseldjango I knew it's late but I'm looking at this issue now. I'm wondering if you are still encountering this issue. If so, would it possible to enable "SyncVerbose" as and share the log of 1st, 2nd, and 3rd replication?

**Comment by pasin** [comment] 2018-08-15 06:08
I have reviewed the logs and replicator codes but I don't understand how come the last sequence didn't match.

```
20:13:46.558‖ Sync: CBLRestPuller[http://CENSORED.amazonaws.com/master] saved remote checkpoint '94106:94101' (_rev=0-12)
20:13:46.558‖ Sync: CBLRestPuller[http://CENSORED.amazonaws.com/master] Progress: set active = 0
20:14:13.075‖ ChangeTracker: CBLSocketChangeTracker[0x6180001d5450 master]: Started... <http://CENSORED.amazonaws.com/master/_changes?feed=normal&heartbeat=300000&style=all_docs&since=94107>
2
```

The exact `since=94107` issue happened in both 2nd and 3rd run from the log. This is very mysterious given that ChangeTracker doesn't manipulate the sequence number of each change from the changes feed.

**Comment by pasin** [comment] 2018-08-15 06:17
Actually there is one possibility that could cause that behavior. If the change of seq =`94107` has an invalid document ID (e.g. document id begins with `_` but not a design doc) and the change is the last one on the list, it could trigger that issue.

**Comment by pasin** [comment] 2018-08-15 06:48
@dieseldjango from the `cblite-replication-client-third-run.log`, could you get the changes feed result of `/master/_changes?feed=normal&heartbeat=300000&style=all_docs&since=94106%3A94011` to see if it contains a seq=`94107` or not?

**Comment by dieseldjango** [comment] 2018-08-15 19:01
I don't have that database around any longer. I'll see if I can get someone to reproduce it again, but my team is pretty busy with other work right now, including possibly eliminating our reliance on couchbase due to this and some other issues.

**Comment by fedal-mas** [comment] 2018-09-20 17:39
@pasin, I'm using the CBL 2.1.1, SG 2.1.0 and CB Server 5.5.1 on MacOS Mojave (10.14) and I think that I'm having the same issue. 

In my case it get stuck forever saying that it has 27 changes to complete.

Here is the [log](https://gist.github.com/fedal-mas/48984b8d8b5a81e0b30ef8ea5ad37f69).

Any idea of solutions for this problem? Because I'm not being able to migrate from version 1.4 to 2.x.x because of this problem.

**Comment by pasin** [comment] 2018-09-20 17:50
@fedal-mas CBL 2.0 uses different replication mechanism so it's a different issue. Do you mind to create a new issue with the info.

**Comment by pasin** [comment] 2018-09-20 17:50
@fedal-mas Do you have the corresponding SG log?

**Comment by fedal-mas** [comment] 2018-09-20 18:17
@pasin No problems, I can create a new one. 

I will try to generate the SG log later today if I have time, WCS tomorrow morning.

**Comment by jayahariv** [comment] 2021-10-01 00:35
Closing 1.x issue!

**Closed by jayahariv** 2021-10-01 00:35 UTC
Labels: f: Replication, reproduce/investigate, bug, icebox, cross-platform
