### ISSUE TITLE
Behavior of indexUpdateMode = .UpdateIndexBefore

### ISSUE THREAD

**Issue by Cyclic** [couchbase/couchbase-lite-ios#1462] opened 2016-09-26 18:57 UTC
I've set indexUpdateMode to .UpdateIndexBefore to get the count of documents from a view after inserting a new document; however, the view takes minutes to return the new count of documents. The server itself is updated immediately, and I can query for the document. Is there a way to get the count of documents from a view before the index has completed? It doesn't seem correct for the view to take this long to update the index.

Thanks!
--------
* Version:   1.3.1
* Client OS: iOS 10
* Server:    Couchbase 4.1

**Comment by pasin** [comment] 2016-09-26 19:25
How many docs have you indexed? Have you had many views that happen to get indexed at the same time (maybe several views with the same prefix)?

> Is there a way to get the count of documents from a view before the index has completed?

No, there isn't. The view index needs to be completed first. If it appears to block the main thread, you may call `-updateIndexAsync:` method to update the index in the bg, and get the count later once the update index is completed.

**Comment by Cyclic** [comment] 2016-09-26 19:28
Pasin, around 500 or so. It’s not blocking the main thread, it’s just that the count isn’t updated for some time. Does a liveQuery also require the indexes to be updated (my understanding is yes)?

Thanks for the prompt response.

**Comment by pasin** [comment] 2016-09-26 19:37
> around 500 or so. It’s not blocking the main thread, it’s just that the count isn’t updated for some time.

500 docs should be done really fast. I have ran some testing to index 1000 docs (alone without any other operations), the index can be done in less than 100 ms. Can you do some profiling and see if the update index is really slow or not? You may also check if the there are any other database intensive operations occur in the app at the same time?

> Does a liveQuery also require the indexes to be updated (my understanding is yes)?

Yes.

**Comment by snej** [comment] 2016-09-26 20:17
The only thing I know of that would make indexing that slow (other than a _very_ expensive map function!) is if there are lots of updates being made to the database at the same time. CBL's current SQLite database adapter code blocks readers while a thread is writing. If this turns out to be the bottleneck, there is a recent commit you could try cherry-picking, that updates the locking policy so that concurrent reads are allowed during a write.

**Comment by Cyclic** [comment] 2016-09-26 20:20
Yes, the map function is in swift, and calls into JavaScript, so that’s likely the bottleneck. I’ll just double check the commit that you mentioned about the locking policy.

Thanks for the insights!

**Comment by pasin** [comment] 2016-09-28 18:40
From the recent comment, it seems like the slowness comes from using JavaScript map function. Using JavaScript as a map function can be pretty slow compared to using native language. If possible, I would recommend to use the native language.

I'm closing the issue now if the issue is at other places, we could reopen the issue again.

**Closed by pasin** 2016-09-28 18:40 UTC

**Comment by Cyclic** [comment] 2016-09-29 17:35
@pasin, @snej, after doing some digging, we are unable to modify the map function to exist in native code. As a suggestion and feature request, can the map function only be called to reindex the rows that have changed? It seems inefficient and slow because indexing occurs on all rows, regardless of changes. Ironically, the server only indexes what has changed rather than reindexing all items.

Thanks!

**Comment by snej** [comment] 2016-09-29 17:36
> can the map function only be called to reindex the rows that have changed?

It already does that. When you query the view, all documents that have changed since the last indexing are re-indexed.
